### ISSUE TITLE
Application hangs with white screen on debugger attach stage on Node.js 12

### ISSUE THREAD

**Issue by SounD120** [microsoft/vscode-react-native#1000]
Extension have an issue when attaching to the debug process on Node.js 12. It shows such error and hangs without connect to the native application, application shows white screen in such case:
```
******** Unhandled error in debug adapter - Unhandled promise rejection: Error: Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).
    at Object.runtimeConnectionTimeout (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\errors.js:91:12)
    at utils.retryAsync.catch.err (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeConnection.js:110:49)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
Related issues: #998, #997 
**Node.js 10.15.3 have no such issues, so you can use it as a workaround**

**Comment by aidanw** [comment]
I am also seeing this

>OS: darwin x64
Adapter node: v10.2.0 x64
vscode-chrome-debug-core: 6.7.46
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Debugger worker loaded runtime on port 18535
******** Unhandled error in debug adapter - Unhandled promise rejection: Error: Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).
    at Object.runtimeConnectionTimeout (/Users/X/.vscode/extensions/ms-vscode.node-debug2-1.33.0/node_modules/vscode-chrome-debug-core/out/src/errors.js:91:12)
    at utils.retryAsync.catch.err (/Users/X/.vscode/extensions/ms-vscode.node-debug2-1.33.0/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeConnection.js:110:49)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by SounD120** [comment]
Hi @aidanw . Which Node.js version do you use?

**Comment by aidanw** [comment]
v12.1.0

I guess I need to downgrade... but it is pretty frustrating how fragile this ecosystem is!

**Comment by dooleyb1** [comment]
Also experiencing this issue, cannot debug through VSCode however can debug by running `react-native run ios` and by using the tool React Native Developer Tools.

**Comment by ruslan-bikkinin** [comment]
@dooleyb1 please create separate issue and describe your specific case there so we could help you quicker, thanks.
