### ISSUE TITLE
Current workspace does not contain React Native projects

### ISSUE THREAD

**Issue by pt8o** [microsoft/vscode-react-native#1012]
## Actual Behavior
- Run `React Native: Start Packager`
  - "Error while working with workspace: Current workspace does not contain React Native projects. (error code 710)"
- Run `Debug: Start Debugging`
  - Debug sidebar shows progress bar for a few seconds then stops
  - Log (Window) says "Error: spawn react-native ENOENT"

## Expected Behavior
- React Native project launches with debugger attached

## Software versions
- React-Native VS Code extension version: 0.9.3
- VSCode version: 1.34.0
- OS platform and version: Pop!_OS 19.04
- NodeJS version: 11.14.0
- React Native version: 0.58.6
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
(it's empty)
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Error] Failed to start the React Native packager (error code 106)

Stack: Error: Failed to start the React Native packager (error code 106): Error while working with workspace: Current workspace does not contain React Native projects. (error code 710)
	at Function.getWrappedError (/home/lh/.vscode/extensions/msjsdiag.vscode-react-native-0.9.3/src/common/error/internalError.js:35:16)
	at Function.wrapError (/home/lh/.vscode/extensions/msjsdiag.vscode-react-native-0.9.3/src/common/error/errorHelper.js:17:44)
	at handleErrors.resultOfCode.done.reason (/home/lh/.vscode/extensions/msjsdiag.vscode-react-native-0.9.3/src/common/entryPointHandler.js:43:72)
	at _rejected (/home/lh/.vscode/extensions/msjsdiag.vscode-react-native-0.9.3/node_modules/q/q.js:844:24)
	at /home/lh/.vscode/extensions/msjsdiag.vscode-react-native-0.9.3/node_modules/q/q.js:870:30
	at Promise.when (/home/lh/.vscode/extensions/msjsdiag.vscode-react-native-0.9.3/node_modules/q/q.js:1122:31)
	at Promise.promise.promiseDispatch (/home/lh/.vscode/extensions/msjsdiag.vscode-react-native-0.9.3/node_modules/q/q.js:788:41)
	at /home/lh/.vscode/extensions/msjsdiag.vscode-react-native-0.9.3/node_modules/q/q.js:604:44
	at runSingle (/home/lh/.vscode/extensions/msjsdiag.vscode-react-native-0.9.3/node_modules/q/q.js:137:13)
	at flush (/home/lh/.vscode/extensions/msjsdiag.vscode-react-native-0.9.3/node_modules/q/q.js:125:13)
	at process._tickCallback (internal/process/next_tick.js:61:11)

```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
[Extension Host] debugger listening on port 62927
workbench.main.js:4342 Overwriting grammar scope name to file mapping for scope source.swift.
Old grammar file: file:///usr/share/code/resources/app/extensions/swift/syntaxes/swift.tmLanguage.json.
New grammar file: file:///home/lh/.vscode/extensions/kasik96.swift-0.0.3/syntaxes/swift.tmLanguage
register @ workbench.main.js:4342
workbench.main.js:238 [Extension Host] (node:31773) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ workbench.main.js:238
workbench.main.js:2365 Error: Error while working with workspace: Current workspace does not contain React Native projects. (error code 710)
	at Function.getInternalError (/home/lh/.vscode/extensions/msjsdiag.vscode-react-native-0.9.3/src/common/error/errorHelper.js:10)
	at Function.selectProject (/home/lh/.vscode/extensions/msjsdiag.vscode-react-native-0.9.3/src/extension/commandPaletteHandler.js:332)
	at Function.startPackager (/home/lh/.vscode/extensions/msjsdiag.vscode-react-native-0.9.3/src/extension/commandPaletteHandler.js:37)
	at registerVSCodeCommand (/home/lh/.vscode/extensions/msjsdiag.vscode-react-native-0.9.3/src/extension/rn-extension.js:181)
	at generate.generator.time (/home/lh/.vscode/extensions/msjsdiag.vscode-react-native-0.9.3/src/common/telemetryHelper.js:61)
	at TelemetryGenerator.time (/home/lh/.vscode/extensions/msjsdiag.vscode-react-native-0.9.3/src/common/telemetryGenerators.js:54)
	at Function.generate (/home/lh/.vscode/extensions/msjsdiag.vscode-react-native-0.9.3/src/common/telemetryHelper.js:61)
	at EntryPointHandler.runFunctionWExtProps (/home/lh/.vscode/extensions/msjsdiag.vscode-react-native-0.9.3/src/common/entryPointHandler.js:26)
	at context.subscriptions.push.vscode.commands.registerCommand (/home/lh/.vscode/extensions/msjsdiag.vscode-react-native-0.9.3/src/extension/rn-extension.js:198)
	at d._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:492)
	at d.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:492)
	at d._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:637)
	at d._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:637)
	at d._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:636)
	at d._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:635)
	at define.constructor._protocol.onMessage.e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:633)
	at u.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47)
	at e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:43)
	at u.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47)
	at a (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:175)
	at e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:175)
	at u.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47)
	at y._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:184)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:181)
	at u.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47)
	at f.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:178)
	at define.constructor._register._socket.onData.e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:177)
	at Socket.t (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186)
	at Socket.emit (events.js:182)
	at addChunk (_stream_readable.js:279)
	at readableAddChunk (_stream_readable.js:264)
	at Socket.Readable.push (_stream_readable.js:219)
	at Pipe.onread (net.js:636)
onDidNotificationChange @ workbench.main.js:2365
workbench.main.js:238 [Extension Host] rejected promise not handled within 1 second: Error: spawn react-native ENOENT
t.log @ workbench.main.js:238
workbench.main.js:238 [Extension Host] stack trace: Error: spawn react-native ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
	at onErrorNT (internal/child_process.js:406:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
t.log @ workbench.main.js:238
workbench.main.js:1402   ERR spawn react-native ENOENT: Error: spawn react-native ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
	at onErrorNT (internal/child_process.js:406:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
workbench.main.js:238 [Extension Host] (node:31773) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```

**Comment by pt8o** [comment]
Apologies if this issue is really vague... I'm just not able to launch a React Native project with the VS Code debugger attached. Regular `react-native run-android` works fine.

I've confirmed that the same project works on macOS.

**Comment by ruslan-bikkinin** [comment]
Hi @pt8o and thanks for reaching us. Seems to be you are missing global react-native cli. Do you use nvm?

**Comment by ruslan-bikkinin** [comment]
@pt8o the node version is used inside VS Code my differ with the system one which is known issue for VS Code and nvm, and I am suspecting that this is your case. To check please run `node -v` in system terminal and in VS Code terminal and if node versions are different then simply run `nvm alias default YOUR_SYSTEM_NODE_VERSION`. After that run `npm install -g react-native-cli` on system node and restart VS Code.

**Comment by pt8o** [comment]
`node -v` on both system Terminal and VS Code terminal prints `v11.14.0`

**Comment by ruslan-bikkinin** [comment]
And you still can't debug your app after installing React Native cli globally on 11.14.0?

**Comment by thibmaek** [comment]
It seems that since this extension moved from the "vsmobile.vscode-react-native" to "msjsdiag.vscode-react-native" namespace this is broken.

- Worked fine before, did not upgrade node, react-native-cli or react-native version
- Installing latest react-native-cli does not work.
- Node version: 10
- No nvm (using brew)
- `react-native -v` prints `react-native: 0.57.5` so detects valid project

**Comment by ruslan-bikkinin** [comment]
@thibmaek what version of extension do you use? Do you open exactly the same folder/workspace as before? If you reinstall the extension the problem is still appear?

**Comment by pt8o** [comment]
@ruslan-bikkinin correct, react-native-cli is installed globally. `react-native -v` returns `react-native-cli: 2.0.1` on both OS terminal and VS Code terminal. The same error messages are appearing and the app and debugger do not launch.

**Comment by ruslan-bikkinin** [comment]
@pt8o could you please send a screenshot of file structure of workspace you open in VS Code?

**Comment by pt8o** [comment]
@ruslan-bikkinin just like this?
![Screenshot from 2019-05-23 09-45-00](https://user-images.githubusercontent.com/22176050/58257765-81774600-7d3f-11e9-9ef0-cd22d6a31f9a.png)

**Comment by thibmaek** [comment]
Fix for me:
1. `npm cache clean --force`
2. `npm i -g react-native-cli@latest`
3. Reinstall extension
4. Reload VS Code

**Comment by pt8o** [comment]
@thibmaek thank you for the suggestion, this didn't work for me -- still the same error messages as in the original post

**Comment by thibmaek** [comment]
Yeah mine stopped working again

**Comment by ruslan-bikkinin** [comment]
@thibmaek @pt8o guys, could you please open your project in VS Code, then open VS Code terminal, run `react-native --version` and share output with me?
@pt8o also, could you please share `.vscode/settings.json` content with me?

In general, "Error: spawn react-native ENOENT" signals that `react-native` command is not available from within VS Code process and it's environment problem.

**Comment by pt8o** [comment]
In VS Code terminal
![Screenshot from 2019-05-24 10-16-35](https://user-images.githubusercontent.com/22176050/58334256-2f045b00-7e0d-11e9-915d-74775e4d9068.png)


The full content of `.vscode/settings.json` is
```{
  "editor.insertSpaces": true,
  "editor.tabSize": 2,
  "java.configuration.updateBuildConfiguration": "disabled"
}```

**Comment by ruslan-bikkinin** [comment]
@pt8o looks like everything is okay there. Could you please run `nvm ls` and share the output with me?

**Comment by thibmaek** [comment]
```console
$ react-native --version
react-native-cli: 2.0.1
react-native: 0.57.5
```

```json
{
  "javascript.validate.enable": false,
  "flow.useNPMPackagedFlow": true
}
```

**Comment by pt8o** [comment]
@ruslan-bikkinin 
`nvm ls` gives
```
        v11.0.0
->     v11.14.0
         system
default -> 11 (-> v11.14.0)
node -> stable (-> v11.14.0) (default)
stable -> 11.14 (-> v11.14.0) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/dubnium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.16.0 (-> N/A)
lts/dubnium -> v10.15.3 (-> N/A)
```
on both system and VS Code terminals

**Comment by ruslan-bikkinin** [comment]
@pt8o are you sure that you don't have any other node installations traces in your system except related to nvm? Also, please check [VS Code docs section](https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/integrated-terminal.md#why-is-nvm-complaining-about-a-prefix-option-when-the-integrated-terminal-is-launched). Problem described there may seem to be unrelated, but I am guessing the cause of your issue and @thibmaek is the same as there.

**Comment by pt8o** [comment]
Hi @ruslan-bikkinin, I've fully removed all `node` and `npm` from my `/usr/` folders and then reinstalled everything with `nvm`. Still getting the same error :(

**Comment by thibmaek** [comment]
I don't even use nvm.

**Comment by ruslan-bikkinin** [comment]
@pt8o @thibmaek I added logging of `process.env` before each `react-native` command call. Could you please try it? Please do the following steps: 
* Uninstall extension installed from Market place
* **Restart VS Code**
* Download archive I prepared: [vscode-react-native-0.9.3.vsix.zip](https://github.com/microsoft/vscode-react-native/files/3232679/vscode-react-native-0.9.3.vsix.zip), rename it to vscode-react-native-0.9.3.vsix
* Install VSIX manually (Open VS Code, click Extensions icon, then click on `...` and select `Install From VSIX`)
* Try to debug and get the error.
* Open Developer Tools `Help -> Toggle Developer Tools`
* You will see logged `process.env` object.
* Go through `PATH` value of the object and make sure that it is correct and 
  * @pt8o - you have `/home/username/.nvm/versions/node/v11.14.0/bin` there
  * @pt8o and @thibmaek no other directories listed there could override path to the main node instance (e.g. no other `node` exists in the paths)

**Comment by Unforgiven-wanda** [comment]
Having the same issue and pretty much the same results so far.

**Comment by ruslan-bikkinin** [comment]
@pt8o @thibmaek hi guys, do you have a chance to look at this?

**Comment by pt8o** [comment]
Hi @ruslan-bikkinin , thanks for following up.

I just tried this and I don't see a logged `process.env` object, I don't think?

I get this:
```
workbench.main.js:238 [Extension Host] rejected promise not handled within 1 second: Error: spawn react-native ENOENT
t.log @ workbench.main.js:238
$logExtensionHostMessage @ workbench.main.js:3178
_doInvokeHandler @ workbench.main.js:3252
_invokeHandler @ workbench.main.js:3252
_receiveRequest @ workbench.main.js:3251
_receiveOneMessage @ workbench.main.js:3249
_protocol.onMessage.e @ workbench.main.js:3248
fire @ workbench.main.js:77
a @ workbench.main.js:321
e @ workbench.main.js:321
fire @ workbench.main.js:77
_receiveMessage @ workbench.main.js:330
S._socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:327
fire @ workbench.main.js:77
acceptChunk @ workbench.main.js:323
_register._socket.onData.e @ workbench.main.js:323
t @ workbench.main.js:332
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
workbench.main.js:238 [Extension Host] stack trace: Error: spawn react-native ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
	at onErrorNT (internal/child_process.js:406:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
t.log @ workbench.main.js:238
$logExtensionHostMessage @ workbench.main.js:3178
_doInvokeHandler @ workbench.main.js:3252
_invokeHandler @ workbench.main.js:3252
_receiveRequest @ workbench.main.js:3251
_receiveOneMessage @ workbench.main.js:3249
_protocol.onMessage.e @ workbench.main.js:3248
fire @ workbench.main.js:77
a @ workbench.main.js:321
e @ workbench.main.js:321
fire @ workbench.main.js:77
_receiveMessage @ workbench.main.js:330
S._socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:327
fire @ workbench.main.js:77
acceptChunk @ workbench.main.js:323
_register._socket.onData.e @ workbench.main.js:323
t @ workbench.main.js:332
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
workbench.main.js:1402   ERR spawn react-native ENOENT: Error: spawn react-native ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
	at onErrorNT (internal/child_process.js:406:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
```

With the 'Extension Host" parts expanded:
```
workbench.main.js:238 [Extension Host] rejected promise not handled within 1 second: Error: spawn react-native ENOENT
t.log @ workbench.main.js:238
$logExtensionHostMessage @ workbench.main.js:3178
_doInvokeHandler @ workbench.main.js:3252
_invokeHandler @ workbench.main.js:3252
_receiveRequest @ workbench.main.js:3251
_receiveOneMessage @ workbench.main.js:3249
_protocol.onMessage.e @ workbench.main.js:3248
fire @ workbench.main.js:77
a @ workbench.main.js:321
e @ workbench.main.js:321
fire @ workbench.main.js:77
_receiveMessage @ workbench.main.js:330
S._socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:327
fire @ workbench.main.js:77
acceptChunk @ workbench.main.js:323
_register._socket.onData.e @ workbench.main.js:323
t @ workbench.main.js:332
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
workbench.main.js:238 [Extension Host] stack trace: Error: spawn react-native ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
	at onErrorNT (internal/child_process.js:406:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
t.log @ workbench.main.js:238
$logExtensionHostMessage @ workbench.main.js:3178
_doInvokeHandler @ workbench.main.js:3252
_invokeHandler @ workbench.main.js:3252
_receiveRequest @ workbench.main.js:3251
_receiveOneMessage @ workbench.main.js:3249
_protocol.onMessage.e @ workbench.main.js:3248
fire @ workbench.main.js:77
a @ workbench.main.js:321
e @ workbench.main.js:321
fire @ workbench.main.js:77
_receiveMessage @ workbench.main.js:330
S._socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:327
fire @ workbench.main.js:77
acceptChunk @ workbench.main.js:323
_register._socket.onData.e @ workbench.main.js:323
t @ workbench.main.js:332
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
workbench.main.js:1402   ERR spawn react-native ENOENT: Error: spawn react-native ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
	at onErrorNT (internal/child_process.js:406:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by ruslan-bikkinin** [comment]
@pt8o yes, that was the wrong one. Here is the correct VSIX: [vscode-react-native-0.9.3.vsix.zip](https://github.com/microsoft/vscode-react-native/files/3253010/vscode-react-native-0.9.3.vsix.zip)

I updated my previous comment.

**Comment by thibmaek** [comment]
__Error__: `ERR spawn react-native ENOENT: Error: spawn react-native ENOENT`

---

__PATH__:

- DevTools: `"/usr/bin:/bin:/usr/sbin:/sbin"`
- echo $PATH in VS Code terminal: `/usr/local/opt/node@10/bin:/usr/local/opt/curl/bin:/Users/thibault/bin:/usr/local/sbin:/usr/local/opt/gpg-agent/bin:/usr/local/opt/python/libexec/bin:/Users/thibault/.rbenv/shims:/Users/thibault/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/thibault/Library/Android/sdk/tools:/Users/thibault/Library/Android/sdk/tools/bin:/Users/thibault/Library/Android/sdk/platform-tools:/usr/local/opt/go/libexec/bin:/Applications/Sketch.app/Contents/Resources/sketchtool/bin`

**Comment by ruslan-bikkinin** [comment]
@thibmaek looks like PATH that is passed to VS Code process differs from the one that defined in your system. Under the hood there are two times when env is passed during the debugging:
First time, on VS Code side when spawning extension host process:
https://github.com/microsoft/vscode/blob/e1ac9a2490eff941c56f666800e29987c7276a67/src/vs/workbench/services/extensions/electron-browser/extensionHost.ts#L131
Second time, in the extension when spawning `react-native` process (`env` is undefined, which means that [parent `process.env` will be used](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options)):
https://github.com/microsoft/vscode-react-native/blob/fc602bb6228af5b1dcd734acf8f6b7cb7bb1807a/src/common/commandExecutor.ts#L86
So, this is local configuration problem, not the extension one. It's hard to say why it was working in your case before 0.9.3 release, because a lot of possible changes could had influenced your environment that may affect PATH. i'd suggest you to move `export PATH="/usr/local/opt/node@10/bin:$PATH"` from `.profile` to `.bash_profile` because `.profile` would be the last one for checking by OS and would be ignored if `bash_profile` exists already.

**Comment by ruslan-bikkinin** [comment]
@pt8o did you have a chance to try updated VSIX?

**Comment by ruslan-bikkinin** [comment]
I am closing this due to inactivity. Feel free to re-open if needed.

**Comment by CyberMew** [comment]
I am having this issue too, I have installed the react-native-cli, `react-native -v` gives:

react-native-cli: 2.0.1
react-native: 0.59.8

and `node -v` gives:

v10.15.3

My workspace folder is the react-native project itself (`package.json` is root of this folder).

Following instructions to enable debugging is not working, it just processes for a few seconds and disappears. I have `React Native Tools` v0.10.1 installed. This is my launch.json:

```
{
      "name": "Attach to packager",
      "cwd": "${workspaceFolder}",
      "type": "reactnative",
      "request": "attach",
      "address": "127.0.0.1"
    },
```

We are using `node node_modules/react-native/local-cli/cli.js start` (`npm start`) to start the metro bundler and the server basically.

Debugging remotely (I'm using iOS simulator) basically just launches Chrome tab. (which btw loads localhost:8081 instead of 127.0.0.1:8081 which causes a CORS issue, not sure if it's our config issue or react-native issue).

In frustration, I manage to find and launch `React Native: Start Packager` and I got this same workspace not found 710 error.

However upon installing your debug .vsix file, and restarting the workspace/app, it magically works!

**Comment by ruslan-bikkinin** [comment]
@CyberMew could you please try to use the previous versions of the extension and let us know on which version you have **no error**:
* 0.9.3
* 0.10.0

To install previous version of the extension you need to 
* open extension page in VS Code
* click right mouse button, select "Install Another Version.."
![image](https://user-images.githubusercontent.com/30265843/61283330-a4652a00-a7c5-11e9-9a7d-6e3dfa81b5be.png)
* Then choose needed version in the menu

**Comment by mjgerace** [comment]
I was having the same exact issue as above, installation versions matched in outside terminal and vscode terminal, same debug issue as well. Just rolled back to 10.0.0  and things are working great. Perhaps there was a regression?

**Comment by DananDio** [comment]
any suggestion? i was having the same issue for this, already try with ver 0.9.3 and 0.10.0, can't use tools

**Comment by ruslan-bikkinin** [comment]
@DananDio @mjgerace if you see "Error: spawn react-native ENOENT" in Developer Tools logs it means that `react-native` command is not available in the PATH provided to the VS Code process. It's nothing to do with extension itself.
I'd recommend you to check your system configuration. You can check what is passed into the PATH variable that is used in VS Code by following these steps:

* Open Developer Tools console in VS Code (Help -> Toggle Developer Tools -> Select Console tab)
* Type `process.env.PATH.split(":");` command in the console and call it
* Then you need to check every directory that is listed in the resulted array to find which one contains node or npm executable. If you have multiple such directories then you need to figure out which are excess ones  , why they have been added to the PATH and how to get rid of them.

**Comment by pt8o** [comment]
Sorry for the long delay @ruslan-bikkinin! The issue for me in the end was that that `nvm` paths were in my `bash_profile` but not my `bashrc`... or it may have been the other way around, I don't remember specifically. Apparently the OS terminal loads both, and the regular built in terminal in VS Code loads both, but the specific environment used by the React Native debugger only loads one of them.

**Comment by pheuter** [comment]
I encounter this issue when using the [Visual Studio Code Remote - Containers](https://code.visualstudio.com/docs/remote/containers) extension and installing the vscode-react-native extension inside the container. In the container I have node installed without using nvm.

**Comment by DananDio** [comment]
@ruslan-bikkinin i could provide run npm on vscode terminal and outside vscode , and the only error gor every time i run react-native tools is this :

[Error] Failed to run the application in Android (error code 104)

Stack: Error: Failed to run the application in Android (error code 104): Error while working with workspace: Current workspace does not contain React Native projects. (error code 710)
    at Function.getWrappedError (/Users/danandio/.vscode/extensions/msjsdiag.vscode-react-native-0.10.2/src/common/error/internalError.js:35:16)
    at Function.wrapError (/Users/danandio/.vscode/extensions/msjsdiag.vscode-react-native-0.10.2/src/common/error/errorHelper.js:17:44)
    at handleErrors.resultOfCode.done.reason (/Users/danandio/.vscode/extensions/msjsdiag.vscode-react-native-0.10.2/src/common/entryPointHandler.js:43:72)
    at _rejected (/Users/danandio/.vscode/extensions/msjsdiag.vscode-react-native-0.10.2/node_modules/q/q.js:844:24)
    at /Users/danandio/.vscode/extensions/msjsdiag.vscode-react-native-0.10.2/node_modules/q/q.js:870:30
    at Promise.when (/Users/danandio/.vscode/extensions/msjsdiag.vscode-react-native-0.10.2/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/Users/danandio/.vscode/extensions/msjsdiag.vscode-react-native-0.10.2/node_modules/q/q.js:788:41)
    at /Users/danandio/.vscode/extensions/msjsdiag.vscode-react-native-0.10.2/node_modules/q/q.js:604:44
    at runSingle (/Users/danandio/.vscode/extensions/msjsdiag.vscode-react-native-0.10.2/node_modules/q/q.js:137:13)
    at flush (/Users/danandio/.vscode/extensions/msjsdiag.vscode-react-native-0.10.2/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by ruslan-bikkinin** [comment]
@DananDio please try follow the instructions from my comment: https://github.com/microsoft/vscode-react-native/issues/1012#issuecomment-514615593

**Comment by ruslan-bikkinin** [comment]
@pheuter thanks for letting us know! I think we should triage that.

**Comment by thibmaek** [comment]
I have no clue how to fix this but will list my setup again:

- In my vscode settings: `"terminal.integrated.shell.osx": "/usr/local/bin/zsh",`
- In my .zshrc: `export PATH="/usr/local/opt/node@10/bin:$PATH"`
- When logging path via vscode devtools: `(4) ["/usr/bin", "/bin", "/usr/sbin", "/sbin"]`
- When logging PATH via integrated shell: `/usr/local/opt/node@10/bin:/Users/thibault.maekelbergh/.rbenv/shims:/Users/thibault.maekelbergh/.rbenv/bin:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/usr/local/opt/node@10/bin:/Users/thibault.maekelbergh/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/thibault.maekelbergh/Library/Android/sdk/tools:/Users/thibault.maekelbergh/Library/Android/sdk/tools/bin:/Users/thibault.maekelbergh/Library/Android/sdk/platform-tools:/Applications/Sketch.app/Contents/Resources/sketchtool/bin`
- node installed via brew

**Comment by ruslan-bikkinin** [comment]
@thibmaek as you can see PATH that is being exposed to VS Code differs from the PATH that is being exposed to integrated shell. For some reason PATH export defined in .zshrc isn't engaged by VS Code when it's started. I think, you can try to workaround it by doubling the export in .bash_profile.

**Comment by thibmaek** [comment]
@ruslan-bikkinin putting the export in .bash_profile yields the same result

**Comment by ruslan-bikkinin** [comment]
@thibmaek understood. I'd suggest you to reach out VS Code team then because this is more likely  zsh/VS Code issue than an extension one.

**Comment by afshawnlotfi** [comment]
I am having the same problem. Anyone found a solution or workaround

**Comment by thibmaek** [comment]
I have finally found what causes this issue.
Launching VS Code with `code folder/` in my shell makes the RN extension work 100% of the time (using ZSH).

Launching VS Code from anywhere else (bash, finder, alfred workflow) never works in conjunction with RN extension

**Comment by iosToTop** [comment]
I fixed this by change my wifi to use my phone 4G.
But when i change my wifi to office.The problem also with me.
So i don't know what the question now!!

**Comment by RedMickey** [comment]
Hi @iosToTop, please open a new issue according to [our issue template](https://github.com/microsoft/vscode-react-native/blob/master/.github/ISSUE_TEMPLATE.md) and describe your problem in details?
