### ISSUE TITLE
Starting React packager from VSCode fails

### ISSUE THREAD

**Issue by PiedPieper** [microsoft/vscode-react-native#1044]
## Actual Behavior
Stop packager, followed by start packager fails
## Expected Behavior
It should start. I restarted my computer and all of the sudden it fails every time. But it works with the command line. 

## Software versions
- React-Native VS Code extension version: 0.10.0
- VSCode version: Version 1.36.0
- OS platform and version: Mac 10.14.5
- NodeJS version: v12.1.0
- React Native version: 
react-native-cli: 2.0.1
react-native: 0.60.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```

[Warning] Error: Packager is not running

[Error] Failed to start the React Native packager (error code 106)

Stack: Error: Failed to start the React Native packager (error code 106): Can't get fulfillment value from any promise, all promises were rejected.
	at Function.getWrappedError (/Users/ryanauger/.vscode/extensions/msjsdiag.vscode-react-native-0.10.0/src/common/error/internalError.js:35:16)
	at Function.wrapError (/Users/ryanauger/.vscode/extensions/msjsdiag.vscode-react-native-0.10.0/src/common/error/errorHelper.js:17:44)
	at handleErrors.resultOfCode.done.reason (/Users/ryanauger/.vscode/extensions/msjsdiag.vscode-react-native-0.10.0/src/common/entryPointHandler.js:43:72)
	at _rejected (/Users/ryanauger/.vscode/extensions/msjsdiag.vscode-react-native-0.10.0/node_modules/q/q.js:844:24)
	at /Users/ryanauger/.vscode/extensions/msjsdiag.vscode-react-native-0.10.0/node_modules/q/q.js:870:30
	at Promise.when (/Users/ryanauger/.vscode/extensions/msjsdiag.vscode-react-native-0.10.0/node_modules/q/q.js:1122:31)
	at Promise.promise.promiseDispatch (/Users/ryanauger/.vscode/extensions/msjsdiag.vscode-react-native-0.10.0/node_modules/q/q.js:788:41)
	at /Users/ryanauger/.vscode/extensions/msjsdiag.vscode-react-native-0.10.0/node_modules/q/q.js:604:44
	at runSingle (/Users/ryanauger/.vscode/extensions/msjsdiag.vscode-react-native-0.10.0/node_modules/q/q.js:137:13)
	at flush (/Users/ryanauger/.vscode/extensions/msjsdiag.vscode-react-native-0.10.0/node_modules/q/q.js:125:13)
	at process._tickCallback (internal/process/next_tick.js:61:11)

```

**Comment by animaonline** [comment]
Me2

**Comment by SounD120** [comment]
Hi @PiedPieper , @animaonline and thanks for reaching us. Extension not yet supports React Native 0.60 and we already have an issue to track this: #1042 . We are already working on adding that support and it will be added as a part of the new extension version. I suggest to move our conversation to #1042.

**Comment by patriksharma** [comment]
Failed to start the React Native packager (error code 106)

Since 2 days I'm getting this error in VS. earlier it was working fine. any help 


```
[Info] Starting Packager

[Error] Failed to start the React Native packager (error code 106)

Stack: Error: Failed to start the React Native packager (error code 106): Could not start the packager.
	at Function.getWrappedError (/Users/mwp1/.vscode/extensions/msjsdiag.vscode-react-native-1.2.0/dist/rn-extension.js:1:153599)
	at Function.wrapError (/Users/mwp1/.vscode/extensions/msjsdiag.vscode-react-native-1.2.0/dist/rn-extension.js:1:7359)
	at /Users/mwp1/.vscode/extensions/msjsdiag.vscode-react-native-1.2.0/dist/rn-extension.js:1:205169
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by RedMickey** [comment]
Hi @patriksharma  and thanks for reaching us. Please create a new issue for your specific case and describe your problem using our [issue template](https://github.com/microsoft/vscode-react-native/blob/master/.github/ISSUE_TEMPLATE/1-bug-report.md).
