### ISSUE TITLE
Current workspace does not contain React Native projects

### ISSUE THREAD

**Issue by AndrewMorsillo** [microsoft/vscode-react-native#1102]
This is similar to #1012 but I've confirmed everything posited as a potential solution in that thread. There's something else going on here. The path definitely includes node (v12.10.0), npm (6.10.3), and react-native (cli v2.9.0). Node is installed via nvm and the version on the path is set as default. All settings are default for the vscode-react-native plugin. My project is standard react-native, package.json exists at the root. `react-native run-ios` works fine from the vscode integrated terminal or an external terminal, only the extension fails.

Output of path from developer tools:
```
0: "/Users/imagio/.yarn/bin"
1: "/Users/imagio/.config/yarn/global/node_modules/.bin"
2: "/Users/imagio/dev/oc-cluster-wrapper"
3: "/Users/imagio/dev/tools/Qt5.11.2/5.11.2/clang_64/bin"
4: "/Users/imagio/Library/Android/sdk/platform-tools"
5: "/Users/imagio/.nvm/versions/node/v12.10.0/bin"
6: "/usr/local/bin"
7: "/usr/bin"
8: "/bin"
9: "/usr/sbin"
10: "/sbin"
11: "/Library/Frameworks/Mono.framework/Versions/Current/Commands"
12: "/Applications/Wireshark.app/Contents/MacOS"
```

## Actual Behavior
1. react native project does not run because project is not detected
 

## Expected Behavior
1. running react native project from command palette works
 

## Software versions
- React-Native VS Code extension version: 0.11.0
- VSCode version: 1.38.1
- OS platform and version: macOS 10.14.6
- NodeJS version: 12.10.0
- React Native version: 0.60.5

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
None
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Error] Failed to run the application in iOS (error code 105)

Stack: Error: Failed to run the application in iOS (error code 105): Error while working with workspace: Current workspace does not contain React Native projects. (error code 710)
	at Function.getWrappedError (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/src/common/error/internalError.js:35:16)
	at Function.wrapError (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/src/common/error/errorHelper.js:17:44)
	at handleErrors.resultOfCode.done.reason (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/src/common/entryPointHandler.js:43:72)
	at _rejected (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/node_modules/q/q.js:844:24)
	at /Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/node_modules/q/q.js:870:30
	at Promise.when (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/node_modules/q/q.js:1122:31)
	at Promise.promise.promiseDispatch (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/node_modules/q/q.js:788:41)
	at /Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/node_modules/q/q.js:604:44
	at runSingle (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/node_modules/q/q.js:137:13)
	at flush (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/node_modules/q/q.js:125:13)
	at process._tickCallback (internal/process/next_tick.js:61:11)
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
notificationsAlerts.ts:38 Error: Error while working with workspace: Current workspace does not contain React Native projects. (error code 710)
	at Function.getInternalError (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/src/common/error/errorHelper.js:10)
	at Function.selectProject (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/src/extension/commandPaletteHandler.js:332)
	at Function.runIos (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/src/extension/commandPaletteHandler.js:116)
	at registerVSCodeCommand (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/src/extension/rn-extension.js:189)
	at generate.generator.time (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/src/common/telemetryHelper.js:61)
	at TelemetryGenerator.time (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/src/common/telemetryGenerators.js:54)
	at Function.generate (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/src/common/telemetryHelper.js:61)
	at EntryPointHandler.runFunctionWExtProps (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/src/common/entryPointHandler.js:26)
	at context.subscriptions.push.vscode.commands.registerCommand (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/src/extension/rn-extension.js:209)
	at _executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:518)
	at _.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:518)
	at d._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:623)
	at d._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:623)
	at d._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:621)
	at d._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:620)
	at define.constructor._protocol.onMessage.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:618)
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186)
	at i.constructor.e.onMessage.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:783)
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186)
	at x._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:191)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:188)
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50)
	at f.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:184)
	at define.constructor._register._socket.onData.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:183)
	at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:192)
	at Socket.emit (events.js:182)
	at Socket.EventEmitter.emit (/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/domain.js:442)
	at addChunk (_stream_readable.js:283)
	at readableAddChunk (_stream_readable.js:264)
	at Socket.Readable.push (_stream_readable.js:219)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94)
```

**Comment by RedMickey** [comment]
Hi @AndrewMorsillo and thanks for reaching us.
Could you please run `nvm ls` and send the output to us?
Could you please also add the following line
```
"react-native-tools.logLevel": "Trace"
```
to your `settings.json`, reload VS Code, run your command and share logs with us?
You can use a format described below:
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native: run iOS in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```

**Comment by AndrewMorsillo** [comment]
`nvm ls` output

```
        v8.11.3
        v8.12.0
        v9.11.2
       v10.15.1
        v12.6.0
->     v12.10.0
default -> v12.10.0
node -> stable (-> v12.10.0) (default)
stable -> 12.10 (-> v12.10.0) (default)
iojs -> N/A (default)
lts/* -> lts/dubnium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.16.1 (-> N/A)
lts/dubnium -> v10.16.3 (-> N/A)
```

Command output with logLevel: "Trace"

```
[Debug] Begin to activate...

[Debug] Extension version: 0.11.0

[Debug] Projects found: 1

[Debug] Add project: /Users/imagio/dev/TaskHero

[Debug] React Native version: 

[Debug] react-native@ isn't supported

[Debug] Run command: runIosSimulator

[Error] Failed to run the application in iOS (error code 105)

Stack: Error: Failed to run the application in iOS (error code 105): Error while working with workspace: Current workspace does not contain React Native projects. (error code 710)
	at Function.getWrappedError (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/src/common/error/internalError.js:35:16)
	at Function.wrapError (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/src/common/error/errorHelper.js:17:44)
	at handleErrors.resultOfCode.done.reason (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/src/common/entryPointHandler.js:43:72)
	at _rejected (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/node_modules/q/q.js:844:24)
	at /Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/node_modules/q/q.js:870:30
	at Promise.when (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/node_modules/q/q.js:1122:31)
	at Promise.promise.promiseDispatch (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/node_modules/q/q.js:788:41)
	at /Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/node_modules/q/q.js:604:44
	at runSingle (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/node_modules/q/q.js:137:13)
	at flush (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-0.11.0/node_modules/q/q.js:125:13)
	at process._tickCallback (internal/process/next_tick.js:61:11)
```

package.json

```
{
    "name": "myproject",
    "version": "0.0.1",
    "private": true,
    "scripts": {
        "start": "node node_modules/react-native/local-cli/cli.js start",
        "test": "jest",
        "postinstall": "jetify"
    },
    "dependencies": {
        "@bankify/react-native-animate-number": "^0.2.1",
        "@react-native-community/async-storage": "^1.6.1",
        "@react-native-community/cli": "^2.9.0",
        "@react-native-community/netinfo": "^4.1.4",
        "appcenter": "^2.2.0",
        "appcenter-analytics": "^2.2.0",
        "appcenter-crashes": "^2.2.0",
        "babel-plugin-rewrite-require": "^1.14.5",
        "date-fns": "^1.30.1",
        "deepdash-es": "^4.2.12",
        "global": "^4.4.0",
        "ios-deploy": "^1.9.4",
        "lodash": "^4.17.15",
        "metro-react-native-babel-preset": "^0.56.0",
        "mobx": "^5.13.0",
        "mobx-react": "^6.1.3",
        "mobx-state-tree": "^3.14.1",
        "moment": "^2.24.0",
        "react": "16.9.0",
        "react-native": "^0.60.5",
        "react-native-animatable": "^1.3.2",
        "react-native-cli": "^2.0.1",
        "react-native-code-push": "^5.6.1",
        "react-native-confetti": "^0.1.0",
        "react-native-countup": "^0.0.2",
        "react-native-draggable-flatlist": "^1.1.7",
        "react-native-easy-toast": "^1.2.0",
        "react-native-exception-handler": "^2.10.8",
        "react-native-fbsdk": "^1.0.1",
        "react-native-firebase": "^5.5.6",
        "react-native-gesture-handler": "^1.2.1",
        "react-native-google-signin": "^2.0.0",
        "react-native-os": "^1.2.2",
        "react-native-particles": "^0.0.7",
        "react-native-popover-view": "^2.0.5",
        "react-native-pose": "^0.9.1",
        "react-native-restart": "^0.0.12",
        "react-native-shimmer": "^0.5.0",
        "react-native-sortable-listview": "^0.2.9",
        "react-native-sound": "^0.11.0",
        "react-native-svg": "^9.6.2",
        "react-native-threads": "^0.0.16",
        "react-native-twitter-signin": "^1.1.1",
        "react-native-vector-icons": "^6.4.2",
        "react-navigation": "^3.11.1",
        "rn-sprite-sheet": "^1.1.3",
        "smartlook-react-native-wrapper": "^0.13.0",
        "styled-components": "^4.2.0",
        "tinycolor2": "^1.4.1",
        "unlink": "^0.0.2"
    },
    "devDependencies": {
        "@babel/core": "^7.5.5",
        "@babel/plugin-proposal-decorators": "^7.4.4",
        "@babel/runtime": "^7.5.5",
        "@types/jest": "^24.0.17",
        "@types/lodash": "^4.14.136",
        "@types/moment": "^2.13.0",
        "@types/react": "^16.9.1",
        "@types/react-native": "^0.60.5",
        "@types/react-native-fbsdk": "^0.7.0",
        "@types/react-native-google-signin": "^1.0.2",
        "@types/react-native-restart": "^0.0.0",
        "@types/react-native-vector-icons": "^6.4.0",
        "@types/react-navigation": "^3.0.8",
        "@types/react-test-renderer": "^16.9.0",
        "@types/styled-components": "^4.1.19",
        "@types/tinycolor2": "^1.4.1",
        "babel-jest": "^24.7.1",
        "jest": "^24.7.1",
        "prettier": "^1.18.2",
        "react-test-renderer": "16.9.0",
        "typescript": "^3.6.3"
    },
    "jest": {
        "preset": "react-native"
    },
    "rnpm": {
        "assets": [
            "./assets/fonts"
        ]
    },
    "react-native": {
        "os": "react-native-os"
    }
}

```

**Comment by RedMickey** [comment]
Hi @AndrewMorsillo. Your `package.json` file shows that you have react-native-cli installed locally, but extension requires to have react-native-cli to be installed globally, so I'd recommend to uninstall local package, global CLI packages and reinstall it globally. You can use the following commands:
```
npm uninstall react-native-cli
npm uninstall @react-native-community/cli
npm uninstall -g @react-native-community/cli
npm install -g react-native-cli
```
Could you please also run the following command and send us the output after `react-native-cli` reinstallation?
```
which react-native
```
Could you please try these recommendations and let us know if they were useful?

**Comment by AndrewMorsillo** [comment]
I did already have it installed globally. Prior to reinstalling, `which react-native` return:

```
/Users/imagio/.config/yarn/global/node_modules/.bin/react-native
```

After reinstalling (I tried a global install with both npm and yarn and they both work fine)

```
/Users/imagio/.config/yarn/global/node_modules/.bin/react-native
```

I'm not sure what the original issue was since you can see it was always accessible on the same path.

I'm curious as to why this extension requires the global deprecated package `react-native-cli`. The documentation for `@react-native-community/cli` states:

```
Using global CLI (legacy)

You'll need to install a global module react-native-cli and follow instructions there.

We strongly encourage you to only use global react-native-cli for bootstrapping new projects. Use local version for everything else.

```

and

```
react-native-cli – an optional global convenience package, which is a proxy to @react-native-community/cli and global installation helper. Please consider it legacy, because it's not necessary anymore.
```

I believe at some point it also prints out a console warning saying that react-native-cli is deprecated. I think more and more people are going to start running into this problem since the react-native documentation specifically advises to do things in a way that doesn't work with this extension.

**Comment by RedMickey** [comment]
@AndrewMorsillo Glad to hear that your issue is resolved.
With respect to the `react-native-cli` deprecation, we are reworking our approach to work with local React Native CLI now. You can track the progress in that [issue](https://github.com/microsoft/vscode-react-native/issues/1101). Please let us know if you have any questions.
