### ISSUE TITLE
Version 0.13 breaks running packager from VS Code from different folder

### ISSUE THREAD

**Issue by gregersn** [microsoft/vscode-react-native#1159]
## Actual Behavior
1. Open workspace with folder configured to other than current directory
2. Choose Start Packager
3. `[Error] Failed to start the React Native packager (error code 106)`

## Expected Behavior
1. Packager to run

## Software versions
- React-Native VS Code extension version: 0.13
- VSCode version: 1.39.2
- OS platform and version: Ubuntu 19.10
- NodeJS version: 12.13.0
- React Native version: 0.60

```
Stack: Error: Failed to start the React Native packager (error code 106): Couldn't find react-native package in node_modules. Please, run "npm install" inside your project to install it. (error code 606)
	at Function.getWrappedError (/home/greger/.vscode/extensions/msjsdiag.vscode-react-native-0.13.0/src/common/error/internalError.js:35:16)
	at Function.wrapError (/home/greger/.vscode/extensions/msjsdiag.vscode-react-native-0.13.0/src/common/error/errorHelper.js:17:44)
	at resultOfCode.done.reason (/home/greger/.vscode/extensions/msjsdiag.vscode-react-native-0.13.0/src/common/entryPointHandler.js:43:72)
	at _rejected (/home/greger/.vscode/extensions/msjsdiag.vscode-react-native-0.13.0/node_modules/q/q.js:844:24)
	at /home/greger/.vscode/extensions/msjsdiag.vscode-react-native-0.13.0/node_modules/q/q.js:870:30
	at Promise.when (/home/greger/.vscode/extensions/msjsdiag.vscode-react-native-0.13.0/node_modules/q/q.js:1122:31)
	at Promise.promise.promiseDispatch (/home/greger/.vscode/extensions/msjsdiag.vscode-react-native-0.13.0/node_modules/q/q.js:788:41)
	at /home/greger/.vscode/extensions/msjsdiag.vscode-react-native-0.13.0/node_modules/q/q.js:604:44
	at runSingle (/home/greger/.vscode/extensions/msjsdiag.vscode-react-native-0.13.0/node_modules/q/q.js:137:13)
	at flush (/home/greger/.vscode/extensions/msjsdiag.vscode-react-native-0.13.0/node_modules/q/q.js:125:13)
	at process._tickCallback (internal/process/next_tick.js:61:11)

```

Downgrading to 0.12.1 works.

**Comment by RedMickey** [comment]
Hi @gregersn and thanks for reaching us. I was able to reproduce that behavior. The fix will be released in the new extension version.

**Comment by RedMickey** [comment]
Hi @gregersn, the fix has been merged to master branch. It will be available in the next extension version, so I'm closing this issue. Feel free to open new ones if needed.

**Comment by RedMickey** [comment]
Hi @gregersn, the new version [0.13.1](https://github.com/microsoft/vscode-react-native/releases/tag/0.13.1) of React Native Tools extension has been released, please try it out and let us know if you face any problems.
