### ISSUE TITLE
Unexpected concatenation of Sdk path with platform tools path happening while debugging , project running fine but the issue is getting while debugging.

### ISSUE THREAD

**Issue by RichardsonVJohnson** [microsoft/vscode-react-native#1203]
Problem : 
Unexpected concatenation of Sdk path with platform tools path happening while debugging , 
project running fine but the issue is getting while debugging.

Notes
1. Sdk and platform tools already set, which is present at Env. Variables 

## Software versions
-React-Native VS Code extension version:
-VSCode version: 1.31
-OS platform and version: Windows 10
-NodeJS version: 13
-React Native version: 16.9.0

Output [run-android]
-------------------------------
BUILD SUCCESSFUL in 2m 54s
543 actionable tasks: 535 executed, 8 up-to-date
info Connecting to the development server...
warn Failed to connect to development server using "adb reverse": spawnSync  C:\Users\Login\AppData\Local\Android\Sdk/platform-tools/adb ENOENT
info Starting the app on "388aa8b77d2b"...

Debug Console
-------------------------------
Could not debug. Unknown error: not all success patterns were matched. 
 It means that "react-native run-android" command failed. 
 Please, check the View -> Toggle Output -> React Native, 
 View -> Toggle Output -> React Native: Run android output windows. (error code 712)

**Comment by SounD120** [comment]
@RichardsonVJohnson Could you please check if you have `local.properties` file in your `android` folder in the project root? If it exists, could you please send us its content?

**Comment by RichardsonVJohnson** [comment]
@SounD120  sure here it is,

## This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
#Thu Feb 06 11:43:19 IST 2020
ndk.dir=C\:\\Users\\Login\\AppData\\Local\\Android\\Sdk\\ndk-bundle
sdk.dir=C\:\\Users\\Login\\AppData\\Local\\Android\\Sdk

**Comment by SounD120** [comment]
@RichardsonVJohnson Could you please try to remove this file from there or move it from that directory and try to run debugging? Also, could you please try to create fresh React Native project and let us know how debugging work with it?

**Comment by RichardsonVJohnson** [comment]
@SounD120 ok, let me do it

**Comment by RichardsonVJohnson** [comment]
now am facing anohter issue while creating new RN app

error Error: Cannot find module 'C:\Users\Login\AppData\Local\Temp\rncli-init-template-EcLdHk\node_modules\react-native\template.config'

Steps to reproduce:
---------------------------
npx react-native init myapp
also i tried 
npm i -g react-native-cli
react-native init myapp

Console Log
-----------------------------------------------------------
√ Downloading template
× Copying template
error Error: Cannot find module 'C:\Users\Login\AppData\Local\Temp\rncli-init-template-EcLdHk\node_modules\react-native\template.config'
Require stack:
- C:\Users\Login\AppData\Local\Yarn\Data\global\node_modules\@react-native-community\cli\build\commands\init\template.js
- C:\Users\Login\AppData\Local\Yarn\Data\global\node_modules\@react-native-community\cli\build\commands\init\init.js
- C:\Users\Login\AppData\Local\Yarn\Data\global\node_modules\@react-native-community\cli\build\commands\init\index.js
- C:\Users\Login\AppData\Local\Yarn\Data\global\node_modules\@react-native-community\cli\build\commands\index.js
- C:\Users\Login\AppData\Local\Yarn\Data\global\node_modules\@react-native-community\cli\build\cliEntry.js
- C:\Users\Login\AppData\Local\Yarn\Data\global\node_modules\@react-native-community\cli\build\index.js
- C:\Users\Login\AppData\Local\Yarn\Data\global\node_modules\@react-native-community\cli\build\bin.js
error EBUSY: resource busy or locked, rmdir 'D:\RD\sapprn'. Run CLI with --verbose flag for more details.
Error: EBUSY: resource busy or locked, rmdir 'D:\RD\sapprn'
    at Object.rmdirSync (fs.js:785:3)
    at rmdirSync (C:\Users\Login\AppData\Local\Yarn\Data\global\node_modules\fs-extra\lib\remove\rimraf.js:276:13)
    at Object.rimrafSync [as removeSync] (C:\Users\Login\AppData\Local\Yarn\Data\global\node_modules\fs-extra\lib\remove\rimraf.js:252:7)
    at Object.initialize [as func] (C:\Users\Login\AppData\Local\Yarn\Data\global\node_modules\@react-native-community\cli\build\commands\init\init.js:292:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

D:\RD>

**Comment by RichardsonVJohnson** [comment]
still its not working !

**Comment by RichardsonVJohnson** [comment]
Console log 
--------------------
warn Failed to connect to development server using "adb reverse": spawnSync  C:\Users\Login\AppData\Local\Android\Sdk/platform-tools/adb ENOENT

**Comment by SounD120** [comment]
@RichardsonVJohnson I tried to reproduce this behavior, but in my case it doesn't reproduce . If `local.properties` file exists the extension uses Android `sdk.dir` from there, not from PATH environment variable. The path to the adb executable is processed [this way](https://github.com/microsoft/vscode-react-native/blob/master/src/extension/android/adb.ts#L60) on the extension side.

Anyway if the path to the Android SDK in `sdk.dir` field of `projectRoot/android/local.properties` file was configured correctly it worked without any problems. Here is my `React Native: Run Android` logs for case when `local.properties` file is exists:
```
[Warning] Target simulator is not supported for Android platform. 
 If you want to use particular device or simulator for launching Android app,
 please specify  device id (as in 'adb devices' output) instead.

[Info] Using Android SDK location defined in android/local.properties file: C:\Android\android-sdk.

[Info] Starting React Native Packager.

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 864 file(s) to forward-jetify. Using 8 workers...
info Installing the app...
> Task :app:generatePackageList
> Task :app:preBuild
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:bundleDebugJsAndAssets SKIPPED
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateDebugSources UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:mainApkListPersistenceDebug UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :app:compileDebugJavaWithJavac UP-TO-DATE
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders UP-TO-DATE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:copyDebugBundledJs SKIPPED
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:signingConfigWriterDebug UP-TO-DATE
> Task :app:checkDebugDuplicateClasses UP-TO-DATE
> Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug UP-TO-DATE
> Task :app:transformDexArchiveWithDexMergerForDebug UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :app:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
> Task :app:packageDebug UP-TO-DATE

> Task :app:installDebug
11:33:16 V/ddms: execute: running am get-config
11:33:17 V/ddms: execute 'am get-config' on 'emulator-5554' : EOF hit. Read: -1
11:33:17 V/ddms: execute: returning
Installing APK 'app-debug.apk' on 'test(AVD) - 9' for app:debug
11:33:17 D/app-debug.apk: Uploading app-debug.apk onto device 'emulator-5554'
11:33:17 D/Device: Uploading file onto device 'emulator-5554'
11:33:17 D/ddms: Reading file permision of C:\Work\rn615\android\app\build\outputs\apk\debug\app-debug.apk as: rwx------
11:33:17 V/ddms: execute: running pm install -r -t "/data/local/tmp/app-debug.apk"
11:33:19 V/ddms: execute 'pm install -r -t "/data/local/tmp/app-debug.apk"' on 'emulator-5554' : EOF hit. Read: -1
11:33:19 V/ddms: execute: returning
11:33:19 V/ddms: execute: running rm "/data/local/tmp/app-debug.apk"
11:33:19 V/ddms: execute 'rm "/data/local/tmp/app-debug.apk"' on 'emulator-5554' : EOF hit. Read: -1
11:33:19 V/ddms: execute: returning
Installed on 1 device.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 8s
27 actionable tasks: 2 executed, 25 up-to-date
info Connecting to the development server...
info Starting the app on "emulator-5554"...
Starting: Intent { cmp=com.rn615/.MainActivity }
```
Have you tried debugging in the application you just created?
Could you please send us full `React Native: Run android` logs for a case of debugging new app and your current app? If these logs could content any sensitive data you can send these logs to my working email: v-yuskor@microsoft.com

**Comment by SounD120** [comment]
@RichardsonVJohnson Do you have a chance to look at this?

**Comment by SounD120** [comment]
@RichardsonVJohnson I am closing this due to inactivity. Please feel free to reopen if needed.
