### ISSUE TITLE
skipping node_internals not working when debugging via attach

### ISSUE THREAD

**Issue by craigphicks** [microsoft/vscode-react-native#1346]
# skipping node_internals not working when debugging via attach

>Please put here any steps, code or any information that can help us reproduce the error on our side so we can fix it:

0. set up launch json with attach process option:
```
    {
      "type": "node",
      "request": "attach",
      "name": "Attach by Process ID",
      "processId": "${command:PickProcess}",
      "skipFiles": [
        "<node_internals>/**"
      ]
    },
```
1. select both 'caught exceptions' 
2. attach a running `node` process; it will automatically stop at main module top (good).
3. do continue
4. it stops on internals exception, e.g.,
```
Exception has occurred: Error: No such module: pipe_wrap
  at internalBinding (internal/bootstrap/loaders.js:104:17)
 ```

## Expected behavior

> What were you expecting to happen?

Would not stop at internal exception.  (Works well when NOT starting via attach).

## Debug output

```
Exception has occurred: Error: No such module: pipe_wrap
  at internalBinding (internal/bootstrap/loaders.js:104:17)
 ```

## Environment

> Please tell us about your system and your project:
```
$ node  --version
v10.16.3
```
```
$ code --version
1.47.0
d5e9aa0227e057a60c82568bf31c04730dc15dcd
x64
```

**Comment by craigphicks** [comment]
I'm moving this to 

https://github.com/microsoft/vscode/issues/102412
