### ISSUE TITLE
React Native Hermes (Preview) doesn't work for Brownfield app 

### ISSUE THREAD

**Issue by SounD120** [microsoft/vscode-react-native#1365]
Hi @SounD120 I didn't had enough time to start digging on this. I tried to use it on the release data (Jun 3) but it was not working for me. Now that I'm free again I started looking again into the preview extension but it still not working. I'm able to attach the debug to the packager but my app never get loaded (JavaScript does not geto loaded when debugging with this version)
I'm currently using react 0.61 with Hermes and my app is a brownfield app (android native activities + react native screens).
Is there any guidance and minimum requirements for the the new debug system?

_Originally posted by @gfrancischini in https://github.com/microsoft/vscode-react-native/issues/1209#issuecomment-667711886_

**Comment by SounD120** [comment]
Hi @gfrancischini . I created a new issue based on your description. Could you please add a description of your problem in accordance with our [bug report template](https://github.com/microsoft/vscode-react-native/blob/master/.github/ISSUE_TEMPLATE/1-bug-report.md)? That can help us a lot.

**Comment by gfrancischini** [comment]
# 🐛 What is the bug? How can we reproduce it?

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:

1. Open a React Native Project on Visual Studio Code
2. Run npm run start (react native start) or using the cmd pallette run React Native : Start Packager
3. On the debug tab start the Attach to Packager with the following configuration

```
"configurations": [
        {
            "name": "Attach to packager",
            "cwd": "${workspaceFolder}",
            "type": "reactnative-preview",
            "request": "attach",
            "skipFiles": [
                "<node_internals>/**/*.js"
            ]
        }
    ]
```

## Expected behavior

What were you expecting to happen?
I'm expecting that my app starts, the javascript code should get loaded and stop on the first file, but the app seems not being able to start loading the scripts.
PS: It works just fine with the current version 0.16 and 0.17
**Also its working now using preview v2020.7.2321**

## Debug output

<details>
<summary>Debug Console</summary>

```text

PASTE OUTPUT OF DEBUG CONSOLE (View -> Toggle Debug Console)
Attaching to the application
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
```
</details>

<details>
<summary>React Native output channel</summary>
[Info] Starting Packager

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   c:\TFS.WORK\SWProjects\RBDC\Source Code\DevBranches\Merge7.80-RN_v3\Mobile\MobileApps\ReactApp 

Loading dependency graph, done.
[Info] Packager started.

info Starting custom debugger by executing:, echo A debugger is not needed:  "c:\TFS.WORK\SWProjects\RBDC\Source Code\DevBranches\Merge7.80-RN_v3\Mobile\MobileApps\ReactApp"

 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (2256/2256), done.

 MAP  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

```text

PASTE OUTPUT OF REACT-NATIVE OUTPUT CHANNEL (View -> Toggle Output -> Select React-Native in ListBox)

```
</details>


<details>
<summary>Developer Tools console</summary>

```text

PASTE OUTPUT OF DEVELOPER TOOLS CONSOLE (Help -> Toggle Developer Tools -> Select Console tab)
 ERR loadedSources not supported: Error: loadedSources not supported
    at t.RawDebugSession.loadedSources (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3169:387)
    at N.getLoadedSources (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6610:965)
    at s (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6558:479)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6559:743
    at Array.forEach (<anonymous>)
    at W.renderBody (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6559:732)
    at W.render (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1070:335)
    at W.render (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6387:305)
    at M.onDidAddViewDescriptors (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6407:65)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6402:142
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at b.onDidChangeContext (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5795:986)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5789:480
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:91:482
    at t.PauseableEmitter.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at t.PauseableEmitter.resume (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:96:349)
    at _.bufferChangeEvents (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1849:989)
    at t.ViewModel.setFocus (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3175:69)
    at G.focusStackFrame (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6635:343)
    at G.launchOrAttachToSession (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6630:514)
    at async G.doCreateSession (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6629:234)
    at async G.startDebugging (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6626:677)
```
</details>


## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
PASTE OUTPUT OF `npx react-native doctor` or `npx expo doctor`
```

* `envinfo`:

```text
System:
    OS: Windows 10 10.0.17134
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 823.68 MB / 7.86 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: 4.9.4 - C:\watchman\watchman.EXE
  Managers:
    pip2: 19.2.3 - C:\Python27\Scripts\pip2.EXE
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    VSCode: 1.47.3 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  Languages:
    PHP: 7.4.1 - C:\Program Files\PHP\v7.4\php.EXE
    Python: 2.7.17 - C:\Python27\python.EXE
  Databases:
    SQLite: 3.28.0 - C:\Users\gfrancischini\AppData\Local\Android\Sdk\platform-tools\sqlite3.EXE
  Browsers:
    Edge: 42.17134.1098.0
    Internet Explorer: 11.0.17134.1
```

* React Native Tools extension version: 3.2.1

**Comment by SounD120** [comment]
@gfrancischini For debugging Hermes there is the `Attach to Hermes application - Experimental` debug scenario which uses `reactnativedirect-preview` debug type. If `Attach to Packager` works for you - it might be that Hermes is disabled for your app and standard React Native debugging approach is used.
With respect to async functions debugging - I think you better to reach out to the [`vscode-js-debug`](https://github.com/microsoft/vscode-js-debug) extension which is the debugging core for this extension. If the case you described will be fixed in there - you'll receive the fix by the VS Code updates.
Please let me know if you have any questions.

**Comment by RedMickey** [comment]
@gfrancischini, I tried to debug a brownfield app with React Native v0.60.5, I could successfully attach to it using the `Attach to Packager` scenario. With respect to Hermes apps debugging, we’d recommend to update React Native package to the last one(e.g. 0.63.2), since old versions of Hermes engine could not support some of the Chrome API methods. This could lead to some debugging issues. Newer versions of React Native are using more recent Hermes engine.

**Comment by SounD120** [comment]
@gfrancischini Is this issue still relevant for you?

**Comment by SounD120** [comment]
@gfrancischini I'm closing this issue due to inactivity.
