### ISSUE TITLE
[Bug] Error while monitoring LogCat

### ISSUE THREAD

**Issue by tosbaha** [microsoft/vscode-react-native#1366]
# 🐛 What is the bug? How can we reproduce it?

Recently, I can't see the logcat output when I start my app with the extension. When I do `adb logcat` logs can be seen.

1. Run the app with "Run Android on Emulator"

## Expected behavior

I want to see logs on Output/LogCat section

## Debug output

<details>
<summary>Debug Console</summary>

```text

Empty

```
</details>

<details>
<summary>React Native output channel</summary>

```text

[Info] Starting Packager

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   /Users/mustafa/Desktop/Project 

[Info] Packager started.

Loading dependency graph, done.
 DELTA  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1376/1376), done.

// Run Android Part
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 3s
228 actionable tasks: 4 executed, 224 up-to-date
info Running /Users/mustafa/Library/Android/sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
info Starting the app on emulator-5554 (/Users/mustafa/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -n com.findmyparcels/com.findmyparcels.MainActivity)...
Starting: Intent { cmp=com.findmyparcels/.MainActivity }
[Warning] Error while monitoring LogCat

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

[Extension Host] [vscode-icons] v10.2.0 activated!
2console.ts:137 [Extension Host] (node:973) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ console.ts:137
log.ts:197   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
error Unrecognized command "doctor".
```

* `envinfo`:

```text
 System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz
    Memory: 8.12 GB / 24.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Utilities:
    CMake: 3.15.4 - /usr/local/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.24.3 - /usr/bin/git
  Servers:
    Apache: 2.4.41 - /usr/sbin/apachectl
  Virtualization:
    Docker: 19.03.8 - /usr/local/bin/docker
    VirtualBox: 5.2.30 - /usr/local/bin/vboxmanage
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.47.3 - /usr/local/bin/code
    Vim: 8.1 - /usr/bin/vim
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 11.0.2 - /usr/bin/javac
    Perl: 5.30.0 - /usr/local/bin/perl
    PHP: 7.3.11 - /usr/bin/php
    Python: 2.7.16 - /usr/local/bin/python
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    SQLite: 3.28.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 79.0
    Safari: 13.1.1
```

* React Native Tools extension version: 0.59.10
* Expo SDK version (if applicable): VERSION

**Comment by RedMickey** [comment]
Hi @tosbaha and thanks for reaching us. We tried to reproduce this problem on a plain React Native v0.59.10 app and LogCat logs were printed properly.
Could you please try to create a plain React Native v0.59.10 app and check whether LogCat logs work there?
To create a new React Native project version lower than 0.60.0 you need to install the `react-native-cli` package globally.
- Run `npm i react-native-cli -g`
- Create a new project `react-native init AwesomeProject05910 --version 0.59.10`
- Run the `Run Android on Emulator` command

Could you please also set the extension log level on `Trace` and send us outputs from `React Native`, `React Native: Run android` and `LogCat` channels for the plain project and the project in this issue ?
You can change the extension log level by adding the `settings.json` file to the `.vscode` folder with the following content:
```
{
    "react-native-tools.logLevel": "Trace"
}
```

Please, let us know about your results.

**Comment by tosbaha** [comment]
- Installed react-native-cli again
```
➜ npm i react-native-cli -g
/Users/mustafa/.nvm/versions/node/v12.14.0/bin/react-native -> /Users/mustafa/.nvm/versions/node/v12.14.0/lib/node_modules/react-native-cli/index.js
+ react-native-cli@2.0.1
updated 1 package in 1.732s
```
- Created new Project

I don't know why but can't create new project with 0.59.10 now.
Probably NPM issue https://status.npmjs.org/incidents/cksjqc1w11v5 I am so lucky lol

```
➜ react-native init AwesomeProject05910 --version 0.59.10
This will walk you through creating a new React Native project in /Users/mustafa/Desktop/AwesomeProject05910
Using yarn v1.22.4
Installing react-native@0.59.10...
yarn add v1.22.4
info No lockfile found.
[1/4] 🔍  Resolving packages...
error Couldn't find package "@react-native-community/cli@^1.2.1" required by "react-native@0.59.10" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
warning react-native > fbjs > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native > create-react-class > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native > fbjs-scripts > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native > metro-babel-register > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
Error: Command failed: yarn add react-native@0.59.10 --exact
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at run (/usr/local/lib/node_modules/react-native-cli/index.js:294:5)
    at createProject (/usr/local/lib/node_modules/react-native-cli/index.js:249:3)
    at init (/usr/local/lib/node_modules/react-native-cli/index.js:200:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:153:7)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 3912,
  stdout: null,
  stderr: null
}
Command `yarn add react-native@0.59.10 --exact` failed.
```

- Run Android (Old Project) with trace level log

React Native run android

```
BUILD SUCCESSFUL in 4s
228 actionable tasks: 4 executed, 224 up-to-date
info Running /Users/mustafa/Library/Android/sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
info Starting the app on emulator-5554 (/Users/mustafa/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -n com.findmyparcels/com.findmyparcels.MainActivity)...
Starting: Intent { cmp=com.findmyparcels/.MainActivity }
[Debug] Finished executing: /Users/mustafa/Desktop/FindMyParcels/node_modules/.bin/react-native run-android --no-packager

[Warning] Error while monitoring LogCat
```

Logcat

```
[Debug] Monitoring LogCat for device emulator-5554 with arguments: *:S,ReactNative:V,ReactNativeJS:V
```

**Comment by tosbaha** [comment]
I found the culprit. The only difference between fresh project and mine is, mine has `local.properties` file.

If the project has `local.properties` file and it has below content
```
## This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
#Tue Jul 02 00:08:24 EET 2019
sdk.dir=/Users/mustafa/Library/Android/sdk
```

LogCat doesn't work. However if I comment out `sdk.dir` part It goes like below

```
[Info] No sdk.dir value found in local.properties file. Using Android SDK location from PATH.

[Info] Starting React Native Packager.
```

My `PATH` is below

```
/Users/mustafa/.fastlane/bin:/Users/mustafa/.nvm/versions/node/v12.14.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/mustafa/Library/Android/sdk/emulator:/Users/mustafa/Library/Android/sdk/tools:/Users/mustafa/Library/Android/sdk/tools/bin:/Users/mustafa/Library/Android/sdk/platform-tools:/Users/mustafa/.rvm/bin
```

As I noted in my original issue, LogCat works if I do `adb logcat` so it is definitely related to the extension.
