### ISSUE TITLE
[Bug] Could not find AppLauncher by the project root path <path>

### ISSUE THREAD

**Issue by VPelt** [microsoft/vscode-react-native#1432]
# 🐛 What is the bug? How can we reproduce it?

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:

1. Step 1 Start vscode 'fresh'
2. Step 2 Start an emulator from terminal in vscode
3. Step 3 Start the debugger by pressing F5

## Expected behavior

Launch the app in debug mode

## Debug output

<details>
<summary>Debug Console</summary>

```text

Debug console is empty

```
</details>

<details>
<summary>React Native output channel</summary>

```text

[Error] Failed to setup the stub launcher for the debugger (error code 703)

Stack: Error: Failed to setup the stub launcher for the debugger (error code 703): EEXIST: file already exists, mkdir 'c:\Git\PROJECT\.vscode\.react'
    at Function.getWrappedError (c:\Users\USER\.vscode\extensions\msjsdiag.vscode-react-native-preview-2020.9.1721\dist\rn-extension.js:1:151080)
    at Function.wrapError (c:\Users\USER\.vscode\extensions\msjsdiag.vscode-react-native-preview-2020.9.1721\dist\rn-extension.js:1:7038)
    at c:\Users\USER\.vscode\extensions\msjsdiag.vscode-react-native-preview-2020.9.1721\dist\rn-extension.js:1:200598
[Error] Failed to activate the React Native Tools extension (error code 702)

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

  ERR Cannot read property 'getRnCdpProxy' of undefined: TypeError: Cannot read property 'getRnCdpProxy' of undefined
    at E.<anonymous> (c:\Users\USER\.vscode\extensions\msjsdiag.vscode-react-native-preview-2020.9.1721\dist\rn-extension.js:1:115975)
    at Generator.next (<anonymous>)
    at c:\Users\USER\.vscode\extensions\msjsdiag.vscode-react-native-preview-2020.9.1721\dist\rn-extension.js:1:113705
    at new Promise (<anonymous>)
    at n (c:\Users\USER\.vscode\extensions\msjsdiag.vscode-react-native-preview-2020.9.1721\dist\rn-extension.js:1:113450)
    at E.disconnectRequest (c:\Users\USER\.vscode\extensions\msjsdiag.vscode-react-native-preview-2020.9.1721\dist\rn-extension.js:1:115915)
    at E.<anonymous> (c:\Users\USER\.vscode\extensions\msjsdiag.vscode-react-native-preview-2020.9.1721\dist\rn-extension.js:1:389980)
    at Generator.next (<anonymous>)
    at c:\Users\USER\.vscode\extensions\msjsdiag.vscode-react-native-preview-2020.9.1721\dist\rn-extension.js:1:386112
    at new Promise (<anonymous>)
    at n (c:\Users\USER\.vscode\extensions\msjsdiag.vscode-react-native-preview-2020.9.1721\dist\rn-extension.js:1:385857)
    at E.disconnectRequest (c:\Users\USER\.vscode\extensions\msjsdiag.vscode-react-native-preview-2020.9.1721\dist\rn-extension.js:1:389794)
    at E.dispatchRequest (c:\Users\USER\.vscode\extensions\msjsdiag.vscode-react-native-preview-2020.9.1721\dist\rn-extension.js:1:122206)
    at E.dispatchRequest (c:\Users\USER\.vscode\extensions\msjsdiag.vscode-react-native-preview-2020.9.1721\dist\rn-extension.js:1:361991)
    at E.handleMessage (c:\Users\USER\.vscode\extensions\msjsdiag.vscode-react-native-preview-2020.9.1721\dist\rn-extension.js:1:358859)
    at E._handleData (c:\Users\USER\.vscode\extensions\msjsdiag.vscode-react-native-preview-2020.9.1721\dist\rn-extension.js:1:360581)
    at Socket.<anonymous> (c:\Users\USER\.vscode\extensions\msjsdiag.vscode-react-native-preview-2020.9.1721\dist\rn-extension.js:1:359191)
    at Socket.emit (events.js:223:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
PASTE OUTPUT OF `npx react-native doctor` or `npx expo doctor`
```

* `envinfo`:

```text
PASTE OUTPUT OF `npx envinfo`
```

* React Native Tools extension version: v2020.9.1721 (preview)

**Comment by SounD120** [comment]
Hi @VPelt . The React Native Preview version is not yet tuned to receive updates after the React Native Tools v1.0.0 stable release. For now stable version has the most recent updates and this problem has been already fixed in v1.0.1 version, so I'd recommend to remove the preview one and try the latest stable version of the extension.

**Comment by VPelt** [comment]
Switching between type: reactnative-preview and type: reactnative does seem to 'fix' the issue.
However with a full computer reboot. fresh restart of vscode it does retrigger this

**Comment by SounD120** [comment]
@VPelt I recommend you to disable or remove React Native Tools Preview version, and try to reboot VS Code and run debugging again. Let me know if this issue persists after that.

**Comment by VPelt** [comment]
I disabled the preview version, however i still got this issue this morning on 1.0.1

**Comment by VPelt** [comment]
[Error] Failed to setup the stub launcher for the debugger (error code 703)

Stack: Error: Failed to setup the stub launcher for the debugger (error code 703): EEXIST: file already exists, mkdir 'c:\Git\rnrealmapp\.vscode\.react'
    at Function.getWrappedError (c:\Users\XXX\.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:150748)
    at Function.wrapError (c:\Users\XXX\.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:7038)
    at c:\Users\XXX\.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:200306
[Error] Failed to activate the React Native Tools extension (error code 702)

**Comment by VPelt** [comment]
Disabling, renableing and restart of vscode seems to 'solve' this issue. Just anoying to do early in the morning.

Once it runs it runs for a whole day

**Comment by SounD120** [comment]
@VPelt, preview and stable seem to be in conflict when both are installed at the same time. The preview branch will be back online soon(right now it doesn't receive updates), so this problems should be resolved in it. But the stable branch is currently the most recent, so it is not recommended to use both versions at the same time.

**Comment by SounD120** [comment]
@VPelt The preview branch is available now and the next release should be released tomorrow. Give it a try and let us know if the problems you described persist.

**Comment by VPelt** [comment]
@SounD120 i even get this in 1.0.1 after uninstalling the preview extension

[2020-10-13 09:21:44.958] [renderer1] [error] Cannot read property 'getRnCdpProxy' of undefined: TypeError: Cannot read property 'getRnCdpProxy' of undefined
    at E.<anonymous> (c:\Users\XXX\.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:115643)
    at Generator.next (<anonymous>)
    at c:\Users\v.pelt\.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:113369
    at new Promise (<anonymous>)
    at n (c:\Users\XXX\.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:113114)
    at E.disconnectRequest (c:\Users\XXX\.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:115583)
    at E.<anonymous> (c:\Users\XXX\.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:389654)
    at Generator.next (<anonymous>)
    at c:\Users\XXX\.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:385782
    at new Promise (<anonymous>)
    at n (c:\Users\XXX\.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:385527)
    at E.disconnectRequest (c:\Users\XXX\.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:389468)
    at E.dispatchRequest (c:\Users\XXX\.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:121874)
    at E.dispatchRequest (c:\Users\XXX\.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:361655)
    at E.handleMessage (c:\Users\XXX.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:358523)
    at E._handleData (c:\Users\XXX\.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:360245)
    at Socket.<anonymous> (c:\Users\XXX\.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:358855)
    at Socket.emit (events.js:223:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)

**Comment by SounD120** [comment]
@VPelt This issue has been fixed in the [Preview extension](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native-preview), and not yet released in [Stable](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native). As soon as an updated Stable version will be released - this problem will be resolved.

**Comment by SounD120** [comment]
@VPelt If the following issue persists even after updates - please open a new issue for this, since it unlikely connected with the original one. 
```
[Error] Failed to setup the stub launcher for the debugger (error code 703)

Stack: Error: Failed to setup the stub launcher for the debugger (error code 703): EEXIST: file already exists, mkdir 'c:\Git\rnrealmapp.vscode.react'
at Function.getWrappedError (c:\Users\XXX.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:150748)
at Function.wrapError (c:\Users\XXX.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:7038)
at c:\Users\XXX.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:200306
[Error] Failed to activate the React Native Tools extension (error code 702)
```
