### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by KishoreBarik** [microsoft/vscode-react-native#1433]
# 🐛 What is the bug? How can we reproduce it?

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:

1. Step 1
Open VScode command dialog using ctrl+ shift+p and execute 
`React Native: Run Android on Emulator`

## Expected behavior

It should launch the emulator, start the metro server and then run the application

## Debug output

<details>
<summary>React Native output channel</summary>

```text

[Error] Failed to run the application in Android (error code 104)

Stack: Error: Failed to run the application in Android (error code 104): Error while executing command 'emulator -list-avds': Command failed: emulator -list-avds
'emulator' is not recognized as an internal or external command,
operable program or batch file.

	at Function.getWrappedError (c:\Users\DELL\.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:150748)
	at Function.wrapError (c:\Users\DELL\.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:7038)
	at c:\Users\DELL\.vscode\extensions\msjsdiag.vscode-react-native-1.0.1\dist\rn-extension.js:1:200306
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

workbench.desktop.main.js:sourcemap:3067 Command 'React Native: Run Android on Emulator' resulted in an error (Error while executing command 'emulator -list-avds': Command failed: emulator -list-avds 'emulator' is not recognized as an internal or external command, operable program or batch file. )
onDidChangeNotification @ workbench.desktop.main.js:sourcemap:3067
(anonymous) @ workbench.desktop.main.js:sourcemap:3066
fire @ workbench.desktop.main.js:sourcemap:96
addNotification @ workbench.desktop.main.js:sourcemap:3133
error @ workbench.desktop.main.js:sourcemap:4878
accept @ workbench.desktop.main.js:sourcemap:2848
async function (async)
accept @ workbench.desktop.main.js:sourcemap:2847
(anonymous) @ workbench.desktop.main.js:sourcemap:1790
fire @ workbench.desktop.main.js:sourcemap:96
(anonymous) @ workbench.desktop.main.js:sourcemap:1205
fire @ workbench.desktop.main.js:sourcemap:96
(anonymous) @ workbench.desktop.main.js:sourcemap:1216

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` 

```text
Common
 ✓ Node.js
 ✓ npm
 ✓ Python

Android
 ✓ JDK
 ✖ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME
```
Note: I have Android Studio installed.
* `envinfo`:

```text
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 15.46 GB / 23.88 GB
  Binaries:
    Node: 12.16.1 - E:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - E:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - E:\Program Files\nodejs\npm.CMD
  Managers:
    Composer: 1.10.6 - C:\ProgramData\ComposerSetup\bin\composer.BAT
    pip2: 19.2.3 - C:\Python27\Scripts\pip2.EXE
  Utilities:
    Git: 2.27.0. - e:\Program Files\Git\cmd\git.EXE
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3
      System Images: android-23 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
  IDEs:
    VSCode: 1.49.2 - C:\Program Files\Microsoft VS Code\bin\code.CMD
    Visual Studio: 16.7.30413.136 (Visual Studio Community 2019)
```

* React Native Tools extension version: 1.0.1

**Comment by SounD120** [comment]
Hi @KishoreBarik and thanks for the question. This issue looks pretty similar to https://github.com/microsoft/vscode-react-native/issues/1423, so I'd recommend you to check that all requirements from official React Native Getting Started docs are met.
Please let us know if this helped.

**Comment by SounD120** [comment]
@KishoreBarik is this issue still relevant for you?

**Comment by SounD120** [comment]
@KishoreBarik I am closing this issue due to no activity.
