### ISSUE TITLE
windows vs code react-native tools No sdk.dir value found in local.properties file. Using Android SDK location from PATH.

### ISSUE THREAD

**Issue by gfmoore** [microsoft/vscode-react-native#1638]
## Actual Behavior
1. When i do F1 React Native Run Android on Device I get the message
windows react-native tools No sdk.dir value found in local.properties file. Using Android SDK location from PATH.
2.  Usually the app starts on my connected Android phone, the Android emulator being too flaky, but that for another issue.

## Expected Behavior
1. No error message
2. 

## Software versions
- React-Native VS Code extension version:  1.6.0
- VSCode version:  1.60.0 insiders
- OS platform and version:  win 10 pro 21h1 19043.1151
- NodeJS version:  v16.3.0
- React Native version:  0.64.2
- Expo SDK version (include if relevant): bare bones/metal ;)

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
``` Can't see a View > Toggle Output ??? VS Code ?

```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
console.ts:137 [Extension Host] (node:13860) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code - Insiders --trace-deprecation ...` to show where the warning was created) (at writeOut (internal/process/warning.js:43:3))
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.java.
Old grammar file: file:///c%3A/Users/Gordon/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/java/syntaxes/java.tmLanguage.json.
New grammar file: file:///c%3A/Users/Gordon/.vscode-insiders/extensions/redhat.java-0.80.0/syntaxes/java.tmLanguage.json
mainThreadExtensionService.ts:63 [[object Object]]s.tmpDir is not a function
mainThreadExtensionService.ts:64 TypeError: s.tmpDir is not a function
	at e._sendFirstFileOnDisk (c:\Users\Gordon\.vscode-insiders\extensions\msjsdiag.vscode-react-native-1.6.0\dist\rn-extension.js:1:25358)
	at Timeout._onTimeout (c:\Users\Gordon\.vscode-insiders\extensions\msjsdiag.vscode-react-native-1.6.0\dist\rn-extension.js:1:24162)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
mainThreadExtensionService.ts:63 [[object Object]]s.tmpDir is not a function
mainThreadExtensionService.ts:64 TypeError: s.tmpDir is not a function
	at e._sendFirstFileOnDisk (c:\Users\Gordon\.vscode-insiders\extensions\msjsdiag.vscode-react-native-1.6.0\dist\rn-extension.js:1:25358)
	at Timeout._onTimeout (c:\Users\Gordon\.vscode-insiders\extensions\msjsdiag.vscode-react-native-1.6.0\dist\rn-extension.js:1:24162)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
```

I've tried creating a android > local.properties file with contents  sdk.dir = C:\\Android\\android-sdk as some have suggested, bit no joy.

the doctor gives a clean bill of health.

**Comment by gfmoore** [comment]
Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):

Cant see this option ????

**Comment by RedMickey** [comment]
Hi @gfmoore and thanks for reaching us. The extension detects if there is a `local.properties` file in the `your_project_root/android` folder. If the file exists, the extension will try to parse `sdk.dir` string from the file. In case this string is absent in the file or the extension failed to parse it, React Native Tools will print just an information message about this:
```
[Info] No sdk.dir value found in local.properties file. Using Android SDK location from PATH.
```
After that the extension will use Android SDK location pointed in `PATH`.
This isn't an error message, so it is not necessary to add `sdk.dir` string to the `local.properties` file.

Currently the extension [can parse the `sdk.dir` parameter correctly](https://github.com/microsoft/vscode-react-native/blob/master/src/extension/android/adb.ts#L194) only if the assignment operator (`=`) is used without whitespaces around it. The extension can parse the following strings:
```
sdk.dir=C:\Android\android-sdk
sdk.dir=C:\\Android\\android-sdk
sdk.dir=C\:\\Android\\android-sdk
```

Could you please try to use one of the strings above in your `local.properties` file and let us know if it works for you?

We can enhance `sdk.dir` parameter parsing and enable using one whitespace before and one after the the assignment operator (`=`) in the string.

> Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
> 
> Cant see this option ????

`React Native` output channel appears in Output ListBox on starting a debugging scenario or extension's Command Palette command related to launching the application or the packager (e.g. `Run Android on Device`).
![image](https://user-images.githubusercontent.com/33267199/129186348-fda1265a-9e4f-4431-a3f3-c2fea688d8eb.png)
