### ISSUE TITLE
Tips Notifications panel opens without content at start

### ISSUE THREAD

**Issue by uloco** [microsoft/vscode-react-native#1651]
# 🐛 What is the bug? How can we reproduce it?

1. Install this extension
2. Set `"react-native-tools.showUserTips": false,` config in settings
2. Close the panel
3. Restart VScode  or use "Reload Window" command.
4. Panel opens on the _Output_ tab with _Tips Notifications_ dropdown menu focused with no output information or tips showing at all.
5. Same behaviour if showUserTips is true

## Expected behavior
The panel should not open at all

## Debug output

<details>
<summary>Debug Console</summary>

```text

no output

```
</details>

<details>
<summary>React Native output channel</summary>

```text

PASTE OUTPUT OF REACT-NATIVE OUTPUT CHANNEL (View -> Toggle Output -> Select React-Native in ListBox)

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

[Extension Host] (node:73198) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
S @ console.ts:137
console.ts:137 [Extension Host] [vscode-icons] v11.6.0 activated!
log.ts:301   ERR s.tmpDir is not a function: TypeError: s.tmpDir is not a function
    at e._sendFirstFileOnDisk (/Users/uloco/.vscode/extensions/msjsdiag.vscode-react-native-1.6.0/dist/rn-extension.js:1:25358)
    at Timeout._onTimeout (/Users/uloco/.vscode/extensions/msjsdiag.vscode-react-native-1.6.0/dist/rn-extension.js:1:24162)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```
</details>

## Environment

Please tell us about your system and your project:

```text
❯ npx react-native doctor
Common
 ✓ Node.js
 ✓ npm
 ✖ Watchman - Used for watching changes in the filesystem when in development mode
   - Version found: 2021.08.02.00
   - Version supported: 4.x

Android
 ✖ JDK
   - Version found: 1.8.0_292
   - Version supported: >= 8
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ ios-deploy - Required for installing your app on a physical device with the CLI

Errors:   2
Warnings: 0
```

* `envinfo`:

```text

  System:
    OS: macOS 11.5.2
    CPU: (8) x64 Apple M1
    Memory: 113.96 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.6.0 - /var/folders/j5/ckgkc5b95wb6p5vhwt_h9dyr0000gn/T/fnm_multishells/68163_1629794112484/bin/node
    npm: 7.19.1 - /var/folders/j5/ckgkc5b95wb6p5vhwt_h9dyr0000gn/T/fnm_multishells/68163_1629794112484/bin/npm
    Watchman: 2021.08.02.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
    Homebrew: 3.2.9 - /opt/homebrew/bin/brew
    pip3: 21.1.3 - /opt/homebrew/bin/pip3
    RubyGems: 3.2.22 - /opt/homebrew/opt/ruby/bin/gem
  Utilities:
    CMake: 3.21.1 - /opt/homebrew/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.33.0 - /opt/homebrew/bin/git
    Clang: 12.0.5 - /usr/bin/clang
  Servers:
    Apache: 2.4.46 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.7 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.59.1 - /opt/homebrew/bin/code
    Vim: 8.2 - /usr/bin/vim
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_292 - /usr/bin/javac
    Perl: 5.30.2 - /usr/bin/perl
    PHP: 7.3.24 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.9.6 - /opt/homebrew/bin/python3
    Ruby: 3.0.2 - /opt/homebrew/opt/ruby/bin/ruby
  Databases:
    MongoDB: 5.0.2 - /opt/homebrew/bin/mongo
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 92.0.4515.159
    Safari: 14.1.2

```

* React Native Tools extension version: 1.6.0
* Expo SDK version (if applicable): not using expo

**Comment by JiglioNero** [comment]
Hi @uloco and thanks for contuct us. We have already revealed and fixed this bug in the [PR](https://github.com/microsoft/vscode-react-native/pull/1642). The fixes will be available in the next extension release.
