### ISSUE TITLE
[Bug] Permission denied when try to run Network inspector

### ISSUE THREAD

**Issue by balvarez-hub** [microsoft/vscode-react-native#1660]
# 🐛 What is the bug? How can we reproduce it?

1. Launch Command 'Run Network inspector'

## Expected behaviour

Run the network inspector

## Debug output

<details>
<summary>Debug Console</summary>

```text

There is no error in Debug console

```
</details>

<details>
<summary>React Native output channel</summary>

```text

[Error] Error: Error while executing command 'adb -s "emulator-5554" shell "echo 'cp "/sdcard/sonarCA.crt" "/data/user/0/com.hubescuela.plaza/files/sonar/sonarCA.crt" && chmod 644 "/data/user/0/com.hubescuela.plaza/files/sonar/sonarCA.crt"' | run-as 'com.hubescuela.plaza'"': Command failed: adb -s "emulator-5554" shell "echo 'cp "/sdcard/sonarCA.crt" "/data/user/0/com.hubescuela.plaza/files/sonar/sonarCA.crt" && chmod 644 "/data/user/0/com.hubescuela.plaza/files/sonar/sonarCA.crt"' | run-as 'com.hubescuela.plaza'"
cp: bad '/sdcard/sonarCA.crt': Permission denied

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

mainThreadExtensionService.ts:63 [[object Object]]s.tmpDir is not a function
mainThreadExtensionService.ts:64 TypeError: s.tmpDir is not a function
	at e._sendFirstFileOnDisk (c:\Users\borja\.vscode\extensions\msjsdiag.vscode-react-native-1.6.1\dist\rn-extension.js:1:25358)
	at Timeout._onTimeout (c:\Users\borja\.vscode\extensions\msjsdiag.vscode-react-native-1.6.1\dist\rn-extension.js:1:24162)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)

```
</details>

## Environment

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
Common
 ✓ Node.js
 ✓ npm

Android
 ✖ JDK
   - Version found: 1.8.0_292
   - Version supported: >= 8
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: 28.0.3, 29.0.2, 30.0.2, 30.0.3
   - Version supported: 29.0.3
 ✓ ANDROID_HOME
```

* `envinfo`:

```text
  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
    Memory: 5.48 GB / 15.95 GB
  Binaries:
    Node: 16.8.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.21.0 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.31.1. - C:\Program Files\Git\cmd\git.EXE
  Virtualization:
    Docker: 20.10.2 - C:\ProgramData\DockerDesktop\version-bin\docker.EXE
  SDKs:
    Android SDK:
      API Levels: 25, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    VSCode: 1.59.1 - C:\Users\borja\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 4.4.19 - C:\WINDOWS\system32\bash.EXE
    Java: 1.8.0_292 - C:\Program Files\OpenJDK\openjdk-8u292-b10\bin\javac.EXE
  Databases:
    SQLite: 3.32.2 - C:\Users\borja\AppData\Local\Android\Sdk\platform-tools\sqlite3.EXE
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.84)
    Internet Explorer: 11.0.19041.906
```

* React Native Tools extension version: 1.6.1

**Comment by balvarez-hub** [comment]
The file sonarCA.crt not exist in path /sdcard/sonarCA.crt
``` adb
PS D:\hub\Proyectos\plaza-tablet-v2> adb -s "emulator-5554" shell "ls -a /sdcard/"
Alarms
Android
Audiobooks
DCIM
Documents
Download
Movies
Music
Notifications
Pictures
Podcasts
Ringtones
PS D:\hub\Proyectos\plaza-tablet-v2>

**Comment by RedMickey** [comment]
Hi @balvarez-hub and thanks for reaching us. Could you please tell us if you are using a real Android device (not an emulator) with the network inspector?

**Comment by JiglioNero** [comment]
Hi @balvarez-hub. It seems the error was in the directory to the `temp` folder used for forwarding certificates. Please try out the extension with the fix by following these steps:

1. Download and unzip compiled extension [VSIX](https://github.com/microsoft/vscode-react-native/files/7115705/vscode-react-native-1.6.1.vsix.zip)
2. Uninstall the extension
3. Close VS Code
4. Open VS Code
5. Click Extensions -> ... -> `Install from VSIX...` and select downloaded VSIX

**Comment by balvarez-hub** [comment]
Hi @RedMickey and @JiglioNero , thanks for your patience. The message that appeared was shown in mobile and emulator.

However,  @JiglioNero solution works perfectly.

Thanks!
