### ISSUE TITLE
Run iOS on Simulator not working on Mac M1

### ISSUE THREAD

**Issue by KishoreBarik** [microsoft/vscode-react-native#1689]
# 🐛 What is the bug? How can we reproduce it?

Run VSCode Command `Run iOS on Simulator` launches the simulator but unable to install the app in that and fails. But I am able to run the app using terminal `react-native run-ios`.

## Expected behavior

App should be built and launched on iOS simulator.

## Debug output

<details>
<summary>React Native: Run iOS output</summary>

```text

info Found Xcode workspace "xxxxxx.xcworkspace"
error Could not find a device with udid: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX1E". Available devices:

```
</details>

<details>
<summary>React Native output channel</summary>

```text
Stack: Error: Failed to run the application in iOS (error code 105): Unknown error: not all success patterns were matched. 
 It means that "react-native run-ios" command failed. 
 Please, check the View -> Toggle Output -> React Native, 
 View -> Toggle Output -> React Native: Run ios output windows. (error code 712)
	at Function.getWrappedError (/Users/sails-dm166/.vscode/extensions/msjsdiag.vscode-react-native-1.7.1/dist/rn-extension.js:21:67029)
	at Function.wrapError (/Users/sails-dm166/.vscode/extensions/msjsdiag.vscode-react-native-1.7.1/dist/rn-extension.js:21:60139)
	at /Users/sails-dm166/.vscode/extensions/msjsdiag.vscode-react-native-1.7.1/dist/rn-extension.js:21:59712

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

log.ts:289  INFO Starting extension host with pid 80728.
log.ts:301   ERR [Extension Host] (node:80728) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:80728) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
v @ console.ts:137
localProcessExtensionHost.ts:335 Extension Host
localProcessExtensionHost.ts:336 objc[80807]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x203a9fb78) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x11815c2c8). One of the two will be used. Which one is undefined.objc[80807]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x203a9fbc8) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x11815c318). One of the two will be used. Which one is undefined.
localProcessExtensionHost.ts:335 Extension Host
localProcessExtensionHost.ts:336 objc[80818]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x203a9fb78) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x117eb02c8). One of the two will be used. Which one is undefined.objc[80818]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x203a9fbc8) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x117eb0318). One of the two will be used. Which one is undefined.
localProcessExtensionHost.ts:335 Extension Host
localProcessExtensionHost.ts:336 objc[80829]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x203a9fb78) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1185442c8). One of the two will be used. Which one is undefined.objc[80829]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x203a9fbc8) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x118544318). One of the two will be used. Which one is undefined.
localProcessExtensionHost.ts:335 Extension Host
localProcessExtensionHost.ts:336 objc[80840]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x203a9fb78) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x11427c2c8). One of the two will be used. Which one is undefined.objc[80840]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x203a9fbc8) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x11427c318). One of the two will be used. Which one is undefined.
localProcessExtensionHost.ts:335 Extension Host
localProcessExtensionHost.ts:336 objc[80851]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x203a9fb78) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1145702c8). One of the two will be used. Which one is undefined.objc[80851]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x203a9fbc8) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x114570318). One of the two will be used. Which one is undefined.
localProcessExtensionHost.ts:335 Extension Host
localProcessExtensionHost.ts:336 objc[80862]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x203a9fb78) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x113eb02c8). One of the two will be used. Which one is undefined.objc[80862]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x203a9fbc8) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x113eb0318). One of the two will be used. Which one is undefined.
localProcessExtensionHost.ts:335 Extension Host
localProcessExtensionHost.ts:336 objc[80876]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x203a9fb78) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1180402c8). One of the two will be used. Which one is undefined.objc[80876]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x203a9fbc8) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x118040318). One of the two will be used. Which one is undefined.
mainThreadExtensionService.ts:63 [[object Object]]s.tmpDir is not a function
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
_ @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
mainThreadExtensionService.ts:64 TypeError: s.tmpDir is not a function
	at e._sendFirstFileOnDisk (vscode-file://vscode-app/Users/sails-dm166/.vscode/extensions/msjsdiag.vscode-react-native-1.7.1/dist/rn-extension.js:1)
	at Timeout._onTimeout (vscode-file://vscode-app/Users/sails-dm166/.vscode/extensions/msjsdiag.vscode-react-native-1.7.1/dist/rn-extension.js:1)
	at listOnTimeout (internal/timers.js:554)
	at processTimers (internal/timers.js:497)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
_ @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
mainThreadExtensionService.ts:63 [[object Object]]s.tmpDir is not a function
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
_ @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
mainThreadExtensionService.ts:64 TypeError: s.tmpDir is not a function
	at e._sendFirstFileOnDisk (vscode-file://vscode-app/Users/sails-dm166/.vscode/extensions/msjsdiag.vscode-react-native-1.7.1/dist/rn-extension.js:1)
	at Timeout._onTimeout (vscode-file://vscode-app/Users/sails-dm166/.vscode/extensions/msjsdiag.vscode-react-native-1.7.1/dist/rn-extension.js:1)
	at listOnTimeout (internal/timers.js:554)
	at processTimers (internal/timers.js:497)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
_ @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
Common
 ✓ Node.js
 ✓ npm
 ✖ Watchman - Used for watching changes in the filesystem when in development mode
   - Version found: 2021.06.07.00
   - Version supported: 4.x

Android
 ✖ JDK
   - Version found: 1.8.0_292
   - Version supported: >= 8
 ✖ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ● ios-deploy - Required for installing your app on a physical device with the CLI

Errors:   3
Warnings: 1
```

* `envinfo`:

```text

  System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 136.97 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    npm: 7.12.0 - ~/Projects/XXXX-app/node_modules/.bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
    Homebrew: 3.2.3 - /opt/homebrew/bin/brew
    pip3: 21.1.3 - /opt/homebrew/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.30.1 - /usr/bin/git
    Clang: 12.0.5 - /usr/bin/clang
  Servers:
    Apache: 2.4.48 - /usr/sbin/apachectl
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.3, 30.0.3
      System Images: android-29 | Google Play ARM 64 v8a, android-30 | Google APIs ARM 64 v8a
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.2 - /usr/bin/vim
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_292 - /usr/bin/javac
    Perl: 5.30.2 - /usr/bin/perl
    PHP: 7.3.29 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.9.6 - /opt/homebrew/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 95.0.4638.54
    Safari: 15.0
```

* React Native Tools extension version: 1.7.1

![Screenshot 2021-10-22 at 12 56 34 PM](https://user-images.githubusercontent.com/13726932/138684153-15093ec8-d0d6-45a5-89e9-2df44f4fe645.png)

**Comment by KishoreBarik** [comment]
Thank you @RedMickey . The further issue is caused by project setup may be. Because it is failing due to the share extension. We can reproduce that using Xcode build as well. So I think we can close this issue. 
Another issue I have noticed is the launch android emulator bundles the JS within it - looks like. Will investigate further when I work on android. Thanks.

**Comment by RedMickey** [comment]
@KishoreBarik 
The `Launch Android Emulator` command doesn't run an RN application, it just starts an Android emulator.
The `Run Android on Emulator` command starts an Android emulator and runs the RN project. If an Android emulator is started via this extension's command, we point its id in the `react-native run-android --deviceId emulator_id` command, that the extension executes to run the RN app on the selected emulator. This React Native command has some peculiarities and causes building a release APK file if there is the ` --deviceId` parameter in the command. We have already investigated the behavior of this command, and you can find more info [here](https://github.com/microsoft/vscode-react-native/issues/1645#issuecomment-905358632).

Feel free to contact us if you have any other questions or need our help.

**Comment by KishoreBarik** [comment]
Sorry I meant `Run Android on Emulator` which builds a release package.

**Comment by RedMickey** [comment]
It seems that this is the expected behavior of the `Run Android on Emulator` command, since it is reproduced in the terminal using the `npx react-native run-android --deviceId emulator_id` command.
You can also try to use `Run...` debug scenarios (e.g. `Run Android`) without specifying the `target` parameter.
```
    {
      "name": "Run Android",
      "request": "launch",
      "type": "reactnative",
      "cwd": "${workspaceFolder}",
      "enableDebug": false,
      "platform": "android"
    }
```
`Run...` debug scenarios start applications without further debugger attachment, so they work almost the same way as Command Palette commands.
