### ISSUE TITLE
[Bug] JavascriptException when using debugger with specific third party component

### ISSUE THREAD

**Issue by MartijnGevaert** [microsoft/vscode-react-native#1728]
# 🐛 What is the bug? How can we reproduce it?

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:

1. Install the react-native-cn-quill extension
2. Add following component to a project:
```
export default function RichTextEditor(props?: RichTextEditorProps) {
  const _editor = React.createRef<QuillEditor>();

  return (
    <SafeAreaView style={styles.root}>
      <QuillEditor
        style={styles.editor}
        ref={_editor}
        initialHtml="<h1>Quill Editor for react-native</h1>"
      />
    </SafeAreaView>
  );
}
```
3. Run the project without debugger, everything runs fine
4. Enable the vscode Debugger, I get this screen:
![image](https://user-images.githubusercontent.com/41551215/149819279-801a43db-4c59-48ee-a55a-2fc45816b602.png)

## Expected behavior

The debugger to work with or without the Quill component.
When just running `yarn android` and opening the web debugger, everything works fine, therefore I think this is an issue related to this extensions.
The symptoms seems to be identical to the ones logged in this issue:
https://github.com/facebook/react-native/issues/26762

## Debug output

<details>
<summary>Debug console</summary>

```text
Attaching to the application
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Debugger worker loaded runtime on port 12616
Debugger worker loaded runtime on port 4839
Debugger worker loaded runtime on port 23646
Debugger worker loaded runtime on port 8120
```
</details>

<details>
<summary>React Native output channel</summary>

```text
I was not able to follow these instructions, can't find a Toggle Output option.
PASTE OUTPUT OF REACT-NATIVE OUTPUT CHANNEL (View -> Toggle Output -> Select React-Native in ListBox)

```
</details>

<details>
<summary>Developer Tools console</summary>

```text
workbench.desktop.main.js:2982 [redhat.vscode-xml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
_logMessageInConsole @ workbench.desktop.main.js:2982
workbench.desktop.main.js:2982 [redhat.vscode-yaml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
_logMessageInConsole @ workbench.desktop.main.js:2982
workbench.desktop.main.js:577   ERR [Extension Host] (node:9736) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
workbench.desktop.main.js:77 [Extension Host] (node:9736) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code --trace-deprecation ...` to show where the warning was created)
I @ workbench.desktop.main.js:77
workbench.desktop.main.js:1720 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///c%3A/Users/MartijnGevaert/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///c%3A/Users/MartijnGevaert/.vscode/extensions/redhat.vscode-yaml-1.3.0/syntaxes/yaml.tmLanguage.json
register @ workbench.desktop.main.js:1720
workbench.desktop.main.js:1892 [[object Object]]s.tmpDir is not a function
$onExtensionRuntimeError @ workbench.desktop.main.js:1892
workbench.desktop.main.js:1892 TypeError: s.tmpDir is not a function
	at e._sendFirstFileOnDisk (c:\Users\MartijnGevaert\.vscode\extensions\msjsdiag.vscode-react-native-1.8.0\dist\rn-extension.js:1:25358)
	at Timeout._onTimeout (c:\Users\MartijnGevaert\.vscode\extensions\msjsdiag.vscode-react-native-1.8.0\dist\rn-extension.js:1:24162)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
$onExtensionRuntimeError @ workbench.desktop.main.js:1892
workbench.desktop.main.js:77 [Extension Host] Couldn't stop monitoring logcat: Cannot read property 'dispose' of undefined
I @ workbench.desktop.main.js:77
workbench.desktop.main.js:77 [Extension Host] process Array(2)
workbench.desktop.main.js:577   ERR [Extension Host] Unknown request: completions
workbench.desktop.main.js:77 [Extension Host] Unknown request: completions
I @ workbench.desktop.main.js:77
workbench.desktop.main.js:1892 [[object Object]]s.tmpDir is not a function
$onExtensionRuntimeError @ workbench.desktop.main.js:1892
workbench.desktop.main.js:1892 TypeError: s.tmpDir is not a function
	at e._sendFirstFileOnDisk (c:\Users\MartijnGevaert\.vscode\extensions\msjsdiag.vscode-react-native-1.8.0\dist\rn-extension.js:1:25358)
	at Timeout._onTimeout (c:\Users\MartijnGevaert\.vscode\extensions\msjsdiag.vscode-react-native-1.8.0\dist\rn-extension.js:1:24162)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
$onExtensionRuntimeError @ workbench.desktop.main.js:1892
workbench.desktop.main.js:1892 [[object Object]]s.tmpDir is not a function
$onExtensionRuntimeError @ workbench.desktop.main.js:1892
workbench.desktop.main.js:1892 TypeError: s.tmpDir is not a function
	at e._sendFirstFileOnDisk (c:\Users\MartijnGevaert\.vscode\extensions\msjsdiag.vscode-react-native-1.8.0\dist\rn-extension.js:1:25358)
	at Timeout._onTimeout (c:\Users\MartijnGevaert\.vscode\extensions\msjsdiag.vscode-react-native-1.8.0\dist\rn-extension.js:1:24162)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
$onExtensionRuntimeError @ workbench.desktop.main.js:1892
workbench.desktop.main.js:77 [Extension Host] process Array(2)
workbench.desktop.main.js:77 [Extension Host] process Array(2)
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/899d46d82c4c95423fb7e10e68eba52050e30ba3/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout
```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

(Not sure why I have these errors, everything works fine except when adding the cn-quil extension AND trying to debug).
```text
Common
 ✓ Node.js
 ✓ yarn

Android
 ✖ JDK
   - Version found: N/A
   - Version supported: 1.8.x || >= 9
 ✖ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME

Errors:   2
Warnings: 0
```

* `envinfo`:

```text
 System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 1.63 GB / 15.75 GB
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE       
    Yarn: 3.1.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD 
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Managers:
    pip3: 21.3.1 - C:\Python39\Scripts\pip3.EXE
  Utilities:
    Git: 2.28.0.
  Virtualization:
    Docker: 20.10.5 - C:\ProgramData\DockerDesktop\version-bin\docker.EXE  
  SDKs:
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-29 | Intel x86 Atom_64
  IDEs:
    VSCode: 1.63.2 - C:\Users\MartijnGevaert\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 4.4.19 - C:\Windows\system32\bash.EXE
    Python: 3.9.0
  Databases:
    SQLite: 3.32.2 - C:\Users\MartijnGevaert\AppData\Local\Android\Sdk\platform-tools\sqlite3.EXE
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.62)
    Internet Explorer: 11.0.19041.1202
```

* React Native Tools extension version: 1.9.0, 1.8.1 and 1.8.0
* Expo SDK version (if applicable): /

**Comment by RedMickey** [comment]
Hi @MartijnGevaert and thanks for reaching us. We fixed this issue in the [PR](https://github.com/microsoft/vscode-react-native/pull/1730), and now the fix is available in the [preview version of React Native Tools extension](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native-preview) (`React Native Tools (Preview)`). You can try it out without waiting for the next stable release.
**Note:** to use the preview version it is needed to disable or remove the stable version and reload VS Code.

**Comment by MartijnGevaert** [comment]
I can confirm this fixed the issue for me, thanks!
