### ISSUE TITLE
[Bug] Restart/Stop Packager not killing node process

### ISSUE THREAD

**Issue by AfrazHussain** [microsoft/vscode-react-native#1794]
# 🐛 What is the bug? How can we reproduce it?

The `Start Packager` command starts the React Native Packager just fine, but if I try to restart or stop the packager using `Restart Packager` or `Stop Packager` commands, the extension reports that the packager was stopped, but the node process is not terminated. This causes issues particularly when I have to restart the packager by using the `Restart Packager` command, where the extension reports `[Info] Packager stopped`  but then outputs `[Warning] Error: Packager is still running. If the packager was started outside VS Code, please quit the packager process using the task manager.`

To use the extension again, I have to manually kill the node process by getting the node process port using `ps aux | grep node` and killing the process with `kill -9 <pid>`.

Steps to reproduce:

1. Create new RN project 
2. Use the `Run iOS on Simulator` command
3. Use the `Restart packager` command, or `Stop packager` and then `Start packager` (both have the same behaviour)

I have tried using the LTS version and I am currently on the Preview version.

## Expected behavior

What were you expecting to happen?

## Debug output

<details>
<summary>React Native output channel</summary>

```text

[Info] Starting Packager

                                                      
                        #######                       
                   ################                   
                #########     #########               
            #########             ##########          
        #########        ######        #########      
       ##########################################     
      #####      #####################       #####    
      #####          ##############          #####    
      #####    ###       ######       ###    #####    
      #####    #######            #######    #####    
      #####    ###########    ###########    #####    
      #####    ##########################    #####    
      #####    ##########################    #####    
      #####      ######################     ######    
       ######        #############        #######     
         #########        ####       #########        
              #########          #########            
                  ######### #########                 
                       #########                      
                                                      
                                                      
                    Welcome to Metro!
              Fast - Scalable - Integrated


[Info] Packager started.

[Error] Failed to run the application in iOS (error code 105)

Stack: Error: Failed to run the application in iOS (error code 105): Cannot find module '/Users/afraz/Development/AwesomeProject/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/findXcodeProject'
Require stack:
- /Users/afraz/.vscode/extensions/msjsdiag.vscode-react-native-preview-2022.4.1421/dist/rn-extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
    at Function.getWrappedError (/Users/afraz/.vscode/extensions/msjsdiag.vscode-react-native-preview-2022.4.1421/dist/rn-extension.js:21:69126)
    at Function.wrapError (/Users/afraz/.vscode/extensions/msjsdiag.vscode-react-native-preview-2022.4.1421/dist/rn-extension.js:21:61765)
    at /Users/afraz/.vscode/extensions/msjsdiag.vscode-react-native-preview-2022.4.1421/dist/rn-extension.js:21:61334
 BUNDLE  ./index.js 

 LOG  Running "AwesomeProject" with {"rootTag":1,"initialProps":{}}
[Info] Stopping Packager

[Info] Packager stopped

[Warning] Error: Packager is still running. If the packager was started outside VS Code, please quit the packager process using the task manager.

[Info] Packager is already running.

[Warning] Error: React Native Packager running outside of VS Code. If you want to debug please use the 'Attach to packager' option

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

[Extension Host]  Quokka.js Live Share integration disabled, VSLS not found.
log.ts:313   ERR [Extension Host] (node:24445) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:24445) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper --trace-deprecation ...` to show where the warning was created)
D @ console.ts:137
log.ts:307  WARN [twxs.cmake]: Cannot register 'cmake.cmakePath'. This property is already registered.
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.macro.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/cpp/syntaxes/cpp.embedded.macro.tmLanguage.json.
New grammar file: file:///Users/afraz/.vscode/extensions/jeff-hykin.better-cpp-syntax-1.15.19/autogenerated/cpp.embedded.macro.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.cpp.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/cpp/syntaxes/cpp.tmLanguage.json.
New grammar file: file:///Users/afraz/.vscode/extensions/jeff-hykin.better-cpp-syntax-1.15.19/autogenerated/cpp.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.js.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/javascript/syntaxes/JavaScript.tmLanguage.json.
New grammar file: file:///Users/afraz/.vscode/extensions/mgmcdermott.vscode-language-babel-0.0.36/grammars/Babel-Language.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.js.jsx.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/javascript/syntaxes/JavaScriptReact.tmLanguage.json.
New grammar file: file:///Users/afraz/.vscode/extensions/ms-vscode.vscode-typescript-next-4.8.20220718/syntaxes/JavaScriptReact.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.js.
Old grammar file: file:///Users/afraz/.vscode/extensions/mgmcdermott.vscode-language-babel-0.0.36/grammars/Babel-Language.json.
New grammar file: file:///Users/afraz/.vscode/extensions/ms-vscode.vscode-typescript-next-4.8.20220718/syntaxes/JavaScript.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.ts.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/typescript-basics/syntaxes/TypeScript.tmLanguage.json.
New grammar file: file:///Users/afraz/.vscode/extensions/ms-vscode.vscode-typescript-next-4.8.20220718/syntaxes/TypeScript.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.tsx.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/typescript-basics/syntaxes/TypeScriptReact.tmLanguage.json.
New grammar file: file:///Users/afraz/.vscode/extensions/ms-vscode.vscode-typescript-next-4.8.20220718/syntaxes/TypeScriptReact.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///Users/afraz/.vscode/extensions/redhat.vscode-yaml-1.9.1/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:47
2log.ts:313   ERR s.tmpDir is not a function: TypeError: s.tmpDir is not a function
    at e._sendFirstFileOnDisk (/Users/afraz/.vscode/extensions/msjsdiag.vscode-react-native-preview-2022.4.1421/dist/rn-extension.js:1:25358)
    at Timeout._onTimeout (/Users/afraz/.vscode/extensions/msjsdiag.vscode-react-native-preview-2022.4.1421/dist/rn-extension.js:1:24162)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
contextKeyService.ts:452 Element already has context attribute: pane, expanded, horizontal
c @ contextKeyService.ts:452
log.ts:313   ERR s.tmpDir is not a function: TypeError: s.tmpDir is not a function
    at e._sendFirstFileOnDisk (/Users/afraz/.vscode/extensions/msjsdiag.vscode-react-native-preview-2022.4.1421/dist/rn-extension.js:1:25358)
    at Timeout._onTimeout (/Users/afraz/.vscode/extensions/msjsdiag.vscode-react-native-preview-2022.4.1421/dist/rn-extension.js:1:24162)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
Common
 ✓ Node.js
 ✓ yarn
 ✓ Watchman - Used for watching changes in the filesystem when in development mode

Android
 ✖ JDK
   - Version found: N/A
   - Version supported: 1.8.x || >= 9
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 31.0.0
 ✖ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ● ios-deploy - Required for installing your app on a physical device with the CLI
 ✓ .xcode.env - File to customize Xcode environment

Errors:   3
Warnings: 1
```

* `envinfo`:

Not able to run possibly because of [an existing issue with envinfo](https://github.com/tabrindle/envinfo/issues/222). I have M1 MacBook Pro (arm64) with node `v16.15.1`

* React Native Tools extension version: v2022.4.1421 [Preview]
* Expo SDK version (if applicable): VERSION

**Comment by EzioLi01** [comment]
@AfrazHussain Thanks for reporting, will investigate on this! Any progress will update this issue.

**Comment by EzioLi01** [comment]
Hi @AfrazHussain, checked your output log, I find your debug process is blocked by this error: `Error: Failed to run the application in iOS (error code 105)`, I'm not sure if the RN packager issue is caused by this failure.

Could you please try to use RN 0.68.2 for 1.9.2 RN extension? If you still need to use the latest RN version, you can try to use latest RN extension following this steps #1781?

**Comment by EzioLi01** [comment]
Hey @AfrazHussain, do you have any update on this?

**Comment by EzioLi01** [comment]
> Hey @EzioLi01, my apologies for the late reply. I wasn't feeling well over the past week. That error is actually related to this issue: #1781. I know that a fix has been released for that issue, but I am on the Nightly Preview version of the extension and not the Master branch of this repo. I can try and switch to the master branch of this repo to see if this issue is related to that issue.

That's correct! @AfrazHussain , our extension publish pipeline is broken recently for some internal issue. Sorry for that, please follow the steps in #1781 and try to build the latest version locally and install on your machine, please let me know if you have any issue.

**Comment by EzioLi01** [comment]
> 



> I have tried building it from the latest master branch. This time around I don't get the error from #1781 (as expected) and the iOS builds on the simulator without any error. But when trying to restart or stop the packager, I do get the same error.
> 
> When restarting packager:
> When stopping the same packager after trying to restart:
> P.S. It took me a while to get the release build of the master branch running. I kept getting the error ` Error: An error occurred. Error: spawn vsce ENOENT` when trying to `gulp release`. For anyone getting the same error, to solve it, I had to install [`vsce`](https://github.com/microsoft/vscode-vsce) to my global npm using: `npm install --location=global vsce`.

Thanks @AfrazHussain, I will check it again. One more question, did you do some other operations when you start packager? Or just open project -> build -> restart or stop?

**Comment by EzioLi01** [comment]
> Nope, no other steps. I have mentioned all the steps for reproduction in the issue description. Literally just start a new RN project, and do `Run iOS on Simulator` and then just try to restart the packager. If you or others aren't having this issue, I suspect it could be something to do with my environment setup? I have M1 MacBook Pro as I've mentioned in the issue description, and I have had slight issues with my [Volta](https://github.com/volta-cli/volta) installation previously (I use Volta to manage my Node installations).

Got it, I have MAC M2 and will try it on this machine.

**Comment by EzioLi01** [comment]
> Info] Stopping Packager
> 
> [Info] Packager stopped
> 
> [Info] Packager is already running.
> 
> [Warning] Error: React Native Packager running outside of VS Code. If you want to debug please use the 'Attach to packager' option

Actually I and others tried on different machine, but no lucky to repro this issue, it worked fine when we restart or stop RN packager at any time. I will keep investigating on this.

**Comment by EzioLi01** [comment]
> > Nope, no other steps. I have mentioned all the steps for reproduction in the issue description. Literally just start a new RN project, and do `Run iOS on Simulator` and then just try to restart the packager. If you or others aren't having this issue, I suspect it could be something to do with my environment setup? I have M1 MacBook Pro as I've mentioned in the issue description, and I have had slight issues with my [Volta](https://github.com/volta-cli/volta) installation previously (I use Volta to manage my Node installations).
> 
> Got it, I have MAC M2 and will try it on this machine.

Actually I and others tried on different machine, but no lucky to repro this issue, it worked fine when we restart or stop RN packager at any time. I will keep investigating on this.

**Comment by EzioLi01** [comment]
> > Actually I and others tried on different machine, but no lucky to repro this issue, it worked fine when we restart or stop RN packager at any time. I will keep investigating on this.
> 
> Okay, that's very strange. I will close this issue for now and will investigate this from my end and update this issue when I've found any solutions to this. Thank you for your time in investigating this. Really appreciate it!

Thanks @AfrazHussain , if can find root cause, maybe you can share some info in this issue, I will keep tracking this!

**Comment by EzioLi01** [comment]
> Okay, I figured it out. It, in fact, was an issue with my Node installation with [Volta](https://volta.sh/). I [uninstalled my Volta installation](https://docs.volta.sh/advanced/uninstall), and then switch on to [NVM](https://github.com/nvm-sh/nvm). No issues after that. Thank you for your time. Hopefully this can be of help to others having similar issues on Volta + Apple Silicon.

Awesome! Thanks for your solution!
