### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by atif7865** [microsoft/vscode-react-native#1825]
# 🐛 What is the bug? How can we reproduce it?

Packager does not start when trying from within debugger.  Running expo start works fine. 

## Expected behavior

The packager should run and debugging start. Content of my launch.json are as follows:

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug in Exponent",
            "cwd": "${workspaceFolder}",
            "type": "reactnative",
            "request": "launch",
            "platform": "exponent",
            "sourceMaps": true
        }
    ]
}

What were you expecting to happen?

## Debug output

<details>
<summary>Debug Console</summary>

```text

PASTE OUTPUT OF DEBUG CONSOLE (View -> Toggle Debug Console)

Launching the application
An error occurred while launching the application. Could not start the packager. (error code 303)

```
</details>

<details>
<summary>React Native output channel</summary>

```text

PASTE OUTPUT OF REACT-NATIVE OUTPUT CHANNEL (View -> Toggle Output -> Select React-Native in ListBox)

[Info] Making sure your project uses the correct dependencies for Expo. This may take a while...

Checking if this is an Expo app......
[Warning] Couldn't read packager's options from exp.json, continue...

[Info] Starting Packager

[Error] Error: Could not start the packager.

[Error] Error: Could not start the packager.

```

</details>

<details>
<summary>Developer Tools console</summary>

```text

PASTE OUTPUT OF DEVELOPER TOOLS CONSOLE (Help -> Toggle Developer Tools -> Select Console tab)

contextKeyService.ts:452 Element already has context attribute: pane, expanded, horizontal
a @ contextKeyService.ts:452
log.ts:313   ERR [Extension Host] (node:83958) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:83958) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper --trace-deprecation ...` to show where the warning was created)
I @ console.ts:137
mainThreadExtensionService.ts:79 [[object Object]]s.tmpDir is not a function
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
mainThreadExtensionService.ts:80 TypeError: s.tmpDir is not a function
	at e._sendFirstFileOnDisk (vscode-file://vscode-app/Users/atefyamin/.vscode/extensions/msjsdiag.vscode-react-native-1.9.2/dist/rn-extension.js:1:25358)
	at Timeout._onTimeout (vscode-file://vscode-app/Users/atefyamin/.vscode/extensions/msjsdiag.vscode-react-native-1.9.2/dist/rn-extension.js:1:24162)
	at listOnTimeout (node:internal/timers:557:17)
	at processTimers (node:internal/timers:500:7)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:80
console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot set properties of undefined (setting 'reactNativeVersionWarnings')
I @ console.ts:137
console.ts:137 [Extension Host] stack trace: TypeError: Cannot set properties of undefined (setting 'reactNativeVersionWarnings')
    at Object.<anonymous> (/Users/atefyamin/.vscode/extensions/msjsdiag.vscode-react-native-1.9.2/dist/rn-extension.js:53:83952)
    at Generator.next (<anonymous>)
    at s (/Users/atefyamin/.vscode/extensions/msjsdiag.vscode-react-native-1.9.2/dist/rn-extension.js:53:82629)
I @ console.ts:137
log.ts:313   ERR Cannot set properties of undefined (setting 'reactNativeVersionWarnings'): TypeError: Cannot set properties of undefined (setting 'reactNativeVersionWarnings')
    at Object.<anonymous> (/Users/atefyamin/.vscode/extensions/msjsdiag.vscode-react-native-1.9.2/dist/rn-extension.js:53:83952)
    at Generator.next (<anonymous>)
    at s (/Users/atefyamin/.vscode/extensions/msjsdiag.vscode-react-native-1.9.2/dist/rn-extension.js:53:82629)
log.ts:313   ERR s.tmpDir is not a function: TypeError: s.tmpDir is not a function
    at e._sendFirstFileOnDisk (/Users/atefyamin/.vscode/extensions/msjsdiag.vscode-react-native-1.9.2/dist/rn-extension.js:1:25296)
    at Timeout._onTimeout (/Users/atefyamin/.vscode/extensions/msjsdiag.vscode-react-native-1.9.2/dist/rn-extension.js:1:24100)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
log.ts:313   ERR [Extension Host] An error occurred while launching the application. Could not start the packager. (error code 303)
console.ts:137 [Extension Host] An error occurred while launching the application. Could not start the packager. (error code 303)
I @ console.ts:137
log.ts:313   ERR s.tmpDir is not a function: TypeError: s.tmpDir is not a function
    at e._sendFirstFileOnDisk (/Users/atefyamin/.vscode/extensions/msjsdiag.vscode-react-native-1.9.2/dist/rn-extension.js:1:25296)
    at Timeout._onTimeout (/Users/atefyamin/.vscode/extensions/msjsdiag.vscode-react-native-1.9.2/dist/rn-extension.js:1:24100)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)


```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
PASTE OUTPUT OF `npx react-native doctor` or `npx expo doctor`

🎉 Didn't find any issues with the project!
```

* `envinfo`:

```text
PASTE OUTPUT OF `npx envinfo`

```

* React Native Tools extension version: V1.9.2
* Expo SDK version (if applicable):  46

**Comment by EzioLi01** [comment]
Hey @atif7865, thanks for reaching us, could you please provide some repro steps for the investigation?

**Comment by atif7865** [comment]
Issue was resolved! It was a permission issue. A dialog box was buried under other windows. Thank you for response

**Comment by EzioLi01** [comment]
> Issue was resolved! It was a permission issue. A dialog box was buried under other windows. Thank you for response

Cool!
