### ISSUE TITLE
[Bug] "Debug in Exponent" overwrites app.json

### ISSUE THREAD

**Issue by ldorigo** [microsoft/vscode-react-native#1848]
# 🐛 What is the bug? How can we reproduce it?

Starting a debug session with a "Debug in Exponent" configuration (silently!) overwrites `app.json`. This can lead to loss of data and makes troubleshooting very confusing as it happens without notifying the user.

## Expected behavior

No overwriting :-)

## Debug output

<details>
<summary>Debug Console</summary>

Nothing special:

```text
Attaching to the application
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
```
</details>

<details>
<summary>React Native output channel</summary>

Also nothing special:

```text
[Info] Starting React Native Packager.

[Info] A device or an emulator was found, 'adb reverse' command successfully executed.

[Info] Expo server is running. Open your Expo app at exp://127.0.0.1:19000 to see it.

[Info] Scan below QR code to open your app:

[Info] 
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █   █▄▀▀▄▀█ ▄▄▄▄▄ █
█ █   █ █ ▀▄ █▀▄ ▄█ █   █ █
█ █▄▄▄█ █▀██▀▀ ▀▄██ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄▀▄█ █▄█ █▄▄▄▄▄▄▄█
█  ██▄▄▄██▀▀▄▀▀▄ ▄██ ▀▄▄ ▄█
██ ▄ █ ▄ ██▀ ▄██ ▀▀  ▄  ▀██
█▀ ▄  ▄▄ ▄▀▄█▄▀▄▀▄▀▄▀▀▄ ▀██
███▀▀▀▄▄▄▀ ▀█▀██▄▄ ██▄ ▀███
█▄▄▄▄██▄▄ ▄ ▄▀▄ ▄ ▄▄▄ ▀ ▄▄█
█ ▄▄▄▄▄ █▀▄▀ ▄ ▄▀ █▄█ ▀▀███
█ █   █ █▄ ▄█▄ ▀█▄▄ ▄▄▀   █
█ █▄▄▄█ █▀███▀█▀▄▄▄ ▀█▀▀ ██
█▄▄▄▄▄▄▄█▄█▄▄█▄▄████▄▄▄▄▄▄█
[Info] Application is running on Expo. Please shake device and select 'Debug JS Remotely' to enable debugging.
```
</details>

<details>
<summary>Developer Tools console</summary>

```text

workbench.desktop.main.js:633 Conflict in default settings: Ignoring expo.appManifest.fileReferences.showHiddenFiles as expo.appManifest.fileReferences is true
(anonymous) @ workbench.desktop.main.js:633
S @ workbench.desktop.main.js:601
i @ workbench.desktop.main.js:633
get configurationModel @ workbench.desktop.main.js:633
reload @ workbench.desktop.main.js:633
reload @ workbench.desktop.main.js:1365
reloadDefaultConfiguration @ workbench.desktop.main.js:2709
reloadConfiguration @ workbench.desktop.main.js:2709
d @ workbench.desktop.main.js:1056
processTicksAndRejections @ node:internal/process/task_queues:96
await in processTicksAndRejections (async)
startDebugging @ workbench.desktop.main.js:2158
processTicksAndRejections @ node:internal/process/task_queues:96
await in processTicksAndRejections (async)
accept @ workbench.desktop.main.js:2149
await in accept (async)
(anonymous) @ workbench.desktop.main.js:608
invoke @ workbench.desktop.main.js:83
deliver @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:83
handleAccept @ workbench.desktop.main.js:593
(anonymous) @ workbench.desktop.main.js:593
invoke @ workbench.desktop.main.js:83
deliver @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:593
workbench.desktop.main.js:633 Conflict in default settings: Ignoring expo.appManifest.fileReferences.excludeGlobPatterns as expo.appManifest.fileReferences is true
(anonymous) @ workbench.desktop.main.js:633
S @ workbench.desktop.main.js:601
i @ workbench.desktop.main.js:633
get configurationModel @ workbench.desktop.main.js:633
reload @ workbench.desktop.main.js:633
reload @ workbench.desktop.main.js:1365
reloadDefaultConfiguration @ workbench.desktop.main.js:2709
reloadConfiguration @ workbench.desktop.main.js:2709
d @ workbench.desktop.main.js:1056
processTicksAndRejections @ node:internal/process/task_queues:96
await in processTicksAndRejections (async)
startDebugging @ workbench.desktop.main.js:2158
processTicksAndRejections @ node:internal/process/task_queues:96
await in processTicksAndRejections (async)
accept @ workbench.desktop.main.js:2149
await in accept (async)
(anonymous) @ workbench.desktop.main.js:608
invoke @ workbench.desktop.main.js:83
deliver @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:83
handleAccept @ workbench.desktop.main.js:593
(anonymous) @ workbench.desktop.main.js:593
invoke @ workbench.desktop.main.js:83
deliver @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:593
workbench.desktop.main.js:87 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot set properties of undefined (setting 'reactNativeVersionWarnings')
I @ workbench.desktop.main.js:87
$logExtensionHostMessage @ workbench.desktop.main.js:1734
_doInvokeHandler @ workbench.desktop.main.js:1734
_invokeHandler @ workbench.desktop.main.js:1734
_receiveRequest @ workbench.desktop.main.js:1734
_receiveOneMessage @ workbench.desktop.main.js:1734
(anonymous) @ workbench.desktop.main.js:1734
invoke @ workbench.desktop.main.js:83
deliver @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:545
_receiveMessage @ workbench.desktop.main.js:545
(anonymous) @ workbench.desktop.main.js:545
invoke @ workbench.desktop.main.js:83
deliver @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:83
acceptChunk @ workbench.desktop.main.js:545
(anonymous) @ workbench.desktop.main.js:545
E @ workbench.desktop.main.js:545
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
workbench.desktop.main.js:87 [Extension Host] stack trace: TypeError: Cannot set properties of undefined (setting 'reactNativeVersionWarnings')
    at Object.<anonymous> (/home/ldorigo/.vscode/extensions/msjsdiag.vscode-react-native-preview-2022.10.2021/dist/rn-extension.js:53:114626)
    at Generator.next (<anonymous>)
    at s (/home/ldorigo/.vscode/extensions/msjsdiag.vscode-react-native-preview-2022.10.2021/dist/rn-extension.js:53:113303)
I @ workbench.desktop.main.js:87
$logExtensionHostMessage @ workbench.desktop.main.js:1734
_doInvokeHandler @ workbench.desktop.main.js:1734
_invokeHandler @ workbench.desktop.main.js:1734
_receiveRequest @ workbench.desktop.main.js:1734
_receiveOneMessage @ workbench.desktop.main.js:1734
(anonymous) @ workbench.desktop.main.js:1734
invoke @ workbench.desktop.main.js:83
deliver @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:545
_receiveMessage @ workbench.desktop.main.js:545
(anonymous) @ workbench.desktop.main.js:545
invoke @ workbench.desktop.main.js:83
deliver @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:83
acceptChunk @ workbench.desktop.main.js:545
(anonymous) @ workbench.desktop.main.js:545
E @ workbench.desktop.main.js:545
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
workbench.desktop.main.js:608   ERR Cannot set properties of undefined (setting 'reactNativeVersionWarnings'): TypeError: Cannot set properties of undefined (setting 'reactNativeVersionWarnings')
    at Object.<anonymous> (/home/ldorigo/.vscode/extensions/msjsdiag.vscode-react-native-preview-2022.10.2021/dist/rn-extension.js:53:114626)
    at Generator.next (<anonymous>)
    at s (/home/ldorigo/.vscode/extensions/msjsdiag.vscode-react-native-preview-2022.10.2021/dist/rn-extension.js:53:113303)

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
It's an expo project, and `npx expo doctor` does not work in the latest sdk (46).
```

* `envinfo`:

```text
 System:
    OS: Linux 6.0 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 17.57 GB / 30.77 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
    Watchman: 20221016.020512.0 - /usr/bin/watchman
  Managers:
    Cargo: 1.64.0 - /usr/bin/cargo
    Maven: 3.8.6 - /usr/bin/mvn
    pip3: 22.3 - /usr/bin/pip3
    RubyGems: 3.3.23 - /usr/bin/gem
  Utilities:
    Bazel: 5.3.1 - /usr/bin/bazel
    CMake: 3.24.2 - /usr/bin/cmake
    Make: 4.3 - /usr/bin/make
    GCC: 12.2.0 - /usr/bin/gcc
    Git: 2.38.1 - /usr/bin/git
    Clang: 14.0.6 - /usr/bin/clang
    Ninja: 1.11.1 - /usr/bin/ninja
    FFmpeg: 5.1.2 - /usr/bin/ffmpeg
  Virtualization:
    Docker: 20.10.20 - /usr/bin/docker
  SDKs:
    Android SDK:
      API Levels: 31
      Build Tools: 31.0.0
      System Images: android-28 | Google APIs Intel x86 Atom, android-31 | Intel x86 Atom_64
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    VSCode: 1.72.2 - /usr/bin/code
    Vim: 9.0 - /usr/bin/vim
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
    Go: 1.19.2 - /usr/bin/go
    Java: 11.0.17 - /usr/bin/javac
    Perl: 5.36.0 - /usr/bin/perl
    Protoc: 3.21.7 - /usr/bin/protoc
    Python: 3.10.8 - /usr/bin/python
    Python3: 3.10.8 - /usr/bin/python3
    Ruby: 3.0.4 - /usr/bin/ruby
    Rust: 1.64.0 - /usr/bin/rustc
  Databases:
    MySQL: 10.9.3 (MariaDB) - /usr/bin/mysql
    PostgreSQL: 14.5 - /usr/bin/postgres
    SQLite: 3.39.4 - /usr/bin/sqlite3
  Browsers:
    Chromium: 106.0.5249.119

```

* React Native Tools extension version: 2022.10.2021
* Expo SDK version (if applicable): 46.0.0

**Comment by orefors** [comment]
I have the same problem on Windows 11, expo SDK 46 and vscode-react-native v. 1.10.0. Out of the box expo templated app, fresh install of VS Code. 

It changes the default app.json to:

{
  "expo": {
    "slug": "my-app",
    "name": "my-app",
    "sdkVersion": "46.0.0"
  },
  "name": "my-app"
}

**Comment by EzioLi01** [comment]
@ldorigo @orefors Thanks for reaching us, will have look on this and will update here if we have any progress.

**Comment by EzioLi01** [comment]
Extension should add missing field in `app.json` as normal, will investigate why it overwrites all content in `app.json`.

**Comment by EzioLi01** [comment]
It related to JSON5 parse function in reading app.json file. Working on fixing.

**Comment by EzioLi01** [comment]
Hey @ldorigo @orefors ,

This issue should be resolved. Please try to use [nightly preview version](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native-preview) for debugging and let me know if the issue still repro on new nightly version. Thanks!

**Comment by ldorigo** [comment]
Hey, thanks for the quick fix ! Seems to work fine on my end now.

**Comment by orefors** [comment]
Thank you, this working now

**Comment by lcsjunior** [comment]
@EzioLi01 Solved for me too.

**Comment by EzioLi01** [comment]
That's cool! Close this issue as resolved, please feel free to reach us if you have any issue need to help!
