### ISSUE TITLE
VSCode and react native: Error while executing command 'node_modules\.bin\react-native.cmd run-android --no-packager' (error code 101) (error code 303)

### ISSUE THREAD

**Issue by tekeroth-snapcode** [microsoft/vscode-react-native#1878]
This is the same issue as discussed here:
https://github.com/microsoft/vscode-react-native/issues/1169

But, I am not on Mac, but Win10 and I am not sure what I have to do to resolve the issue:

`An error occurred while launching the application. Error while executing command 'c:\Github\myproject\node_modules\.bin\react-native.cmd run-android --no-packager' (error code 101) (error code 303)`

_Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:_

I honestly am not sure how you can repro it, I am not a React Native dev really, just trying to debug an existing app. The app can be built, when I use this command:

```
npx react-native run-android --variant=MyFlavorDebug
```
which actually installs it on device. 

This also works, and produces APKs (from /android dir):
```
 ./gradlew assembleRelease
```

so, something is working, but not via VSCode.

## Expected behavior

I was expecting VSCode to be able to launch and attach a debugger.

## Debug output

<details>
<summary>Debug Console</summary>

```text

BUILD FAILED in 55s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 55s

    at makeError (c:\Github\myproject\node_modules\execa\index.js:174:9)
    at c:\Github\myproject\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (c:\Github\myproject\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (c:\Github\myproject\node_modules\@react-native-community\cli\build\index.js:192:9)


</details>

<details>
<summary>React Native output channel</summary>

```text

PASTE OUTPUT OF REACT-NATIVE OUTPUT CHANNEL (View -> Toggle Output -> Select React-Native in ListBox)

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

PASTE OUTPUT OF DEVELOPER TOOLS CONSOLE (Help -> Toggle Developer Tools -> Select Console tab)

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
PS C:\Github\alfaonlinev3> npx react-native doctor
Common
 ✓ Node.js
 ✓ yarn

Android
 ✓ JDK
 ✖ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME

Errors:   1
Warnings: 0

Usage
 › Press f to try to fix issues.
 › Press e to try to fix errors.
 › Press w to try to fix warnings.
 › Press Enter to exit.
```
Note: I have Android Studio installed, and it is working for Android native project. No idea why doctor complains or how to resolve it, other than downloading another copy of  Android studio?

* `envinfo`:

Visual Studio code: 1.73.1

```text

  System:
    OS: Windows 10 10.0.19044
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 5.01 GB / 31.95 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Managers:
    pip2: 19.2.3 - C:\Python27\Scripts\pip2.EXE
    pip3: 21.1.1 - C:\Python39\Scripts\pip3.EXE
  Utilities:
    Git: 2.34.1.
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
  IDEs:
    VSCode: 1.73.1 - C:\Program Files\Microsoft VS Code\bin\code.CMD
    Visual Studio: 17.3.32519.111 (Visual Studio Community 2022), 16.11.32106.194 (Visual Studio Community 2019)
  Languages:
    Java: 19.0.1
    Python: 3.9.5
  Databases:
    SQLite: 3.32.2 - C:\Users\wagge\AppData\Local\Android\Sdk\platform-tools\sqlite3.EXE
  Browsers:
    Chrome: 107.0.5304.121
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.56)
    Internet Explorer: 11.0.19041.1566


 IDEs:
    Android Studio: Not Found
    Visual Studio: 17.3.32519.111 (Visual Studio Community 2022), 16.11.32106.194 (Visual Studio Community 2019)
  Languages:
    Java: 19.0.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.4 => 0.67.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```
* React Native Tools extension version: ?
* Expo SDK version (if applicable): ?

**Comment by EzioLi01** [comment]
Hey @tekeroth-snapcode , thanks for reaching us. Is it possible to share the related RN application for the further investigation?

**Comment by tekeroth-snapcode** [comment]
Thanks for your quick answer.
Would a debug APK work to debug? I can't give out source code at this point.

Where do I add runArguments? The launch.json (auto-gen by vscode) is

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Launch Current File",
            "request": "launch",
            "mainClass": "${file}"
        },
        {
            "name": "Debug Android",
            "cwd": "${workspaceFolder}",
            "type": "reactnative",
            "request": "launch",
            "platform": "android",
            "isDynamic": true
        }
    ]
}

```

**Comment by EzioLi01** [comment]
@tekeroth-snapcode 

Please try to follow below steps:

1. Navigate to app root folder
2. Run `npx react-native start` to start Metro as below:
![image](https://user-images.githubusercontent.com/19662219/204703205-8e95dc38-4110-466b-9769-dff0a317b13e.png)
3. Run `npx react-native run-android` or `npx react-native run-android --variant=MyFlavorDebug`
4. Check if app can be open in simulator successfully
![image](https://user-images.githubusercontent.com/19662219/204703494-658ba6dc-7cb2-4c50-b45b-b44317935a22.png)

If your app cannot open using react-native command, the app maybe have some problems in development. 
It's good if you can provide the application repo for investigation, or maybe you can contact to app owner for the help.

**Comment by EzioLi01** [comment]
Hey @tekeroth-snapcode, do you have chance to have a try as above? Also, could you please help to check if your app had `local.properties` file in `root/android` path?

**Comment by tekeroth-snapcode** [comment]
I have not, yet.

The app wont start automatically, but if I start it from the phone i am able to attach to "The packager" manually.

I will take a look on your suggstion tonight

**Comment by tekeroth-snapcode** [comment]
Sorry, I realize I am not sure how to start a simulator from cmd or VSCode, I always run on real device...

**Comment by EzioLi01** [comment]
> Sorry, I realize I am not sure how to start a simulator from cmd or VSCode, I always run on real device...

Maybe you can look into this [doc](https://reactnative.dev/docs/environment-setup). 

You can try it both on device and simulator,
1. If you have APK file, install app
2. Open RN app
3. Press Ctrl+M open dev menu
![image](https://user-images.githubusercontent.com/19662219/205200794-50cb7f3d-eb42-4a4b-841e-3714965a3c84.png)
4. Click change bundle location, get address
5. Open project in VSCode, start RN packager
![image](https://user-images.githubusercontent.com/19662219/205200994-49723ccb-9ac6-488f-acfe-88430e9e8b4b.png)
6. Add config like this, set host address and port you get in dev menu, and start debugging
        {
            "name": "Attach to Hermes application - Experimental",
            "request": "attach",
            "type": "reactnativedirect",
            "cwd": "${workspaceFolder}",
            "address": "localhost",
            "port": 8081
        },

**Comment by tekeroth-snapcode** [comment]
I really appreciate your time and input! I can get the debugger to work, it was messy, but that part is working (as far as it goes with react native).
I will check and see if simulator for ios can be done, somehow...

**Comment by EzioLi01** [comment]
@tekeroth-snapcode Great to see it works! You can have a try with simulator and I will keep this issue here.
If you do not have further updates in coming days, I will close issue as resolved. Thank you!

Any other issues please reach us anytime.

**Comment by kaikrmen** [comment]
@EzioLi01 this save my life, thanks!!!!
