### ISSUE TITLE
[Bug] Debugging in exponent fails 

### ISSUE THREAD

**Issue by ldorigo** [microsoft/vscode-react-native#1883]
# 🐛 What is the bug? How can we reproduce it?

I try to run "debug in exponent" with the attached configuration files and directory structure.  

[dirstructure.txt](https://github.com/microsoft/vscode-react-native/files/10140600/dirstructure.txt)

<details>
<summary> app.json </summary>

```text
{
  "expo": {
    "name": "pybooks",
    "slug": "pybooks",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.pybooks.pybooks"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      },
      "jsEngine": "hermes",
      "package": "com.pybooks.pybooks"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": [],
    "extra": {
      "eas": {
        "projectId": "66d0f466-d5ae-439d-ba37-985efa170d96"
      }
    },
    "sdkVersion": "47.0.0",
    "entryPoint": ".vscode/exponentIndex.js"
  },
  "name": "pybooks"
}
```
</details>

<details>
<summary> package.json </summary>

```text
{
  "name": "pybooks",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "cache:clear": "watchman watch-del-all && rm -rf node_modules && rm yarn.lock && yarn cache clean && yarn install && rm -rf /tmp/metro-*"
  },
  "dependencies": {
    "@babel/preset-env": "^7.19.4",
    "@expo/webpack-config": "^0.17.2",
    "@rneui/base": "^4.0.0-rc.6",
    "@rneui/themed": "^4.0.0-rc.6",
    "easy-peasy": "^5.1.0",
    "expo": "^47.0.0",
    "expo-camera": "~13.1.0",
    "expo-dev-client": "~2.0.1",
    "expo-file-system": "~15.1.1",
    "expo-image-picker": "~14.0.2",
    "expo-modules-autolinking": "^1.0.0",
    "expo-permissions": "~14.0.0",
    "expo-status-bar": "~1.4.2",
    "global": "^4.4.0",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-native": "0.70.5",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-reanimated": "~2.12.0",
    "react-native-safe-area-context": "4.4.1",
    "react-native-svg": "13.4.0",
    "react-native-transformable-image": "^0.0.18",
    "react-native-vector-icons": "^9.2.0",
    "react-native-web": "~0.18.7"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3",
    "@types/react": "~18.0.24",
    "@types/react-native": "~0.70.6",
    "@typescript-eslint/eslint-plugin": "^5.40.1",
    "@typescript-eslint/parser": "^5.40.1",
    "eslint": "^8.25.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.31.10",
    "eslint-plugin-react-hooks": "^4.6.0",
    "prettier": "^2.7.1",
    "typescript": "^4.6.3"
  },
  "private": true
}
```
</details>

When I scan the QR code and try to launch the app, it fails with the error below.
## Expected behavior

Being able to debug in exponent.

## Debug output

<details>
<summary>Debug Console</summary>

```text

Launching the application
Getting app.json path: /home/ldorigo/Dropbox/projects/pybooks_app/app.json
Start parsing .json file...
Attaching to the application
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application

```
</details>

<details>
<summary>React Native output channel</summary>

```text

Debug] Begin to activate...

[Debug] Extension version: 2022.12.120

[Debug] Projects found: 1

[Debug] Add project: /home/ldorigo/Dropbox/projects/pybooks_app

[Debug] React Native version: 0.70.5

[Debug] Run command: selectAndInsertDebugConfiguration

[Info] Making sure your project uses the correct dependencies for Expo. This may take a while...

[Debug] Getting xdl dependency.

[Debug] Getting @expo/metro-config dependency.

[Debug] Dependency xdl is present with another version. Retry after install this package with specific version...

[Debug] Dependency @expo/metro-config is present with another version. Retry after install this package with specific version...

.............................................................
[Debug] Getting xdl dependency.

[Debug] Getting @expo/metro-config dependency.

Checking if this is an Expo app.
...[Debug] 'expo' package is found in 'dependencies' section of package.json

.[Debug] 'expo' package is found in 'dependencies' section of package.json

.
....[Debug] 'expo' package is found in 'dependencies' section of package.json

[Info] Starting Packager

[Debug] Executing command: /home/ldorigo/Dropbox/projects/pybooks_app/node_modules/.bin/react-native start --port 8081


                        ▒▒▓▓▓▓▒▒
                     ▒▓▓▓▒▒░░▒▒▓▓▓▒
                  ▒▓▓▓▓░░░▒▒▒▒░░░▓▓▓▓▒
                 ▓▓▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▓▓
                 ▓▓░░░░░▒▓▓▓▓▓▓▒░░░░░▓▓
                 ▓▓░░▓▓▒░░░▒▒░░░▒▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▒▒▒▒▓▓▓▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▓▓▓▓▓▓▓▓▒░░▓▓
                 ▓▓▒░░▒▒▓▓▓▓▓▓▓▓▒░░░▒▓▓
                  ▒▓▓▓▒░░░▒▓▓▒░░░▒▓▓▓▒
                     ▒▓▓▓▒░░░░▒▓▓▓▒
                        ▒▒▓▓▓▓▒▒


                Welcome to Metro v0.72.3
              Fast - Scalable - Integrated


[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] Building and running application.

No issue with doctor-config-json-not-read
No issue with doctor-watchman-version
No issue with doctor-problem-checking-watchman-version
No issue with doctor-unversioned
No issue with doctor-versions-endpoint-failed
No issue with doctor-invalid-sdk-version
No issue with doctor-schema-validation
No issue with doctor-validate-asset-fields
No issue with doctor-schema-validation-exception
No issue with doctor-no-react-native-in-package-json
No issue with doctor-legacy-async-storage
No issue with doctor-not-using-expo-fork
No issue with doctor-invalid-version-of-react-native
No issue with doctor-react-native-not-installed
[Info] Enable JS Debugging

No issue with doctor-config-json-not-read
No issue with doctor-watchman-version
No issue with doctor-problem-checking-watchman-version
No issue with doctor-unversioned
No issue with doctor-versions-endpoint-failed
No issue with doctor-invalid-sdk-version
No issue with doctor-schema-validation
No issue with doctor-validate-asset-fields
No issue with doctor-schema-validation-exception
No issue with doctor-no-react-native-in-package-json
No issue with doctor-legacy-async-storage
No issue with doctor-not-using-expo-fork
No issue with doctor-invalid-version-of-react-native
No issue with doctor-react-native-not-installed
 BUNDLE  .vscode/exponentIndex.js 

error: Error: Unable to resolve module /home/ldorigo/Dropbox/projects/pybooks_app/node_modules/react from /data/Dropbox/projects/pybooks_app/.vscode/exponentIndex.js: 

None of these files exist:
  * ../../../../home/ldorigo/Dropbox/projects/pybooks_app/node_modules/react(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  * ../../../../home/ldorigo/Dropbox/projects/pybooks_app/node_modules/react/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  1 | // This file is automatically generated by VS Code
  2 | // Please do not modify it manually. All changes will be lost.
> 3 | var React = require('/home/ldorigo/Dropbox/projects/pybooks_app/node_modules/react');
    |                      ^
  4 | var { Component } = React;
  5 | var ReactNative = require('/home/ldorigo/Dropbox/projects/pybooks_app/node_modules/react-native');
  6 | var { AppRegistry } = ReactNative;
    at ModuleResolver.resolveDependency (/data/Dropbox/projects/pybooks_app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:152:15)
    at DependencyGraph.resolveDependency (/data/Dropbox/projects/pybooks_app/node_modules/metro/src/node-haste/DependencyGraph.js:264:43)
    at Object.resolve (/data/Dropbox/projects/pybooks_app/node_modules/metro/src/lib/transformHelpers.js:170:21)
    at resolveDependencies (/data/Dropbox/projects/pybooks_app/node_modules/metro/src/DeltaBundler/graphOperations.js:466:33)
    at processModule (/data/Dropbox/projects/pybooks_app/node_modules/metro/src/DeltaBundler/graphOperations.js:232:31)
    at async traverseDependenciesForSingleFile (/data/Dropbox/projects/pybooks_app/node_modules/metro/src/DeltaBundler/graphOperations.js:221:3)
    at async Promise.all (index 0)
    at async initialTraverseDependencies (/data/Dropbox/projects/pybooks_app/node_modules/metro/src/DeltaBundler/graphOperations.js:204:3)
    at async DeltaCalculator._getChangedDependencies (/data/Dropbox/projects/pybooks_app/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:208:25)
    at async DeltaCalculator.getDelta (/data/Dropbox/projects/pybooks_app/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:90:16)


```
</details>

<details>
<summary>Developer Tools console</summary>

```text

PASTE OUTPUT OF DEVELOPER TOOLS CONSOLE (Help -> Toggle Developer Tools -> Select Console tab)

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
Expected package @expo/config-plugins@^5.0.2
Found invalid:
  @expo/config-plugins@5.0.1
  (for more info, run: npm why @expo/config-plugins)
/home/ldorigo/.yarn/bin/expo-cli doctor  34,24s user 2,24s system 120% cpu 30,282 total  
```
 (not sure about the above, when I do `yarn why @expo/config-plugins it only shows 5.0.4)

* `envinfo`:

```text
yarn run v1.22.19
$ /data/Dropbox/projects/pybooks_app/node_modules/.bin/envinfo

  System:
    OS: Linux 6.0 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 9.15 GB / 30.77 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.0 - /tmp/yarn--1669980163352-0.4397090008216815/node
    Yarn: 1.22.19 - /tmp/yarn--1669980163352-0.4397090008216815/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
    Watchman: 20221016.020512.0 - /usr/bin/watchman
  Managers:
    Cargo: 1.65.0 - /usr/bin/cargo
    Composer: 2.4.4 - /usr/bin/composer
    Maven: 3.8.6 - /usr/bin/mvn
    pip3: 22.3.1 - /usr/bin/pip3
    RubyGems: 3.3.25 - /usr/bin/gem
  Utilities:
    Bazel: 5.3.2 - /usr/bin/bazel
    CMake: 3.25.0 - /usr/bin/cmake
    Make: 4.3 - /usr/bin/make
    GCC: 12.2.0 - /usr/bin/gcc
    Git: 2.38.1 - /usr/bin/git
    Clang: 14.0.6 - /usr/bin/clang
    Ninja: 1.11.1 - /usr/bin/ninja
    FFmpeg: 5.1.2 - /usr/bin/ffmpeg
  Virtualization:
    Docker: 20.10.21 - /usr/bin/docker
  SDKs:
    Android SDK:
      API Levels: 31, 33
      Build Tools: 30.0.3, 31.0.0
      System Images: android-28 | Google APIs Intel x86 Atom, android-31 | Intel x86 Atom_64
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    VSCode: 1.73.1 - /usr/bin/code
    Vim: 9.0 - /usr/bin/vim
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
    Go: 1.19.3 - /usr/bin/go
    Java: 11.0.17 - /usr/bin/javac
    Perl: 5.36.0 - /usr/bin/perl
    PHP: 8.1.13 - /usr/bin/php
    Protoc: 3.21.9 - /usr/bin/protoc
    Python: 3.10.8 - /usr/bin/python
    Python3: 3.10.8 - /usr/bin/python3
    Ruby: 3.0.4 - /usr/bin/ruby
    Rust: 1.65.0 - /usr/bin/rustc
  Databases:
    MySQL: 10.9.4 (MariaDB) - /usr/bin/mysql
    PostgreSQL: 14.6 - /usr/bin/postgres
    SQLite: 3.40.0 - /usr/bin/sqlite3
  Browsers:
    Chromium: 107.0.5304.121

Done in 3.48s.

```

* React Native Tools extension version: nightly
* Expo SDK version (if applicable): 47

**Comment by ldorigo** [comment]
Note that despite what the error says, react does exist in node_modules as you can see from the directory structure

**Comment by EzioLi01** [comment]
Hey @ldorigo , could you please try to use `yarn` or `npm install` to module again? Also could you please try to use `expo start` to launch app and does it working fine?

**Comment by ldorigo** [comment]
Hi, I already re-installed everything (deleted node-modules directory). Expo start works but ONLY if I remove the line that gets automatically added to app.json by your extension (` "entryPoint": ".vscode/exponentIndex.js"`) - otherwise I get the same error.

**Comment by EzioLi01** [comment]
@ldorigo Could you please try to delete `.vscode/exponentIndex.js` file and `"entryPoint": ".vscode/exponentIndex.js"` in app.json and try to debug app again?
Also I saw your app structure that you have build your app on each platform, could you please to use `react native debugger config` to see if it works?
        {
            "name": "Debug Android Hermes - Experimental",
            "request": "launch",
            "type": "reactnativedirect",
            "cwd": "${workspaceFolder}",
            "platform": "android"
        }

**Comment by ldorigo** [comment]
I understand that this would be much easier to troubleshoot if you could run the code, but I'm not confident enough about how everything is structured to know that there aren't some "secret" stuff inside the code (like `eas` tokens?) so I'd rather avoid sharing publicly here. If you give me an e-mail I can send you a zip file with the exact contents of the directory I'm running the code from?

**Comment by EzioLi01** [comment]
Hey, do you have any updates?

**Comment by EzioLi01** [comment]
> @ldorigo Please send the file to [this](eziolyk3@outlook.com) address, thank you!

Hey, do you have any updates?

**Comment by EzioLi01** [comment]
Hey @ldorigo , do you have any updates on this?

**Comment by EzioLi01** [comment]
Close this issue since it had no updates so far, please reopen this issue if you have any details on it. Thank you!
