### ISSUE TITLE
[Bug] Breakpoint location changes after debugger attaches with latest VSCode version (1.78)

### ISSUE THREAD

**Issue by shivam124** [microsoft/vscode-react-native#1968]
Breakpoint location changes with latest VSCode version (1.78). If I put a breakpoint in App.tsx then it changes to require.js file once the debugger is attached.

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:

1. Launch android emulator
2.  adb reverse tcp:8081 tcp:8081
3. npx react-native@latest init AwesomeProject
4. Open project in VSCode (1.78)
5. Put a breakpoint at line 62 in App.tsx
6. Then attach "reactnativedirect" debugger

https://github.com/microsoft/vscode-react-native/assets/12963703/b70ba679-f477-4c81-9cc3-fddb96d23fe8

## Expected behavior
Breakpoint location to be line 62 in App.tsx

What were you expecting to happen?
Breakpoint location not changed 
## Debug output

<details>
<summary>Debug Console</summary>

```text

Attaching to the application
Connecting to 8081 port

```
</details>

<details>
<summary>React Native output channel</summary>

```text

[Debug] Begin to activate...

[Debug] Extension version: 1.11.0

[Debug] Projects found: 1

[Debug] Add project: c:\Users\ASUS\AwesomeProject

[Debug] React Native version: 0.71.8

[Info] Need to check main file and entry point of open module, will setup and write new content if they're not existing. Path: c:\Users\ASUS\AwesomeProject\node_modules\open

[Info] Find open-main.js and entry in open module, skip setup...

[Info] Starting Packager

[Debug] Executing command: c:\Users\ASUS\AwesomeProject\node_modules\.bin\react-native.cmd start --port 8081


                        ▒▒▓▓▓▓▒▒
                     ▒▓▓▓▒▒░░▒▒▓▓▓▒
                  ▒▓▓▓▓░░░▒▒▒▒░░░▓▓▓▓▒
                 ▓▓▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▓▓
                 ▓▓░░░░░▒▓▓▓▓▓▓▒░░░░░▓▓
                 ▓▓░░▓▓▒░░░▒▒░░░▒▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▒▒▒▒▓▓▓▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▓▓▓▓▓▓▓▓▒░░▓▓
                 ▓▓▒░░▒▒▓▓▓▓▓▓▓▓▒░░░▒▓▓
                  ▒▓▓▓▒░░░▒▓▓▒░░░▒▓▓▓▒
                     ▒▓▓▓▒░░░░▒▓▓▓▒
                        ▒▒▓▓▓▓▒▒


                Welcome to Metro v0.73.9
              Fast - Scalable - Integrated


[Info] Packager started.

 MAP  ./index.js 

 MAP  ./index.js 

 BUNDLE  ./index.js 

 LOG  Running "AwesomeProject" with {"rootTag":31}
 MAP  ./index.js 

 MAP  ./index.js 

 MAP  ./index.js 



```
</details>

<details>
<summary>Developer Tools console</summary>

```text

 WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-selfhost-test-provider' wants API proposal 'testContinuousRun' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:431  WARN Settings pattern "application.*" doesn't match any settings
log.ts:431  WARN SettingsEditor2: Settings not included in settingsLayout.ts: interactiveEditor.editMode, accessibility.verbosity.diff-editor, accessibility.verbosity.terminal
log.ts:441   ERR [Extension Host] (node:12932) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:12932) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
I @ console.ts:137
log.ts:421  INFO [perf] Render performance baseline is 61ms
log.ts:431  WARN Settings pattern "application.*" doesn't match any settings
mainThreadExtensionService.ts:80 [msjsdiag.vscode-react-native]s.tmpDir is not a function
$onExtensionRuntimeError @ mainThreadExtensionService.ts:80
mainThreadExtensionService.ts:81 TypeError: s.tmpDir is not a function
	at e._sendFirstFileOnDisk (c:\Users\ASUS\.vscode\extensions\msjsdiag.vscode-react-native-1.11.0\dist\rn-extension.js:1:25325)
	at Timeout._onTimeout (c:\Users\ASUS\.vscode\extensions\msjsdiag.vscode-react-native-1.11.0\dist\rn-extension.js:1:24129)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
console.ts:137 [Extension Host] process Array(2)
console.ts:137 [Extension Host] Couldn't stop monitoring logcat: Cannot read properties of undefined (reading 'dispose')
I @ console.ts:137
console.ts:137 [Extension Host] process Array(0)
console.ts:137 [Extension Host] Couldn't stop monitoring logcat: Cannot read properties of undefined (reading 'dispose')
I @ console.ts:137
mainThreadExtensionService.ts:80 [msjsdiag.vscode-react-native]s.tmpDir is not a function
$onExtensionRuntimeError @ mainThreadExtensionService.ts:80
mainThreadExtensionService.ts:81 TypeError: s.tmpDir is not a function
	at e._sendFirstFileOnDisk (c:\Users\ASUS\.vscode\extensions\msjsdiag.vscode-react-native-1.11.0\dist\rn-extension.js:1:25325)
	at Timeout._onTimeout (c:\Users\ASUS\.vscode\extensions\msjsdiag.vscode-react-native-1.11.0\dist\rn-extension.js:1:24129)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
mainThreadExtensionService.ts:80 [msjsdiag.vscode-react-native]s.tmpDir is not a function
$onExtensionRuntimeError @ mainThreadExtensionService.ts:80
mainThreadExtensionService.ts:81 TypeError: s.tmpDir is not a function
	at e._sendFirstFileOnDisk (c:\Users\ASUS\.vscode\extensions\msjsdiag.vscode-react-native-1.11.0\dist\rn-extension.js:1:25325)
	at Timeout._onTimeout (c:\Users\ASUS\.vscode\extensions\msjsdiag.vscode-react-native-1.11.0\dist\rn-extension.js:1:24129)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
console.ts:137 [Extension Host] process Array(0)
console.ts:137 [Extension Host] Couldn't stop monitoring logcat: Cannot read properties of undefined (reading 'dispose')
I @ console.ts:137
console.ts:137 [Extension Host] process Array(1)

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
C:\Users\ASUS\AwesomeProject>npx react-native doctor
Common
 ✓ Node.js
 ✓ yarn

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: 30.0.3
   - Version supported: 33.0.0
 ✓ ANDROID_HOME

Errors:   1
Warnings: 0

Usage
 › Press f to try to fix issues.
 › Press e to try to fix errors.
 › Press w to try to fix warnings.
 › Press Enter to exit.
```

* `envinfo`:

```text
C:\Users\ASUS\AwesomeProject>npx envinfo

  System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 AMD Ryzen 7 4700U with Radeon Graphics
    Memory: 838.41 MB / 7.42 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Managers:
    pip3: 21.2.3 - ~\AppData\Local\Programs\Python\Python310\Scripts\pip3.EXE
  Utilities:
    Git: 2.31.1. - C:\Program Files\Git\cmd\git.EXE
  SDKs:
    Android SDK:
      API Levels: 30, 33
      Build Tools: 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    VSCode: 1.56.2 - C:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE
    Java: 11.0.18 - C:\Program Files\Microsoft\jdk-11.0.18.10-hotspot\bin\javac.EXE
    Python: 3.10.0 - C:\Users\ASUS\AppData\Local\Programs\Python\Python310\python.EXE
  Databases:
    SQLite: 3.32.2 - C:\Users\ASUS\AppData\Local\Android\Sdk\platform-tools\sqlite3.EXE
  Browsers:
    Edge: Spartan (44.22621.1265.0), Chromium (114.0.1823.37)
    Internet Explorer: 11.0.22621.1

```

* React Native Tools extension version: VERSION
* Expo SDK version (if applicable): VERSION

**Comment by EzioLi01** [comment]
Thanks @shivam124 for reaching us, we also notice this issue, and in investigating. It only happened if you set breakpoint at first and run debugging, but not repro if attach and then add breakpoint. I think it should related to some changes or issues on js-debug V1.78.0. Will add comment here if we have any update.

**Comment by EzioLi01** [comment]
This issue is occurred from js-debug nightly version V2023.4.27, will talk with related team to get some info soon.

**Comment by EzioLi01** [comment]
Confirm with js-debug team, it should a regression bug on 1.78.0, will update fix information when I get response from js-debug team.

**Comment by EzioLi01** [comment]
Update: this issue will be fixed on next js-debug release. Here is a temporary workaround for the reference - using js-debug nightly version.

1. Open the extensions view (ctrl+shift+x) and search for @builtin @id:ms-vscode.js-debug
2. Right click on the JavaScript Debugger extension and Disable it.
3. Search for @id:ms-vscode.js-debug-nightly in the extensions view.
4. Install that extension.
5. Uninstall latest nightly version, select install another version: using v2023.4.1317.

**Comment by EzioLi01** [comment]
Close this issue, please comment or discuss the related issue on above issue, thank you!
