### ISSUE TITLE
[Feature] Ability to exclude workspace projects from extension

### ISSUE THREAD

**Issue by jsg2021** [microsoft/vscode-react-native#2054]
# 🚀 Feature request

What do you want to be added?
The ability to add a block list to my workspace that prevents libraries from showing up in the launch packager menu

## What scenarios will this solve?
I have several projects in my workspace and only one of them is the application, the rest are support libraries... a few of them have a storybook/test harness app to develop independently of the main app... 

What will this allow you to do? Will this benefit other developers?
It will save me time from accidentally starting the wrong packager without having to drop the project from my workspace.

**Comment by EzioLi01** [comment]
Hey @jsg2021, thanks for reaching us, will investigate it soon, it's possible to provide a demo to us for your request, it can help us quickly evaluate and test scenario in development. Thank you!

**Comment by EzioLi01** [comment]
Thanks @jsg2021 sharing details, will investigate on this.

**Comment by EzioLi01** [comment]
Hey @jsg2021 , could you please check if this `.vsix` can help you in this scenario.
[vscode-react-native-1.12.1.zip](https://github.com/microsoft/vscode-react-native/files/12923738/vscode-react-native-1.12.1.zip)

Follow below steps:
1. Unzip and install extension with .vsix
2. Open workspace settings json
3. Add 
```	"settings": {
		"react-native.workspace.exclude": [
			"Folder Name You Want To Exclude"
		]
	}

```
5. Execute RN packager

Note: Since the folder selection list is not handled by extension rather than vscode, we must set exclude folder when extesnsion is not activated. If you add exclude folder after extension activating, you must re-activate you extension or reopen your vscode.

**Comment by jsg2021** [comment]
This vsix doesn't load 

[Error] Failed to activate the React Native Tools extension (error code 702)

```
2023-10-17 11:36:33.900 [error] SyntaxError: Expected double-quoted property name in JSON at position 500
	at JSON.parse (<anonymous>)
	at p.<anonymous> (/Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:284:68992)
	at Generator.next (<anonymous>)
	at /Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:284:65779
	at new Promise (<anonymous>)
	at n (/Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:284:65524)
	at p.getWorkspaceFileExcludeFolder (/Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:284:68876)
	at /Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:284:11433
	at Generator.next (<anonymous>)
	at /Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:284:10416
	at new Promise (<anonymous>)
	at n (/Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:284:10161)
	at U (/Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:284:11368)
	at /Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:284:16370
	at Array.forEach (<anonymous>)
	at /Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:284:16350
	at Generator.next (<anonymous>)
	at /Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:284:10416
	at new Promise (<anonymous>)
	at n (/Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:284:10161)
	at /Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:284:14582
	at /Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:21:465508
	at t.TelemetryGenerator.<anonymous> (/Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:21:461633)
	at Generator.next (<anonymous>)
	at /Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:21:460722
	at new Promise (<anonymous>)
	at n (/Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:21:460467)
	at t.TelemetryGenerator.time (/Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:21:461562)
	at u.generate (/Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:21:465495)
	at t.EntryPointHandler.runFunctionWExtProps (/Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:21:401489)
	at t.EntryPointHandler.runFunction (/Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:21:401373)
	at t.EntryPointHandler.runApp (/Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:21:401568)
	at /Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:284:14486
	at Generator.next (<anonymous>)
	at /Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:284:10416
	at new Promise (<anonymous>)
	at n (/Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:284:10161)
	at t.activate (/Users/jonathan/.vscode/extensions/msjsdiag.vscode-react-native-1.12.1/dist/rn-extension.js:284:13161)
	at q.ib (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:136:13192)
	at q.hb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:136:12914)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:136:11039
	at async v.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:6205)
	at async v.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:6168)
	at async v.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:5625)
```

**Comment by EzioLi01** [comment]
Verified it's working well on my side, according to the message, could you please check if you are using some extra comma in your json file? Thanks!

**Comment by jsg2021** [comment]
I tried again... it worked :)  Must have had a weird cached state or something.

**Comment by EzioLi01** [comment]
Cool, you can use this `.vsix` so far, this feature will be released in next prod version.

**Comment by EzioLi01** [comment]
Feature is completed, thanks for the great suggestion!
