### ISSUE TITLE
Debugging experience suddenly stops

### ISSUE THREAD

**Issue by gilesbradshaw** [Microsoft/vscode-react-native#209]
## Actual Behavior

Was all working fine then suddenly nothing happens anymore when I press play.  Have tried restarting the Mac.

My app still works fine when I run it in Xcode - but debugs now in chrome developer tools rather than VSCode

## Expected Behavior

should be set ok and hit

## Software versions

- React-Native VS Code extension version: 0.1.3
- VSCode version:  0.10.11
- OS platform and version:  mac os el capitain
- React Native version: 0.22.2

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console): 

````
node --debug-brk=12935 launchReactNative.js ios 9090 'iPhone 5s' 
Debugger listening on port 12935
````

- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox): 
nothing

- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab): 

````

Cannot read property 'languageIds' of undefined: TypeError: Cannot read property 'languageIds' of undefined
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:98:5560
    at Array.forEach (native)
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:98:5037
    at Array.forEach (native)
    at e._handler (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:98:5009)
    at Object.listener (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:58:28803)
    at e._triggerPointListener (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:58:30786)
    at e.registerPlugins (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:58:31386)
    at t.$onPluginHostReady (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:71:21766)
    at t.e.handle (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:71:29651)e.onUnexpectedError @ shell.ts:480
index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:26 [uncaught exception]: TypeError: Cannot convert object to primitive valueonError @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:26
index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:29 TypeError: Cannot convert object to primitive value
    at new Error (native)
    at Client.trackException (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/applicationinsights/Library/Client.js:67:25)
    at e.logException (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:30848)
    at e.log (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:112:10791)
    at t.handleEvent (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:68:2959)
    at t.e.publicLog (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:68:144)
    at t.publicLog (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:68:5186)
    at t.e.flushErrorBuffer (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:67:30198)
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:67:30058onError @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:29
/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/applicationinsights/Librar…:67 Uncaught TypeError: Cannot convert object to primitive value
shell.ts:480Internal module zlib.js not found.: Error: Internal module zlib.js not found.
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:78:182
    at Object.p [as _notify] (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:17247)
    at Object.n.undefined.F.enter (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:20575)
    at n.undefined.t.Class.define._run (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:21896)
    at n.undefined.t.Class.define._error (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:21413)
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:29436
    at t.dispatch (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:30522)
    at t.handleData (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:30032)
    at Socket.<anonymous> (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:29302)
    at emitOne (events.js:77:13)e.onUnexpectedError @ shell.ts:480
winjs.base.js:47WARNING: Promise with no error callback:8
winjs.base.js:48Object
shell.ts:480Internal module zlib.js not found.: Error: Internal module zlib.js not found.
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:78:182
    at Object.p [as _notify] (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:17247)
    at Object.n.undefined.F.enter (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:20575)
    at n.undefined.t.Class.define._run (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:21896)
    at n.undefined.t.Class.define._error (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:21413)
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:29436
    at t.dispatch (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:30522)
    at t.handleData (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:30032)
    at Socket.<anonymous> (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:29302)
    at emitOne (events.js:77:13)e.onUnexpectedError @ shell.ts:480
winjs.base.js:47WARNING: Promise with no error callback:11
winjs.base.js:48Object
shell.ts:480Internal module zlib.js not found.: Error: Internal module zlib.js not found.
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:78:182
    at Object.p [as _notify] (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:17247)
    at Object.n.undefined.F.enter (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:20575)
    at n.undefined.t.Class.define._run (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:21896)
    at n.undefined.t.Class.define._error (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:21413)
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:29436
    at t.dispatch (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:30522)
    at t.handleData (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:30032)
    at Socket.<anonymous> (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:29302)
    at emitOne (events.js:77:13)e.onUnexpectedError @ shell.ts:480
winjs.base.js:47WARNING: Promise with no error callback:14
winjs.base.js:48Object

````

**Comment by gilesbradshaw** [comment]
I think that zlib.js file is the souce of the issue - the last thing that happened was I had a break on an exception in that file.  Could I have accidentally edited it?  Perhaps I need a re install...

**Comment by gilesbradshaw** [comment]
I seem to have fixed this by re installing zlib

```` 
sudo npm i zlib
````

I am guessing it got corrupted I remember an exception in that file so maybe I hit a key and edited it by mistake ...

**Comment by digeff** [comment]
@gilesbradshaw I'm happy you were able to resolve your issue! Thank you for reporting this!

**Comment by MSLaguana** [comment]
Where was this zlib which was corrupted? Was it part of your vscode install, our extension, or your app?

**Comment by gilesbradshaw** [comment]
I'm only guessing it was corrupted but I did npm i zlib so I assume it was in my project ie node_modules
