### ISSUE TITLE
[Feature] Support .cjs metro config file

### ISSUE THREAD

**Issue by TheWirv** [microsoft/vscode-react-native#2101]
# 🐛 What is the bug? How can we reproduce it?

Hi, with this extension it is not possible to launch an app when the Metro config is named anything other than `metro.config.js`. When trying to launch with a config file named `metro.config.cjs`, this error message appears:

```text
An error occurred while launching the application. ENOENT: no such file or directory, open 'C:\{path-to-project}\metro.config.js' (error code 303)
```

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:

1. Rename Metro config file to `metro.config.cjs`
2. Launch an app via F5

## Expected behavior

The app launches properly.

## Debug output

<details>
<summary>Debug Console</summary>

```text
Debug console is empty.
```
</details>

<details>
<summary>React Native output channel</summary>

```text
No output.
```
</details>

<details>
<summary>Developer Tools console</summary>

```text
[Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'getPackager')
w @ console.ts:137
console.ts:137 [Extension Host] stack trace: TypeError: Cannot read properties of undefined (reading 'getPackager')
	at C.<anonymous> (c:\Users\Marcel\.vscode\extensions\msjsdiag.vscode-react-native-1.12.3\dist\rn-extension.js:21:467347)
	at Generator.next (<anonymous>)
	at c:\Users\Marcel\.vscode\extensions\msjsdiag.vscode-react-native-1.12.3\dist\rn-extension.js:21:461973
	at new Promise (<anonymous>)
	at n (c:\Users\Marcel\.vscode\extensions\msjsdiag.vscode-react-native-1.12.3\dist\rn-extension.js:21:461718)
	at C.disconnectRequest (c:\Users\Marcel\.vscode\extensions\msjsdiag.vscode-react-native-1.12.3\dist\rn-extension.js:21:467104)
	at C.dispatchRequest (c:\Users\Marcel\.vscode\extensions\msjsdiag.vscode-react-native-1.12.3\dist\rn-extension.js:1:5426)
	at C.dispatchRequest (c:\Users\Marcel\.vscode\extensions\msjsdiag.vscode-react-native-1.12.3\dist\rn-extension.js:1:18045)
	at C.handleMessage (c:\Users\Marcel\.vscode\extensions\msjsdiag.vscode-react-native-1.12.3\dist\rn-extension.js:1:22697)
	at C._handleData (c:\Users\Marcel\.vscode\extensions\msjsdiag.vscode-react-native-1.12.3\dist\rn-extension.js:1:24416)
	at Socket.<anonymous> (c:\Users\Marcel\.vscode\extensions\msjsdiag.vscode-react-native-1.12.3\dist\rn-extension.js:1:23015)
	at Socket.emit (node:events:513:28)
	at Socket.emit (node:domain:489:12)
	at addChunk (node:internal/streams/readable:324:12)
	at readableAddChunk (node:internal/streams/readable:297:9)
	at Readable.push (node:internal/streams/readable:234:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
w @ console.ts:137
mainThreadExtensionService.ts:81 [msjsdiag.vscode-react-native]Cannot read properties of undefined (reading 'getPackager')
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
mainThreadExtensionService.ts:82 TypeError: Cannot read properties of undefined (reading 'getPackager')
	at C.<anonymous> (c:\Users\Marcel\.vscode\extensions\msjsdiag.vscode-react-native-1.12.3\dist\rn-extension.js:21:467347)
	at Generator.next (<anonymous>)
	at c:\Users\Marcel\.vscode\extensions\msjsdiag.vscode-react-native-1.12.3\dist\rn-extension.js:21:461973
	at new Promise (<anonymous>)
	at n (c:\Users\Marcel\.vscode\extensions\msjsdiag.vscode-react-native-1.12.3\dist\rn-extension.js:21:461718)
	at C.disconnectRequest (c:\Users\Marcel\.vscode\extensions\msjsdiag.vscode-react-native-1.12.3\dist\rn-extension.js:21:467104)
	at C.dispatchRequest (c:\Users\Marcel\.vscode\extensions\msjsdiag.vscode-react-native-1.12.3\dist\rn-extension.js:1:5426)
	at C.dispatchRequest (c:\Users\Marcel\.vscode\extensions\msjsdiag.vscode-react-native-1.12.3\dist\rn-extension.js:1:18045)
	at C.handleMessage (c:\Users\Marcel\.vscode\extensions\msjsdiag.vscode-react-native-1.12.3\dist\rn-extension.js:1:22697)
	at C._handleData (c:\Users\Marcel\.vscode\extensions\msjsdiag.vscode-react-native-1.12.3\dist\rn-extension.js:1:24416)
	at Socket.<anonymous> (c:\Users\Marcel\.vscode\extensions\msjsdiag.vscode-react-native-1.12.3\dist\rn-extension.js:1:23015)
	at Socket.emit (node:events:513:28)
	at Socket.emit (node:domain:489:12)
	at addChunk (node:internal/streams/readable:324:12)
	at readableAddChunk (node:internal/streams/readable:297:9)
	at Readable.push (node:internal/streams/readable:234:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
Common
 ✓ Node.js - Required to execute JavaScript code
 ✓ yarn - Required to install NPM dependencies
 ● Metro - Metro Bundler is not running

Android
 ✖ Adb - No devices and/or emulators connected. Please create emulator with Android Studio or connect Android device.
 ✓ JDK - Required to compile Java code
 ✖ Android Studio - Required for building and installing your app on Android
 ✓ ANDROID_HOME - Environment variable that points to your Android SDK installation
 ✓ Gradlew - Build tool required for Android builds
 ✓ Android SDK - Required for building and installing your app on Android

Errors:   2
Warnings: 1
```

PS: I closed the bundler and emulator before running `react-native doctor`.

* `envinfo`:

```text
  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600K
    Memory: 20.16 GB / 31.82 GB
  Binaries:
    Node: 20.11.0 - D:\dev_tools\node\node.EXE
    Yarn: 4.0.2 - D:\dev_tools\node\yarn.CMD
    npm: 10.2.4 - D:\dev_tools\node\npm.CMD
    Watchman: 20231008.002904.0 - D:\dev_tools\watchman\bin\watchman.EXE
  Utilities:
    CMake: 3.28.1 - /d/dev_tools/cmake/bin/cmake
    Git: 2.42.0. - /d/dev_tools/git/bin/git
    Clang: 17.0.6 - c:\msys64\clang64\bin\clang.EXE
    Ninja: 1.11.1 - /d/dev_tools/ninja/bin/ninja
    Curl: 8.4.0 - c:\windows\system32\curl.EXE
  SDKs:
    Android SDK:
      API Levels: 33
      Build Tools: 33.0.1, 34.0.0
      System Images: android-33 | Intel x86_64 Atom
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
  IDEs:
    VSCode: 1.85.2 - C:\Users\{user}\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
    Visual Studio: 16.11.34407.143 (Visual Studio Community 2019)
  Languages:
    Bash: 5.2.15 - D:\dev_tools\git\bin\bash.EXE
    Java: 17.0.9 - /d/dev_tools/jdk/bin/javac
    Perl: 5.38.2 - c:\msys64\usr\bin\perl.EXE
    Python: 3.11.7 - /clang64/bin/python
    Python3: 3.11.7 - /clang64/bin/python3
  Databases:
    SQLite: 3.44.2 - c:\msys64\clang64\bin\sqlite3.EXE
  Browsers:
    Edge: Chromium (121.0.2277.83)
    Internet Explorer: 11.0.22621.1
```

* React Native Tools extension version: v1.12.3
* Expo SDK version (if applicable): N/A

**Comment by lexie011** [comment]
Hi, @TheWir. Thanks for reaching us.
.cjs config file is not supported yet. This feature will be added in our agenda.

**Comment by TheWirv** [comment]
Hi, thanks so mich!
