### ISSUE TITLE
[Bug] LogCat not Detecting adb correctly on MAC

### ISSUE THREAD

**Issue by SamJbori** [microsoft/vscode-react-native#2129]
# 🐛 What is the bug? How can we reproduce it?
I am getting /bin/sh: adb: command not found when I try to run RN LogCat
![image](https://github.com/microsoft/vscode-react-native/assets/17522597/4d9c2130-87c0-447b-95ad-95adb0cd4d1d)

I am using most recent vscode 1.87.2
most recent plugin

I am trying to run the command
React Native: Run React Native LogCat Monitor

## Expected behavior

the logCat monitor work
## Debug output

<details>
<summary>Debug Console</summary>

```text


```
</details>

<details>
<summary>React Native output channel</summary>

```text

[Warning] An error occurred while trying to get installed emulators: Error while executing command 'emulator -list-avds': Command failed: emulator -list-avds
/bin/sh: emulator: command not found

Continue using only online targets

[Error] Error while starting monitoring LogCat (error code 1206)

Stack: Error: Error while starting monitoring LogCat (error code 1206): Error while executing command 'adb devices': Command failed: adb devices
/bin/sh: adb: command not found

	at o.getWrappedError (/Users/wj/.vscode-server/extensions/msjsdiag.vscode-react-native-1.13.0/dist/rn-extension.js:21:382537)
	at i.wrapError (/Users/wj/.vscode-server/extensions/msjsdiag.vscode-react-native-1.13.0/dist/rn-extension.js:21:374834)
	at /Users/wj/.vscode-server/extensions/msjsdiag.vscode-react-native-1.13.0/dist/rn-extension.js:21:374403
[Warning] An error occurred while trying to get installed emulators: Error while executing command 'emulator -list-avds': Command failed: emulator -list-avds
/bin/sh: emulator: command not found

Continue using only online targets

[Error] Error while starting monitoring LogCat (error code 1206)

Stack: Error: Error while starting monitoring LogCat (error code 1206): Error while executing command 'adb devices': Command failed: adb devices
/bin/sh: adb: command not found

	at o.getWrappedError (/Users/wj/.vscode-server/extensions/msjsdiag.vscode-react-native-1.13.0/dist/rn-extension.js:21:382537)
	at i.wrapError (/Users/wj/.vscode-server/extensions/msjsdiag.vscode-react-native-1.13.0/dist/rn-extension.js:21:374834)
	at /Users/wj/.vscode-server/extensions/msjsdiag.vscode-react-native-1.13.0/dist/rn-extension.js:21:374403
```
</details>

<details>
<summary>Developer Tools console</summary>

```text

workbench.desktop.main.js:sourcemap:651  INFO Started local extension host with pid 43972.
workbench.desktop.main.js:sourcemap:651  INFO Invoking resolveAuthority(ssh-remote)...
workbench.desktop.main.js:sourcemap:651  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] obtaining proxy...
workbench.desktop.main.js:sourcemap:651  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] invoking...
workbench.desktop.main.js:sourcemap:651  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][1002ms] waiting...
workbench.desktop.main.js:sourcemap:651  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][2027ms] waiting...
workbench.desktop.main.js:sourcemap:651  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][3001ms] waiting...
workbench.desktop.main.js:sourcemap:651  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][4003ms] waiting...
workbench.desktop.main.js:sourcemap:651  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][4526ms] returned WebSocket(127.0.0.1:51492)
workbench.desktop.main.js:sourcemap:651  INFO resolveAuthority(ssh-remote) returned 'WebSocket(127.0.0.1:51492)' after 4526 ms
workbench.desktop.main.js:sourcemap:651  INFO Creating a socket (renderer-Management-b1d578f2-6d03-4f8e-ba4a-3254425a8ba7)...
workbench.desktop.main.js:sourcemap:651  INFO Creating a socket (renderer-ExtensionHost-045fc50f-dc03-4c16-9466-de497b647bd4)...
workbench.desktop.main.js:sourcemap:651  INFO Creating a socket (renderer-Management-b1d578f2-6d03-4f8e-ba4a-3254425a8ba7) was successful after 4 ms.
workbench.desktop.main.js:sourcemap:651  INFO Creating a socket (renderer-ExtensionHost-045fc50f-dc03-4c16-9466-de497b647bd4) was successful after 18 ms.
2workbench.desktop.main.js:sourcemap:678 Ignoring expo.appManifest.fileReferences.excludeGlobPatterns as expo.appManifest.fileReferences is true
(anonymous) @ workbench.desktop.main.js:sourcemap:678
workbench.desktop.main.js:sourcemap:1871 Overwriting grammar scope name to file mapping for scope source.js.jsx.
Old grammar file: file:///c%3A/Users/SamJb/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/javascript/syntaxes/JavaScriptReact.tmLanguage.json.
New grammar file: vscode-remote://ssh-remote%2B7b22686f73744e616d65223a226d61634f532e4d616e43617665227d/Users/wj/.vscode-server/extensions/ms-vscode.vscode-typescript-next-5.5.20240325/syntaxes/JavaScriptReact.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1871
workbench.desktop.main.js:sourcemap:1871 Overwriting grammar scope name to file mapping for scope source.js.
Old grammar file: file:///c%3A/Users/SamJb/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/javascript/syntaxes/JavaScript.tmLanguage.json.
New grammar file: vscode-remote://ssh-remote%2B7b22686f73744e616d65223a226d61634f532e4d616e43617665227d/Users/wj/.vscode-server/extensions/ms-vscode.vscode-typescript-next-5.5.20240325/syntaxes/JavaScript.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1871
workbench.desktop.main.js:sourcemap:1871 Overwriting grammar scope name to file mapping for scope source.ts.
Old grammar file: file:///c%3A/Users/SamJb/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/typescript-basics/syntaxes/TypeScript.tmLanguage.json.
New grammar file: vscode-remote://ssh-remote%2B7b22686f73744e616d65223a226d61634f532e4d616e43617665227d/Users/wj/.vscode-server/extensions/ms-vscode.vscode-typescript-next-5.5.20240325/syntaxes/TypeScript.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1871
workbench.desktop.main.js:sourcemap:1871 Overwriting grammar scope name to file mapping for scope source.tsx.
Old grammar file: file:///c%3A/Users/SamJb/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/typescript-basics/syntaxes/TypeScriptReact.tmLanguage.json.
New grammar file: vscode-remote://ssh-remote%2B7b22686f73744e616d65223a226d61634f532e4d616e43617665227d/Users/wj/.vscode-server/extensions/ms-vscode.vscode-typescript-next-5.5.20240325/syntaxes/TypeScriptReact.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1871
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.js.jsx.
Old grammar file: file:///c%3A/Users/SamJb/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/javascript/syntaxes/JavaScriptReact.tmLanguage.json.
New grammar file: vscode-remote://ssh-remote%2B7b22686f73744e616d65223a226d61634f532e4d616e43617665227d/Users/wj/.vscode-server/extensions/ms-vscode.vscode-typescript-next-5.5.20240325/syntaxes/JavaScriptReact.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.js.
Old grammar file: file:///c%3A/Users/SamJb/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/javascript/syntaxes/JavaScript.tmLanguage.json.
New grammar file: vscode-remote://ssh-remote%2B7b22686f73744e616d65223a226d61634f532e4d616e43617665227d/Users/wj/.vscode-server/extensions/ms-vscode.vscode-typescript-next-5.5.20240325/syntaxes/JavaScript.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.ts.
Old grammar file: file:///c%3A/Users/SamJb/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/typescript-basics/syntaxes/TypeScript.tmLanguage.json.
New grammar file: vscode-remote://ssh-remote%2B7b22686f73744e616d65223a226d61634f532e4d616e43617665227d/Users/wj/.vscode-server/extensions/ms-vscode.vscode-typescript-next-5.5.20240325/syntaxes/TypeScript.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.tsx.
Old grammar file: file:///c%3A/Users/SamJb/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/typescript-basics/syntaxes/TypeScriptReact.tmLanguage.json.
New grammar file: vscode-remote://ssh-remote%2B7b22686f73744e616d65223a226d61634f532e4d616e43617665227d/Users/wj/.vscode-server/extensions/ms-vscode.vscode-typescript-next-5.5.20240325/syntaxes/TypeScriptReact.tmLanguage.json
register @ TMScopeRegistry.ts:46
workbench.desktop.main.js:sourcemap:651  WARN No search provider registered for scheme: vscode-remote, waiting
workbench.desktop.main.js:sourcemap:651   ERR [Extension Host] Failed to load message bundle for file c:\Users\SamJb\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.5\out\extension
workbench.desktop.main.js:sourcemap:148 [Extension Host] Failed to load message bundle for file c:\Users\SamJb\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.5\out\extension
p @ workbench.desktop.main.js:sourcemap:148
workbench.desktop.main.js:sourcemap:651   ERR [Extension Host] Failed to load message bundle for file c:\Users\SamJb\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.5\out\extension
workbench.desktop.main.js:sourcemap:148 [Extension Host] Failed to load message bundle for file c:\Users\SamJb\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.5\out\extension
p @ workbench.desktop.main.js:sourcemap:148
workbench.desktop.main.js:sourcemap:651   ERR [Extension Host] Failed to load message bundle for file c:\Users\SamJb\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.5\out\extension
workbench.desktop.main.js:sourcemap:148 [Extension Host] Failed to load message bundle for file c:\Users\SamJb\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.5\out\extension
p @ workbench.desktop.main.js:sourcemap:148
workbench.desktop.main.js:sourcemap:651   ERR [Extension Host] Failed to load message bundle for file c:\Users\SamJb\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.5\out\extension
workbench.desktop.main.js:sourcemap:148 [Extension Host] Failed to load message bundle for file c:\Users\SamJb\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.5\out\extension
p @ workbench.desktop.main.js:sourcemap:148
workbench.desktop.main.js:sourcemap:651   ERR [Extension Host] Failed to load message bundle for file c:\Users\SamJb\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.5\out\extension
workbench.desktop.main.js:sourcemap:148 [Extension Host] Failed to load message bundle for file c:\Users\SamJb\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.5\out\extension
p @ workbench.desktop.main.js:sourcemap:148
workbench.desktop.main.js:sourcemap:651   ERR [Extension Host] Failed to load message bundle for file c:\Users\SamJb\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.5\out\extension
workbench.desktop.main.js:sourcemap:148 [Extension Host] Failed to load message bundle for file c:\Users\SamJb\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.5\out\extension
p @ workbench.desktop.main.js:sourcemap:148
workbench.desktop.main.js:sourcemap:651   ERR [Extension Host] Failed to load message bundle for file c:\Users\SamJb\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.5\out\extension
workbench.desktop.main.js:sourcemap:148 [Extension Host] Failed to load message bundle for file c:\Users\SamJb\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.5\out\extension
p @ workbench.desktop.main.js:sourcemap:148
workbench.desktop.main.js:sourcemap:651   ERR [Extension Host] Failed to load message bundle for file c:\Users\SamJb\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.5\out\extension
workbench.desktop.main.js:sourcemap:148 [Extension Host] Failed to load message bundle for file c:\Users\SamJb\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.5\out\extension
p @ workbench.desktop.main.js:sourcemap:148
workbench.desktop.main.js:sourcemap:651   ERR [Extension Host] (node:8022) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
workbench.desktop.main.js:sourcemap:148 [Extension Host] (node:8022) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
p @ workbench.desktop.main.js:sourcemap:148
workbench.desktop.main.js:sourcemap:651  INFO [perf] Render performance baseline is 13ms
workbench.desktop.main.js:sourcemap:651   ERR Could not find pty on pty host: CodeExpectedError: Could not find pty on pty host
    at D.U (/Users/wj/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateIcon (/Users/wj/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/platform/terminal/node/ptyHostMain.js:43:27763)
    at T.<computed> (/Users/wj/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/Users/wj/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/Users/wj/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/Users/wj/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/Users/wj/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/Users/wj/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/Users/wj/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/Users/wj/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2workbench.desktop.main.js:sourcemap:651   ERR Could not find pty on pty host: CodeExpectedError: Could not find pty on pty host
    at D.U (/Users/wj/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/platform/terminal/node/ptyHostMain.js:43:32578)
    at D.updateTitle (/Users/wj/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/platform/terminal/node/ptyHostMain.js:43:27710)
    at T.<computed> (/Users/wj/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/platform/terminal/node/ptyHostMain.js:43:22925)
    at Object.call (/Users/wj/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/platform/terminal/node/ptyHostMain.js:34:5061)
    at u.s (/Users/wj/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/platform/terminal/node/ptyHostMain.js:32:5165)
    at u.q (/Users/wj/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/platform/terminal/node/ptyHostMain.js:32:4667)
    at l.value (/Users/wj/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/platform/terminal/node/ptyHostMain.js:32:4065)
    at m.y (/Users/wj/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at m.fire (/Users/wj/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process._ (/Users/wj/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/platform/terminal/node/ptyHostMain.js:25:10025)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
workbench.desktop.main.js:sourcemap:651   ERR read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✖ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Error: Problem validating fields in /Users/wj/Projects/hamemadmin/app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • Field: android - should NOT have additional property 'enableDangerousExperimentalLeanBuilds'.

One or more checks failed, indicating possible issues with the project.```

* `envinfo`:

```text
 System:
    OS: macOS 12.6.7
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i9-13900K
    Memory: 3.84 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.19.1/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v18.19.1/bin/npm
    Watchman: 2024.03.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
    Homebrew: 4.2.15 - /usr/local/bin/brew
    pip3: 24.0 - /usr/local/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 14.0.0 - /usr/bin/gcc
    Git: 2.37.1 - /usr/bin/git
    Clang: 14.0.0 - /usr/bin/clang
    Curl: 7.87.0 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2023.1 AI-231.9392.1.2311.11330709
    Vim: 9.0 - /usr/bin/vim
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 17.0.10 - /usr/local/opt/openjdk@17/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python3: 3.12.2 - /usr/local/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    SQLite: 3.42.0 - /Users/wj/Library/Android/sdk/platform-tools/sqlite3
  Browsers:
    Edge: 123.0.2420.53
    Safari: 15.6.1```

* React Native Tools extension version: v1.13.0
* Expo SDK version (if applicable): 50.0.14
Additional 
wj@mmancave ~ % /bin/sh --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.
wj@mmancave ~ % /bin/sh adb
/Users/wj/Library/Android/sdk/platform-tools/adb: /Users/wj/Library/Android/sdk/platform-tools/adb: cannot execute binary file
wj@mmancave ~ % /bin/sh
sh-3.2$ adb devices
List of devices attached
R58RB4G1GLK     device

sh-3.2$ adb devices
List of devices attached
R58RB4G1GLK     device

sh-3.2$ exit
```

**Comment by SamJbori** [comment]
The issue is creating a `.bash_profile` even if you are using `zsh`, `.bashrc` wont work on mac too.
