### ISSUE TITLE
[Bug] attach function does not work as expected

### ISSUE THREAD

**Issue by biaji** [microsoft/vscode-react-native#2253]
# 🐛 What is the bug? How can we reproduce it?

1. Open  a  rn project and using debug once(must load the applicaiton in client)
2. close vscode
3. open vscode and same project again,
4. try to attach 

## Expected behavior

attach works as first time

actually,  it begin to start metro instead of attaching, and report error of port in use because I already start the packager myself.

Interest thing is:  

- Every first attempt to attach is successful.
- This issue related to a config in `~/Library/Application Support/Code/User/workspaceStorage/xxxx/state.vscdb`. If I delete the database,  It works as expected.

## Debug output

<details>
<summary>Debug Console</summary>

```text

Attaching to the application
An error occurred while attaching debugger to the application. 无法启动包生成工具。 (error code 1410)

```
</details>

<details>
<summary>React Native output channel</summary>

```text

[Info] Need to check main file and entry point of open module, will setup and write new content if they're not existing. Path: /Users/xxxxxxx/node_modules/open

[Info] Find open-main.js and entry in open module, skip setup...

[Info] 正在启动包生成工具

[Debug] Executing command: /Users/xxxxxxx/node_modules/.bin/react-native start --port 8081

error listen EADDRINUSE: address already in use :::8081.
Error: listen EADDRINUSE: address already in use :::8081
    at Server.setupListenHandle [as _listen2] (node:net:1817:16)
    at listenInCluster (node:net:1865:12)
    at Server.listen (node:net:1953:7)
    at /Users/xxxxxxx/node_modules/metro/src/index.flow.js:398:14
    at new Promise (<anonymous>)
    at earlyPortCheck (/Users/xxxxxxx/node_modules/metro/src/index.flow.js:394:11)
    at exports.runServer (/Users/xxxxxxx/node_modules/metro/src/index.flow.js:155:9)
    at Object.runServer [as func] (/Users/xxxxxxx/node_modules/@react-native-community/cli-plugin-metro/build/commands/start/runServer.js:123:49)
    at async Command.handleAction (/Users/xxxxxxx/node_modules/@react-native-community/cli/build/index.js:142:9)
info Run CLI with --verbose flag for more details.
```
</details>

## Environment

* `launch.json`:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "连接至debug服务",
            "cwd": "${workspaceFolder}",
            "type": "reactnative",
            "request": "attach",
            "sourceMaps": true,
            "port": 8081
        }
    ]
}
```

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
Common
 ✓ Node.js
 ✓ yarn
 ✓ Watchman - Used for watching changes in the filesystem when in development mode

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ● ios-deploy - Required for installing your app on a physical device with the CLI
 ✓ .xcode.env - File to customize Xcode environment

Errors:   0
Warnings: 1

```

* `envinfo`:

```text
PASTE OUTPUT OF `npx envinfo`
```

* React Native Tools extension version: v1.13.0

**Comment by biaji** [comment]
> Hey [@biaji](https://github.com/biaji) , thanks for reaching us. I cannot repro it in my local. But if you launch your application using react-native-tools rn packager, and close vscode directly, the packager port may be not killed correctly. Could you please try to using `npx kill-port 8081` to force kill your metro port and try it again?

Not really,  I start my metro packager in another terminal using common `npx react-native start` which out of vscode.  And packager keep running while vscode close,  and restart. 

Is it normal when I using `attach to packager` and `react-native-tools` try to start the packager even when there is already a packager running ?

**Comment by biaji** [comment]
It looks like it failed at:


```javascript
    public async isRunning(): Promise<boolean> {
        const statusURL = `http://${this.getHost()}/status`;
        try {
            const body = await Request.request(statusURL);
            return body === "packager-status:running";
        } catch (error) {
            return false;  // got an error as :  "Cannot read properties of null (reading 'agent')"
        }
    }
```

with stack:

```
TypeError: Cannot read properties of null (reading 'agent')
	at Object.patchedFn [as get] (/Users/xxxx/.vscode/extensions/sourcegraph.cody-ai-1.46.0/dist/extension.node.js:180958:21)
	at /Users/xxxx/workspace/vscode-react-native/src/common/node/request.js:11:50
	at new Promise (<anonymous>)
	at Request.request (/Users/xxxx/workspace/vscode-react-native/src/common/node/request.js:10:16)
	at Packager.<anonymous> (/Users/xxxx/workspace/vscode-react-native/src/common/packager.js:299:54)
	at Generator.next (<anonymous>)
	at /Users/xxxx/workspace/vscode-react-native/src/common/packager.js:10:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/xxxx/workspace/vscode-react-native/src/common/packager.js:6:12)
	at Packager.isRunning (/Users/xxxx/workspace/vscode-react-native/src/common/packager.js:296:16)
	at Packager.<anonymous> (/Users/xxxx/workspace/vscode-react-native/src/common/packager.js:225:28)
	at Generator.next (<anonymous>)
	at /Users/xxxx/workspace/vscode-react-native/src/common/packager.js:10:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/xxxx/workspace/vscode-react-native/src/common/packager.js:6:12)
	at Packager.stop (/Users/xxxx/workspace/vscode-react-native/src/common/packager.js:222:16)
	at StopPackager.<anonymous> (/Users/xxxx/workspace/vscode-react-native/src/extension/commands/stopPackager.js:48:94)
	at Generator.next (<anonymous>)
	at /Users/xxxx/workspace/vscode-react-native/src/extension/commands/stopPackager.js:10:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/xxxx/workspace/vscode-react-native/src/extension/commands/stopPackager.js:6:12)
	at StopPackager.baseFn (/Users/xxxx/workspace/vscode-react-native/src/extension/commands/stopPackager.js:46:16)
	at StopPackager.<anonymous> (/Users/xxxx/workspace/vscode-react-native/src/extension/commands/util/reactNativeCommand.js:64:23)
	at Generator.next (<anonymous>)
	at /Users/xxxx/workspace/vscode-react-native/src/extension/commands/util/reactNativeCommand.js:10:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/xxxx/workspace/vscode-react-native/src/extension/commands/util/reactNativeCommand.js:6:12)
	at /Users/xxxx/workspace/vscode-react-native/src/extension/commands/util/reactNativeCommand.js:56:31
	at /Users/xxxx/workspace/vscode-react-native/src/common/telemetryHelper.js:123:29
	at TelemetryGenerator.<anonymous> (/Users/xxxx/workspace/vscode-react-native/src/common/telemetryGenerators.js:64:30)
	at Generator.next (<anonymous>)
	at /Users/xxxx/workspace/vscode-react-native/src/common/telemetryGenerators.js:10:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/xxxx/workspace/vscode-react-native/src/common/telemetryGenerators.js:6:12)
	at TelemetryGenerator.time (/Users/xxxx/workspace/vscode-react-native/src/common/telemetryGenerators.js:61:16)
	at TelemetryHelper.generate (/Users/xxxx/workspace/vscode-react-native/src/common/telemetryHelper.js:123:14)
	at StopPackager.<anonymous> (/Users/xxxx/workspace/vscode-react-native/src/extension/commands/util/reactNativeCommand.js:51:53)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/xxxx/workspace/vscode-react-native/src/extension/commands/util/reactNativeCommand.js:7:58)
```

**Comment by biaji** [comment]
it looks like it failed at:

```javascript
    public async isRunning(): Promise<boolean> {
        const statusURL = `http://${this.getHost()}/status`;
        try {
            const body = await Request.request(statusURL);
            return body === "packager-status:running";
        } catch (error) {
            return false;   //got an error
        }
    }

```

with stack:

```
TypeError: Cannot read properties of null (reading 'agent')
	at Object.patchedFn [as get] (/Users/xxxx/.vscode/extensions/sourcegraph.cody-ai-1.46.0/dist/extension.node.js:180958:21)
	at /Users/xxxx/workspace/vscode-react-native/src/common/node/request.js:11:50
	at new Promise (<anonymous>)
	at Request.request (/Users/xxxx/workspace/vscode-react-native/src/common/node/request.js:10:16)
	at Packager.<anonymous> (/Users/xxxx/workspace/vscode-react-native/src/common/packager.js:299:54)
	at Generator.next (<anonymous>)
	at /Users/xxxx/workspace/vscode-react-native/src/common/packager.js:10:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/xxxx/workspace/vscode-react-native/src/common/packager.js:6:12)
	at Packager.isRunning (/Users/xxxx/workspace/vscode-react-native/src/common/packager.js:296:16)
	at Packager.<anonymous> (/Users/xxxx/workspace/vscode-react-native/src/common/packager.js:225:28)
	at Generator.next (<anonymous>)
	at /Users/xxxx/workspace/vscode-react-native/src/common/packager.js:10:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/xxxx/workspace/vscode-react-native/src/common/packager.js:6:12)
	at Packager.stop (/Users/xxxx/workspace/vscode-react-native/src/common/packager.js:222:16)
	at StopPackager.<anonymous> (/Users/xxxx/workspace/vscode-react-native/src/extension/commands/stopPackager.js:48:94)
	at Generator.next (<anonymous>)
	at /Users/xxxx/workspace/vscode-react-native/src/extension/commands/stopPackager.js:10:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/xxxx/workspace/vscode-react-native/src/extension/commands/stopPackager.js:6:12)
	at StopPackager.baseFn (/Users/xxxx/workspace/vscode-react-native/src/extension/commands/stopPackager.js:46:16)
	at StopPackager.<anonymous> (/Users/xxxx/workspace/vscode-react-native/src/extension/commands/util/reactNativeCommand.js:64:23)
	at Generator.next (<anonymous>)
	at /Users/xxxx/workspace/vscode-react-native/src/extension/commands/util/reactNativeCommand.js:10:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/xxxx/workspace/vscode-react-native/src/extension/commands/util/reactNativeCommand.js:6:12)
	at /Users/xxxx/workspace/vscode-react-native/src/extension/commands/util/reactNativeCommand.js:56:31
	at /Users/xxxx/workspace/vscode-react-native/src/common/telemetryHelper.js:123:29
	at TelemetryGenerator.<anonymous> (/Users/xxxx/workspace/vscode-react-native/src/common/telemetryGenerators.js:64:30)
	at Generator.next (<anonymous>)
	at /Users/xxxx/workspace/vscode-react-native/src/common/telemetryGenerators.js:10:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/xxxx/workspace/vscode-react-native/src/common/telemetryGenerators.js:6:12)
	at TelemetryGenerator.time (/Users/xxxx/workspace/vscode-react-native/src/common/telemetryGenerators.js:61:16)
	at TelemetryHelper.generate (/Users/xxxx/workspace/vscode-react-native/src/common/telemetryHelper.js:123:14)
	at StopPackager.<anonymous> (/Users/xxxx/workspace/vscode-react-native/src/extension/commands/util/reactNativeCommand.js:51:53)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/xxxx/workspace/vscode-react-native/src/extension/commands/util/reactNativeCommand.js:7:58)
```

ok....cody.....

**Comment by EzioLi01** [comment]
Thanks for the info, I will also look into this scenario.
