### ISSUE TITLE
Running with exponent isn't working

### ISSUE THREAD

**Issue by MarkEstefanos** [Microsoft/vscode-react-native#414]
## Actual Behavior
1. In console: "Warning: Installed version 0.41.2 of 'react-native' does not satify required version https://github.com/exponent/react-native/archive/sdk-14.0.0.tar.gz\n\nIf there is an issue running your project, please run `npm install` in /Users/mark/Documents/Projects/right-hook and restart."
2. In simulator: "Unable to resolve module ./assets/fonts/SpaceMono-Regular.ttf from /..../. Directory doesn't exist." (it does exist)
3. Can't run Exponent app in simulator
4. Everything works using XDE
5. npm install doesn't solve the issue, nor does clearing node modules and trying again

## Expected Behavior
1. Correct execution of RN app in exponent

## Software versions
- React-Native VS Code extension version: 0.3.1
- VSCode version: 1.10.1
- OS platform and version: macOS 10.12.3
- NodeJS version: v7.4.0
- React Native version: from package.json: "react-native": "https://github.com/exponent/react-native/archive/sdk-14.0.0.tar.gz"

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
none
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
######### Packager started. ##########
Loading dependency graph, done.
Loading dependency graph..."Warning: Problem in exp.json. child \"notification\" fails because [\"icon\" is not allowed]. See https://docs.getexponent.com/."
"Warning: Installed version 0.41.2 of 'react-native' does not satify required version https://github.com/exponent/react-native/archive/sdk-14.0.0.tar.gz\n\nIf there is an issue running your project, please run `npm install` in /Users/mark/Documents/Projects/right-hook and restart."
"Warning: Problem in exp.json. child \"notification\" fails because [\"icon\" is not allowed]. See https://docs.getexponent.com/."
Bundling `main.js`
  Analysing...(node:12037) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): UnableToResolveError: Unable to resolve module ./assets/fonts/SpaceMono-Regular.ttf from /Users/mark/Documents/Projects/right-hook/main.js: Directory /Users/mark/Documents/Projects/right-hook/assets/fonts/SpaceMono-Regular.ttf doesn't exist
(node:12037) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Starting custom debugger by executing: echo A debugger is not needed:  "/Users/mark/Documents/Projects/right-hook" "/Users/mark/Documents/Projects/right-hook/.vscode"
"Warning: Installed version 0.41.2 of 'react-native' does not satify required version https://github.com/exponent/react-native/archive/sdk-14.0.0.tar.gz\n\nIf there is an issue running your project, please run `npm install` in /Users/mark/Documents/Projects/right-hook and restart."

```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
mainThreadExtensionService.ts:110Extension is not compatible with Code 1.10.1. Extension requires: 1.5.x.t.$localShowMessage @ mainThreadExtensionService.ts:110
extensionHost.ts:282[Extension Host] typescript (vscode.typescript) uses PROPOSED API which is subject to change and removal without notice
extensionHost.ts:282[Extension Host] Error: Module version mismatch. Expected 50, got 51.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:178:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:178:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:15:19228)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mark/.vscode/extensions/vsmobile.vscode-react-native-0.3.1/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)d.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:15:19228)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mark/.vscode/extensions/vsmobile.vscode-react-native-0.3.1/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:15:19228)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mark/.vscode/extensions/vsmobile.vscode-react-native-0.3.1/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:556:32)d.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:15:19228)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mark/.vscode/extensions/vsmobile.vscode-react-native-0.3.1/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:15:19228)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mark/.vscode/extensions/vsmobile.vscode-react-native-0.3.1/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:556:32)d.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] Uncaught Exception:  TypeError: l._setExceptionValue is not a functiond.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] TypeError: l._setExceptionValue is not a function
    at Object.m [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:6603)
    at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:10162)
    at _run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:11990)
    at _completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:11431)
    at e.resolveOk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:9:580)
    at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:8:31148)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)d.logExtensionHostMessage @ extensionHost.ts:282
shell.ts:426l._setExceptionValue is not a function: TypeError: l._setExceptionValue is not a function
    at Object.m [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:6603)
    at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:10162)
    at _run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:11990)
    at _completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:11431)
    at e.resolveOk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:9:580)
    at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:8:31148)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)e.onUnexpectedError @ shell.ts:426
extensionHost.ts:282[Extension Host] Uncaught Exception:  TypeError: l._setExceptionValue is not a functiond.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] TypeError: l._setExceptionValue is not a function
    at Object.m [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:6603)
    at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:10162)
    at _run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:11990)
    at _completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:11431)
    at e.resolveOk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:9:580)
    at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:8:31148)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)d.logExtensionHostMessage @ extensionHost.ts:282
shell.ts:426l._setExceptionValue is not a function: TypeError: l._setExceptionValue is not a function
    at Object.m [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:6603)
    at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:10162)
    at _run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:11990)
    at _completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:11431)
    at e.resolveOk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:9:580)
    at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:8:31148)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)e.onUnexpectedError @ shell.ts:426
messageService.ts:126Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:23372).
```

**Comment by quincycs** [comment]
I also have ran into this.  I can reproduce by just running brand new exponent app made by XDE (choose the tab navigation sample).  The blank sample runs fine.
