### ISSUE TITLE
Couldn't import script at <http://localhost:8081/index.android.bundle?platform=android&dev=false&hot=false&minify=false>

### ISSUE THREAD

**Issue by VickyKoblinski** [Microsoft/vscode-react-native#446]
## Actual Behavior
I'm trying to set up Android debugging through VSC. Right now I've gotten breakpoints to work and initial debugging. My issue occurs reliably when:
1. I run Debug Android through VSC
2. I let the app install and run
3. Once running, I make a change to my project and save (even if that change is whitespace)
4. I reload the app.

I've checked the address to make sure the content it loads after saving my changes but before refreshing the app (using the emulator's reloading by double tapping R). I can access the address before reloading the app, but it immediately crashes once I ask it to reload. 

## Expected Behavior
1. Debugging to continue working after making changes and reloading the app.

## Software versions
- React-Native VS Code extension version: 0.3.2
- VSCode version: 1.12.1
- OS platform and version: Win7
- NodeJS version: 7.10
- React Native version: 0.42.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
[vscode-react-native] Debugger worker loaded runtime on port 11359
[vscode-react-native] Disconnected from the Proxy (Packager) to the React Native application. Retrying reconnection soon...
[Error] [Warning] Couldn't import script at <http://localhost:8081/index.android.bundle?platform=android&dev=false&hot=false&minify=false>. Debugging won't work: Try reloading the JS from inside the app, or Reconnect the VS Code debugger: read ECONNRESET
Stack: Error: Couldn't import script at <http://localhost:8081/index.android.bundle?platform=android&dev=false&hot=false&minify=false>. Debugging won't work: Try reloading the JS from inside the app, or Reconnect the VS Code debugger: read ECONNRESET
    at Function.getNestedWarning (C:\Users\me\.vscode\extensions\vsmobile.vscode-react-native-0.3.2\out\common\error\errorHelper.js:24:16)
    at printDebuggingError (C:\Users\me\.vscode\extensions\vsmobile.vscode-react-native-0.3.2\out\debugger\forkedAppWorker.js:13:52)
    at workerLoaded.promise.then.done.reason (C:\Users\me\.vscode\extensions\vsmobile.vscode-react-native-0.3.2\out\debugger\forkedAppWorker.js:84:88)
    at _rejected (C:\Users\me\.vscode\extensions\vsmobile.vscode-react-native-0.3.2\node_modules\q\q.js:844:24)
    at C:\Users\me\.vscode\extensions\vsmobile.vscode-react-native-0.3.2\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\me\.vscode\extensions\vsmobile.vscode-react-native-0.3.2\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\me\.vscode\extensions\vsmobile.vscode-react-native-0.3.2\node_modules\q\q.js:788:41)
    at C:\Users\me\.vscode\extensions\vsmobile.vscode-react-native-0.3.2\node_modules\q\q.js:604:44
    at runSingle (C:\Users\me\.vscode\extensions\vsmobile.vscode-react-native-0.3.2\node_modules\q\q.js:137:13)
    at flush (C:\Users\me\.vscode\extensions\vsmobile.vscode-react-native-0.3.2\node_modules\q\q.js:125:13)
******** Unhandled error in debug adapter - Unhandled promise rejection: Error: Cannot attach to packager. Are you sure there is a packager and it is running in the port 8081? If your packager is configured to run in another port make sure to add that to the setting.json.
    at packager_1.Packager.isPackagerRunning.then.running (C:\Users\me\.vscode\extensions\vsmobile.vscode-react-native-0.3.2\out\debugger\appWorker.js:40:23)
    at _fulfilled (C:\Users\me\.vscode\extensions\vsmobile.vscode-react-native-0.3.2\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\me\.vscode\extensions\vsmobile.vscode-react-native-0.3.2\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\me\.vscode\extensions\vsmobile.vscode-react-native-0.3.2\node_modules\q\q.js:796:13)
    at C:\Users\me\.vscode\extensions\vsmobile.vscode-react-native-0.3.2\node_modules\q\q.js:604:44
    at runSingle (C:\Users\me\.vscode\extensions\vsmobile.vscode-react-native-0.3.2\node_modules\q\q.js:137:13)
    at flush (C:\Users\me\.vscode\extensions\vsmobile.vscode-react-native-0.3.2\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by VickyKoblinski** [comment]
I discovered that my problem wasn't related to vscode-react-native but instead was a React Native issue:

Ref: https://github.com/facebook/react-native/issues/12895

The solution was to go into Dev Settings and reenable JS Dev Mode

**Comment by Kaybarax** [comment]
Mine is enabled but genymotion just cant pick it up.

**Comment by ruslan-bikkinin** [comment]
Hi @Kaybarax could you please submit separate issue describing your specific problem?

**Comment by Kaybarax** [comment]
Hey @VickyKoblinski @ruslan-bikkinin, thanks, but I was able to resolve it by adding this line:
compile ("com.facebook.react:react-native:<your.RN.version>") { force = true }
to android/app/build.gradle
and commenting out the line:
compile 'com.facebook.react:react-native:+'
This forces the Native Code version and your RN from node modules to match up.
