### ISSUE TITLE
"Android app has stopped" when trying to start from VSCode

### ISSUE THREAD

**Issue by Carpetfizz** [Microsoft/vscode-react-native#449]
## Actual Behavior
1. Press the green play button with "Debug Android" option selected
2. "MyApp has stopped" on physical Google Pixel

## Expected Behavior
1. Press the green play button with "Debug Android" option selected
2. App runs, I can enable Live Reload and go about my day

## Software versions
- React-Native VS Code extension version: 0.3.2
- VSCode version: 1.12.1
- OS platform and version: macOS 10.12.4
- NodeJS version: v7.4.0
- React Native version: 2.0.1

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
BUILD SUCCESSFUL
Total time: 11.316 secs
This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html
Running /Users/aramesh/Library/Android/sdk/platform-tools/adb -s FA6CN0300564 reverse tcp:8081 tcp:8081
Starting the app on FA6CN0300564 (/Users/aramesh/Library/Android/sdk/platform-tools/adb -s FA6CN0300564 shell am start -n com.customviewtest/.MainActivity)...
Starting: Intent { cmp=com.customviewtest/.MainActivity }
[vscode-react-native] Finished executing: react-native run-android
[vscode-react-native] Executing command: adb -s "FA6CN0300564" reverse tcp:8081 tcp:8081
[vscode-react-native] 
[vscode-react-native] Finished executing: adb -s "FA6CN0300564" reverse tcp:8081 tcp:8081
[vscode-react-native] Executing command: adb -s FA6CN0300564 shell am broadcast -a "com.customviewtest.RELOAD_APP_ACTION" --ez jsproxy true
[vscode-react-native] Broadcasting: Intent { act=com.customviewtest.RELOAD_APP_ACTION (has extras) }
Broadcast completed: result=0
[vscode-react-native] Finished executing: adb -s FA6CN0300564 shell am broadcast -a "com.customviewtest.RELOAD_APP_ACTION" --ez jsproxy true
[vscode-react-native] Starting debugger app worker.
[vscode-react-native] Established a connection with the Proxy (Packager) to the React Native application
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
Starting custom debugger by executing: echo A debugger is not needed:  "/Users/aramesh/Documents/Code/CustomViewTest"
Starting custom debugger by executing: echo A debugger is not needed:  "/Users/aramesh/Documents/Code/CustomViewTest"
Starting custom debugger by executing: echo A debugger is not needed:  "/Users/aramesh/Documents/Code/CustomViewTest"
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
workbench.main.js:29 [Extension Host] (node:20900) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
d.logExtensionHostMessage @ workbench.main.js:29
workbench.main.js:29 [Extension Host] Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Function.Y.o._load (/private/var/folders/xq/8fr0f9zx0tn86hbzmw7xb7v9px1v01/T/AppTranslocation/B6BE1A52-770D-4FF3-A0CF-D508135022D1/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:366384)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/aramesh/.vscode/extensions/vsmobile.vscode-react-native-0.3.2/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Object.<anonymous> (/Users/aramesh/.vscode/extensions/vsmobile.vscode-react-native-0.3.2/node_modules/dtrace-provider/dtrace-provider.js:42:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
d.logExtensionHostMessage @ workbench.main.js:29
workbench.main.js:29 [Extension Host] Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Function.Y.o._load (/private/var/folders/xq/8fr0f9zx0tn86hbzmw7xb7v9px1v01/T/AppTranslocation/B6BE1A52-770D-4FF3-A0CF-D508135022D1/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:366384)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/aramesh/.vscode/extensions/vsmobile.vscode-react-native-0.3.2/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Object.<anonymous> (/Users/aramesh/.vscode/extensions/vsmobile.vscode-react-native-0.3.2/node_modules/dtrace-provider/dtrace-provider.js:42:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
d.logExtensionHostMessage @ workbench.main.js:29
workbench.main.js:29 [Extension Host] Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Function.Y.o._load (/private/var/folders/xq/8fr0f9zx0tn86hbzmw7xb7v9px1v01/T/AppTranslocation/B6BE1A52-770D-4FF3-A0CF-D508135022D1/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:366384)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/aramesh/.vscode/extensions/vsmobile.vscode-react-native-0.3.2/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Object.<anonymous> (/Users/aramesh/.vscode/extensions/vsmobile.vscode-react-native-0.3.2/node_modules/dtrace-provider/dtrace-provider.js:42:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
d.logExtensionHostMessage @ workbench.main.js:29
```

**launch.json**

```javascript
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Android",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "launch",
            "platform": "android",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/.vscode/.react"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}"
        }
    ]
}
```

## Additional Information
* I can confirm that I have quit Google Chrome and I have not started `react-native run-android` anywhere else. 

* I have also quit all `node` tasks in Activity Monitor 

* Same result happens when I do `> React Native: Run Android` from the CMD+Shift+P menu. 

* I can also confirm that developer mode has been enabled  on my phone and I can successfully compile and run apps from Android Studio

* Running `react-native run-android` when VSCode is closed crashes the first time but works when I start the app again manually from the device.

**Comment by vladimir-kotikov** [comment]
@Carpetfizz, thanks for reporting!

However I think that this is more an issue w/ react-native, especially given that you're seeing exactly the same behavior when running `react-native run-android` from terminal.

Looking at the debug console output, though, it seems that the debugger being started correctly (see `[vscode-react-native] Established a connection with the Proxy (Packager) to the React Native application
` line) and just waiting for the app to connect (which will never happen since the app has crashed :) ). You can workaround this issue by running debug session from VSCode and then once app terminated, run it manually (just as in case with `react-native run-android` from terminal) and select 'Debug JS remotely' from app's debug menu on device. After that the app will connect to debugger and the debug session will continue.
