### ISSUE TITLE
Error while executing command 'react-native run-android --no-packager'

### ISSUE THREAD

**Issue by fix777** [Microsoft/vscode-react-native#569]
## Actual Behavior
1. Error

## Expected Behavior
1. Start Debugger

## Software versions
- React-Native VS Code extension version: 0.4.4
- VSCode version: 1.17.2
- OS platform and version: macOS Sierra 10.12.6
- NodeJS version: 8.2.1
- React Native version: 0.38.1

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.17.3
Could not debug. Error while executing command 'react-native run-android --no-packager': Error while executing command 'react-native run-android --no-packager'
Error processing "disconnect": TypeError: Cannot read property 'noDebug' of undefined
    at Object.terminateSession (/Users/g.wang/.vscode/extensions/ms-vscode.node-debug2-1.18.3/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:198:63)
    at Object.terminateSession (/Users/g.wang/.vscode/extensions/ms-vscode.node-debug2-1.18.3/out/src/nodeDebugAdapter.js:400:15)
    at Object.disconnect (/Users/g.wang/.vscode/extensions/ms-vscode.node-debug2-1.18.3/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:821:21)
    at Object.dispatchRequest (/Users/g.wang/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugSession.js:75:82)
    at Object.disconnect (/Users/g.wang/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/src/debugger/nodeDebugWrapper.js:83:23)
    at Object.dispatchRequest (/Users/g.wang/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/src/debugger/nodeDebugWrapper.js:44:29)
    at Object.ProtocolServer._handleData (/Users/g.wang/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/node_modules/vscode-debugadapter/lib/protocol.js:104:38)
    at Socket.<anonymous> (/Users/g.wang/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/node_modules/vscode-debugadapter/lib/protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Info] Starting Packager

Scanning 712 folders for symlinks in /Users/g.wang/Documents/Alibaba/DCOM/idcWorker/node_modules (24ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/g.wang/Documents/Alibaba/DCOM/idcWorker 

[Hot Module Replacement] Server listening on /hot

React packager ready.

[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.android.bundle?platform=android

[2017-10-30 22:48:13] <START> Requesting bundle bundle_url: /index.android.bundle?platform=android
[2017-10-30 22:48:15] <START> Initializing Packager
[2017-10-30 22:48:15] <START> Building in-memory fs for JavaScript
[2017-10-30 22:48:15] <END>   Building in-memory fs for JavaScript (53ms)
[2017-10-30 22:48:15] <START> Building Haste Map
[2017-10-30 22:48:15] <END>   Building Haste Map (367ms)
[2017-10-30 22:48:15] <END>   Initializing Packager (454ms)
[2017-10-30 22:48:15] <START> Transforming files
[2017-10-30 22:48:30] <END>   Transforming files (14676ms)
[2017-10-30 22:48:36] <END>   Requesting bundle bundle_url: /index.android.bundle?platform=android (22898ms)
[Warning] The Bundle Cache was prewarmed.

[Info] Building and running application.

[Error] Error: Error while executing command 'react-native run-android --no-packager': Error while executing command 'react-native run-android --no-packager'

[Info] Packager is already running.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.android.bundle?platform=android

[2017-10-30 22:51:36] <START> Requesting bundle bundle_url: /index.android.bundle?platform=android
[Warning] The Bundle Cache was prewarmed.

[Info] Building and running application.

[2017-10-30 22:51:36] <END>   Requesting bundle bundle_url: /index.android.bundle?platform=android (43ms)
[Error] Error: Error while executing command 'react-native run-android --no-packager': Error while executing command 'react-native run-android --no-packager'

[Info] Stopping Packager

[Info] Packager stopped

[Info] Attempting to start the React Native packager

[Info] Starting Packager

Scanning 712 folders for symlinks in /Users/g.wang/Documents/Alibaba/DCOM/idcWorker/node_modules (12ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/g.wang/Documents/Alibaba/DCOM/idcWorker 

[Hot Module Replacement] Server listening on /hot

React packager ready.

[2017-10-30 22:52:44] <START> Initializing Packager
[2017-10-30 22:52:44] <START> Building in-memory fs for JavaScript
[2017-10-30 22:52:44] <END>   Building in-memory fs for JavaScript (93ms)
[2017-10-30 22:52:44] <START> Building Haste Map
[2017-10-30 22:52:45] <END>   Building Haste Map (777ms)
[2017-10-30 22:52:45] <END>   Initializing Packager (910ms)
[Info] Packager started.

[Error] Failed to run the application in Android

Stack: Error: Failed to run the application in Android: Error while executing command 'react-native run-android --no-packager': Error while executing command 'react-native run-android --no-packager'
	at Function.getWrappedError (/Users/g.wang/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/src/common/error/internalError.js:35:16)
	at Function.wrapError (/Users/g.wang/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/src/common/error/errorHelper.js:18:44)
	at resultOfCode.done.reason (/Users/g.wang/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/src/common/entryPointHandler.js:46:72)
	at _rejected (/Users/g.wang/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/node_modules/q/q.js:844:24)
	at /Users/g.wang/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/node_modules/q/q.js:870:30
	at Promise.when (/Users/g.wang/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/node_modules/q/q.js:1122:31)
	at Promise.promise.promiseDispatch (/Users/g.wang/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/node_modules/q/q.js:788:41)
	at /Users/g.wang/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/node_modules/q/q.js:604:44
	at runSingle (/Users/g.wang/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/node_modules/q/q.js:137:13)
	at flush (/Users/g.wang/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/node_modules/q/q.js:125:13)
[Info] Packager is already running.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.android.bundle?platform=android

[2017-10-31 09:59:18] <START> Requesting bundle bundle_url: /index.android.bundle?platform=android
[2017-10-31 09:59:18] <START> Transforming files
[2017-10-31 09:59:19] <END>   Transforming files (674ms)
[Warning] The Bundle Cache was prewarmed.

[Info] Building and running application.

[2017-10-31 09:59:19] <END>   Requesting bundle bundle_url: /index.android.bundle?platform=android (852ms)
[Error] Error: Error while executing command 'react-native run-android --no-packager': Error while executing command 'react-native run-android --no-packager'

[Info] Packager is already running.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.android.bundle?platform=android

[2017-10-31 10:13:00] <START> Requesting bundle bundle_url: /index.android.bundle?platform=android
[2017-10-31 10:13:01] <END>   Requesting bundle bundle_url: /index.android.bundle?platform=android (40ms)
[Warning] The Bundle Cache was prewarmed.

[Info] Building and running application.

[Error] Error: Error while executing command 'react-native run-android --no-packager': Error while executing command 'react-native run-android --no-packager'

[Info] Packager is already running.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.android.bundle?platform=android

[2017-10-31 10:13:09] <START> Requesting bundle bundle_url: /index.android.bundle?platform=android
[Warning] The Bundle Cache was prewarmed.

[Info] Building and running application.

[2017-10-31 10:13:09] <END>   Requesting bundle bundle_url: /index.android.bundle?platform=android (40ms)
[Error] Error: Error while executing command 'react-native run-android --no-packager': Error while executing command 'react-native run-android --no-packager'

[Info] Packager is already running.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.android.bundle?platform=android

[2017-10-31 10:13:29] <START> Requesting bundle bundle_url: /index.android.bundle?platform=android
[Warning] The Bundle Cache was prewarmed.

[Info] Building and running application.

[2017-10-31 10:13:29] <END>   Requesting bundle bundle_url: /index.android.bundle?platform=android (39ms)
[Error] Error: Error while executing command 'react-native run-android --no-packager': Error while executing command 'react-native run-android --no-packager'

[Info] Packager is already running.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.android.bundle?platform=android

[2017-10-31 10:13:43] <START> Requesting bundle bundle_url: /index.android.bundle?platform=android
[Warning] The Bundle Cache was prewarmed.

[Info] Building and running application.

[2017-10-31 10:13:43] <END>   Requesting bundle bundle_url: /index.android.bundle?platform=android (39ms)
[Error] Error: Error while executing command 'react-native run-android --no-packager': Error while executing command 'react-native run-android --no-packager'
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 [Extension Host] vscode-customcss is active!
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 Git: Your local changes to the following files would be overwritten by checkout:
e.doShow @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 [Extension Host] (node:3892) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 [Extension Host] [Guides] Sending usage statistics...
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 [Extension Host] [Guides] Error while sending usage statistics: undefined
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 [Extension Host] [Guides] Usage statistics will retry in the next 5 minutes
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 [Extension Host] [Guides] Sending usage statistics...
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 [Extension Host] [Guides] Error while sending usage statistics: undefined
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 [Extension Host] [Guides] Usage statistics will retry in the next 10 minutes
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 [Extension Host] [Guides] Sending usage statistics...
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 [Extension Host] [Guides] Error while sending usage statistics: undefined
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 [Extension Host] [Guides] Usage statistics will retry in the next 20 minutes
```

**Comment by iTOYS** [comment]
Hi @fix777,
Thanks for reporting!
Seems like this is problem with one of our dependence, it have been already [fixed](https://github.com/Microsoft/vscode-node-debug2/issues/149).
I'm going to release new version of extension a bit later this week.
If new version of extension won't fix your issue, feel free to reopen it!
Thanks!
