### ISSUE TITLE
Debugging completely broken

### ISSUE THREAD

**Issue by TobyEalden** [Microsoft/vscode-react-native#581]
A simple vanilla app can not be debugged, e.g. following these steps:

```
react-native init test
```
Open `test` folder in vscode and create a react-native debug configuration, then hit 'Debug Android'.

Tested on both emulator and real device, on two different machines.

## Actual Behavior
1. App doesn't start 

## Expected Behavior
1. App should start

## Software versions
- React-Native VS Code extension version: 0.5.1
- VSCode version: 1.17.2
- OS platform and version: Ubuntu 16.04
- NodeJS version: 6.11.3
- React Native version: 0.50.1

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: linux x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.18.4
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Debugger worker loaded runtime on port 30099
SyntaxError: Unexpected token <
vm.js:56
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Timeout.Module.runMain [as _onTimeout] (module.js:604:10)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Info] Starting Packager

Scanning folders for symlinks in /home/nuc/dev/nqminds/nqm-careshare/MobileApp/node_modules (7ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running Metro Bundler on port 8081.                                       │ 
 │                                                                            │ 
 │  Keep Metro Bundler running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own Metro Bundler  instance if you    │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /home/nuc/dev/nqminds/nqm-careshare/MobileApp 


Metro Bundler ready.

Loading dependency graph, done.
[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] Entry point at /home/nuc/dev/nqminds/nqm-careshare/MobileApp/index.android.js doesn'tLog. exist. Skipping prewarming...

[Info] Building and running application.

Starting custom debugger by executing: echo A debugger is not needed:  "/home/nuc/dev/nqminds/nqm-careshare/MobileApp"
Starting custom debugger by executing: echo A debugger is not needed:  "/home/nuc/dev/nqminds/nqm-careshare/MobileApp"
Starting custom debugger by executing: echo A debugger is not needed:  "/home/nuc/dev/nqminds/nqm-careshare/MobileApp"
Starting custom debugger by executing: echo A debugger is not needed:  "/home/nuc/dev/nqminds/nqm-careshare/MobileApp"
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
extensionService.ts:435 Overwriting extension /usr/share/code/resources/app/extensions/ms-vscode.node-debug2 with /home/nuc/.vscode/extensions/ms-vscode.node-debug2-1.18.4.
e._logMessageInConsole @ extensionService.ts:435
console.ts:123 [Extension Host] vscode-icons is active!
console.ts:123 [Extension Host] (node:10592) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ console.ts:123
```

**Comment by iTOYS** [comment]
Fixed in 0.5.2
