### ISSUE TITLE
Debug via exponent fails to load script in Typescript CRNA. Unable to resolve module `../../../../App`

### ISSUE THREAD

**Issue by strake7** [Microsoft/vscode-react-native#589]
I have a bare bones react native application that was generated from CRNA via [react-native-scripts-ts](https://github.com/mathieudutour/create-react-native-app-typescript).  I have not been able to successfully debug the application in Expo using this extension in VSCode. It should be noted that running from console and using chrome dev tools works fine, 

## Actual Behavior
1. At the time of loading the application in the expo app the console reports a failures to import script. This breaks the application from proceeding. The log is: 

> Unable to resolve module `../../../../App` from `c:\\workspace\\react-native\\habit-builder\\node_modules\\react-native-scripts-ts\\build\\bin\\crna-entry.js`: could not resolve `c:\\workspace\\react-native\\habit-builder\\App' as a file nor as a folder

The App file does exist (though is TSX) and has shown to work just using the commands in terminal. 

## Expected Behavior
1. Able to load App.tsx and remotely debug the application in VSCode when hosted in Expo. 

## Software versions
- React-Native VS Code extension version: 
- VSCode version: 
- OS platform and version: 
- NodeJS version: 
- React Native version: 

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```

vscode-chrome-debug-core: 3.18.4
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Debugger worker loaded runtime on port 7683
Couldn't import script at <http://localhost:8081/./node_modules/react-native-scripts-ts/build/bin/crna-entry.bundle?platform=android&dev=true&strict=false&minify=false&hot=false&assetPlugin=c:%5Cworkspace%5Creact-native%5Chabit-builder%5Cnode_modules%5Cexpo%5Ctools%5ChashAssetFiles>. Debugging won't work: Try reloading the JS from inside the app, or Reconnect the VS Code debugger: {"from":"c:\\workspace\\react-native\\habit-builder\\node_modules\\react-native-scripts-ts\\build\\bin\\crna-entry.js","to":"../../../../App","message":"Unable to resolve module `../../../../App` from `c:\\workspace\\react-native\\habit-builder\\node_modules\\react-native-scripts-ts\\build\\bin\\crna-entry.js`: could not resolve `c:\\workspace\\react-native\\habit-builder\\App' as a file nor as a folder","name":"UnableToResolveError","type":"UnableToResolveError","errors":[{}]}
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Info] Making sure your project uses the correct dependencies for exponent. This may take a while...

Checking if this is Expo app......
[Info] Starting Packager

Scanning folders for symlinks in c:\workspace\react-native\habit-builder\node_modules (26ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   c:\workspace\react-native\habit-builder
   c:\workspace\react-native\habit-builder\.vscode 


React packager ready.

[Info] Packager started.

Sucessfully ran `adb reverse`. Localhost urls should work on the connected Android device.Sucessfully ran `adb reverse`. Localhost urls should work on the connected Android device.[Info] Prewarming bundle cache. This may take a while ...

[Info] Building and running application.

Loading dependency graph, done.
Starting custom debugger by executing: echo A debugger is not needed:  "c:\workspace\react-native\habit-builder" "c:\workspace\react-native\habit-builder\.vscode"
Bundling `node_modules\react-native-scripts-ts\build\bin\crna-entry.js`  [development, non-minified]  0.0% (0/410), failed.
error: bundling failed: UnableToResolveError: Unable to resolve module `../../../../App` from `c:\workspace\react-native\habit-builder\node_modules\react-native-scripts-ts\build\bin\crna-entry.js`: could not resolve `c:\workspace\react-native\habit-builder\App' as a file nor as a folder
    at ModuleResolver._loadAsFileOrDirOrThrow (c:\workspace\react-native\habit-builder\node_modules\metro-bundler\src\node-haste\DependencyGraph\ModuleResolution.js:337:11)
    at ModuleResolver._resolveFileOrDir (c:\workspace\react-native\habit-builder\node_modules\metro-bundler\src\node-haste\DependencyGraph\ModuleResolution.js:222:17)
    at ModuleResolver.resolveNodeDependency (c:\workspace\react-native\habit-builder\node_modules\metro-bundler\src\node-haste\DependencyGraph\ModuleResolution.js:236:19)
    at ResolutionRequest.resolveDependency (c:\workspace\react-native\habit-builder\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:111:14)
    at dependencyNames.map.name (c:\workspace\react-native\habit-builder\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:136:10)
    at Array.map (native)
    at ResolutionRequest.resolveModuleDependencies (c:\workspace\react-native\habit-builder\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:135:42)
    at Promise.resolve.then (c:\workspace\react-native\habit-builder\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:175:21)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```

keybindingsRegistry.ts:197 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  typescriptHero.resolve.addImportUnderCursor
e._assertNoCtrlAlt @ keybindingsRegistry.ts:197
keybindingsRegistry.ts:197 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  typescriptHero.resolve.addMissingImports
e._assertNoCtrlAlt @ keybindingsRegistry.ts:197
keybindingsRegistry.ts:197 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  typescriptHero.resolve.organizeImports
e._assertNoCtrlAlt @ keybindingsRegistry.ts:197
extensionService.ts:437 [C:\Users\Nolan\.vscode\extensions\xabikos.javascriptsnippets-1.5.0]: Unknown language in `contributes.JavaScriptSnippets.language`. Provided value: vue
e._logMessageInConsole @ extensionService.ts:437
console.ts:123 [Extension Host] Looking for parseable documents...
console.ts:123 [Extension Host] 2017-11-15T09:57:43.114Z - info: [DeclarationIndexMapper] initializing index mapper for 1 workspaces
console.ts:123 [Extension Host] 2017-11-15T09:57:43.116Z - debug: [DeclarationIndexMapper] initialize index for "c:\workspace\react-native\habit-builder"
console.ts:123 [Extension Host] 2017-11-15T09:57:43.129Z - info: [DeclarationIndexMapper] initialized
console.ts:123 [Extension Host] 2017-11-15T09:57:43.130Z - debug: [TypeScriptHero] activation event, initializing
console.ts:123 [Extension Host] 2017-11-15T09:57:43.131Z - info: [ImportResolveExtension] initialized
console.ts:123 [Extension Host] 2017-11-15T09:57:43.131Z - info: [CodeCompletionExtension] initialized
console.ts:123 [Extension Host] 2017-11-15T09:57:43.132Z - info: [DocumentSymbolStructureExtension] initialized
console.ts:123 [Extension Host] 2017-11-15T09:57:43.133Z - info: [CodeActionCreator] initialized
console.ts:123 [Extension Host] 2017-11-15T09:57:43.133Z - info: [OrganizeImportsOnSaveExtension] initialized
console.ts:123 [Extension Host] 2017-11-15T09:57:43.133Z - info: [TypeScriptHero] initialized
shell.ts:459 Unable to write to User Settings because sync.version is not a registered configuration.: Error: Unable to write to User Settings because sync.version is not a registered configuration.
    at new t (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10:303516)
    at e.wrapError (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10:307475)
    at e.resolveAndValidate (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10:310219)
    at e.doWriteConfiguration (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10:304369)
    at Object.factory (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10:304102)
    at t.e.consume (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:103671)
    at e.queue (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:103458)
    at new n.Class.derive._oncancel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:69553)
    at t.e.queue (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:103373)
    at e.writeConfiguration (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10:304076)
e.onUnexpectedError @ shell.ts:459
console.ts:123 [Extension Host] Found all parseable documents.
console.ts:123 [Extension Host] Parsing documents and looking for CSS class definitions...
console.ts:123 [Extension Host] 2017-11-15T09:57:47.053Z - info: [DeclarationIndexMapper] built index for workspace "habit-builder" {"durationMs":3937}
console.ts:123 [Extension Host] 2017-11-15T09:57:48.711Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] Summary:
console.ts:123 [Extension Host]% 134 parseable documents found
console.ts:123 [Extension Host]% 75834 CSS class definitions found
console.ts:123 [Extension Host]% 998 unique CSS class definitions found
console.ts:123 [Extension Host]% 3 failed attempts to parse. List of the documents:
console.ts:123 [Extension Host] /c:/workspace/react-native/habit-builder/node_modules/convert-source-map/test/fixtures/map-file-comment-double-slash.css
/c:/workspace/react-native/habit-builder/node_modules/serve-index/public/directory.html
/c:/workspace/react-native/habit-builder/node_modules/errorhandler/public/error.html

console.ts:123 [Extension Host] 2017-11-15T09:57:53.550Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T09:57:53.551Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T09:57:53.838Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] (node:5060) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ console.ts:123
console.ts:123 [Extension Host] 2017-11-15T10:02:09.721Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:02:09.759Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:02:09.762Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:09.763Z - info: [CodeActionCreator] calculated diagnostics {"durationMs":1}
console.ts:123 [Extension Host] 2017-11-15T10:02:09.765Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:02:10.017Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:02:10.316Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:02:10.783Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:10.783Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:11.161Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:11.161Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:11.639Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:11.640Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:12.109Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:12.110Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:13.311Z - debug: [CodeCompletionExtension] provide code completion for "C"
console.ts:123 [Extension Host] 2017-11-15T10:02:13.344Z - info: [CodeCompletionExtension] calculated code completions {"durationMs":33}
console.ts:123 [Extension Host] 2017-11-15T10:02:13.477Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:13.477Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:13.687Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:13.688Z - debug: [MissingImportCreator] class not found in index {"meta":{"specifier":"C"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:13.688Z - info: [CodeActionCreator] calculated diagnostics {"durationMs":1}
console.ts:123 [Extension Host] 2017-11-15T10:02:14.622Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:14.622Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:14.825Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:14.825Z - debug: [MissingImportCreator] class not found in index {"meta":{"specifier":"Consol'. Did you mean 'Console"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:14.825Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:15.465Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:15.465Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:15.692Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:15.692Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:15.801Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:15.802Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:16.023Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:16.023Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:17.302Z - debug: [CodeCompletionExtension] did not match criteria to provide intellisense {"meta":{"searchWord":"Log","lineText":"    Console.Log","indexReady":true}}
console.ts:123 [Extension Host] 2017-11-15T10:02:17.533Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:17.533Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:17.800Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:17.801Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:18.032Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:18.032Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:18.517Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:18.517Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:18.731Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:18.731Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:19.172Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:19.172Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:19.394Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:19.394Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:20.053Z - debug: [CodeCompletionExtension] did not match criteria to provide intellisense {"meta":{"searchWord":"l","lineText":"    Console.l","indexReady":true}}
console.ts:123 [Extension Host] 2017-11-15T10:02:20.638Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:20.638Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:20.859Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:20.859Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:21.868Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:21.868Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:22.064Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:22.064Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:22.480Z - debug: [CodeCompletionExtension] did not match criteria to provide intellisense {"meta":{"searchWord":"log","lineText":"    Console.log","indexReady":true}}
console.ts:123 [Extension Host] 2017-11-15T10:02:22.716Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:22.716Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:22.938Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:22.938Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:24.225Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:24.225Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:24.421Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:24.421Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:25.173Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:25.173Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:25.476Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:25.476Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:25.669Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:25.669Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:25.960Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:25.960Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:26.158Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:26.158Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:26.430Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:26.430Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:26.666Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:26.666Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:26.853Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:26.853Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:27.077Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:27.077Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:31.146Z - debug: [CodeCompletionExtension] provide code completion for "c"
console.ts:123 [Extension Host] 2017-11-15T10:02:31.150Z - info: [CodeCompletionExtension] calculated code completions {"durationMs":4}
console.ts:123 [Extension Host] 2017-11-15T10:02:32.846Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:32.846Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:33.121Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:33.121Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:34.383Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:34.383Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:35.287Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"c:\\workspace\\react-native\\habit-builder\\App.tsx"}}
console.ts:123 [Extension Host] 2017-11-15T10:02:35.287Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] 2017-11-15T10:02:36.422Z - debug: [OrganizeImportsOnSaveExtension] organizeOnSave is deactivated through config
console.ts:123 [Extension Host] 2017-11-15T10:02:36.435Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:02:36.979Z - debug: [DeclarationIndexMapper] rebuilding index for index "c:\workspace\react-native\habit-builder"
console.ts:123 [Extension Host] 2017-11-15T10:02:36.996Z - info: [DeclarationIndexMapper] rebuilt index for workspace "habit-builder" {"durationMs":17}
console.ts:123 [Extension Host] 2017-11-15T10:05:25.248Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:05:25.520Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:05:28.413Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:05:28.414Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:05:28.474Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:05:28.655Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] Congratulations, your extension "expand-region" is now active!
console.ts:123 [Extension Host] lala
console.ts:123 [Extension Host] add position 0
console.ts:123 [Extension Host]% 0
console.ts:123 [Extension Host] 2017-11-15T10:07:13.217Z - debug: [OrganizeImportsOnSaveExtension] organizeOnSave is deactivated through config
console.ts:123 [Extension Host] 2017-11-15T10:07:13.228Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:09:52.573Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
2console.ts:123 [Extension Host] 2017-11-15T10:09:52.574Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:09:53.063Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:09:53.690Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:09:53.691Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:09:53.692Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:10:06.433Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:10:06.475Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:10:07.272Z - debug: [DeclarationIndexMapper] rebuilding index for index "c:\workspace\react-native\habit-builder"
console.ts:123 [Extension Host] 2017-11-15T10:10:07.301Z - info: [DeclarationIndexMapper] rebuilt index for workspace "habit-builder" {"durationMs":29}
console.ts:123 [Extension Host] 2017-11-15T10:10:19.887Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:11:13.471Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:11:18.649Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:11:37.845Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2017-11-15T10:11:40.212Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
```

**Comment by iTOYS** [comment]
Hi @strake7 
Thanks for reporting!
Issue have been fixed, new release of extension will be soon

**Comment by strake7** [comment]
@iTOYS Appreciate the prompt fix! You guys are awesome.
