### ISSUE TITLE
Extension not starting "reactNative.startPackager not found"

### ISSUE THREAD

**Issue by Jarrio** [Microsoft/vscode-react-native#598]
## Actual Behavior
1. `F1` > Start Packager
2.  Alert saying: "Error: command 'reactNative.startPackager' not found"

## Expected Behavior
1. `F1` > Start Packager
2. Packager Starts

## Software versions
- React-Native VS Code extension version: 0.5.4
- VSCode version: 1.18.1 
- OS platform and version: Windows 10 64-Bit
- NodeJS version: 8.7.0
- React Native version:  0.48.0

## Outputs (Include if relevant)
```
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9 [Extension Host] Activating extension `vsmobile.vscode-react-native` failed: Cannot find module 'ws'.
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9 Activating extension `vsmobile.vscode-react-native` failed: Cannot find module 'ws'.
e._logMessageInConsole @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9 [Extension Host] Activating extension `vsmobile.vscode-react-native` failed:  Cannot find module 'ws'
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9 [Extension Host] Here is the error stack:  Error: Cannot find module 'ws'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:484450)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\Jazz\.vscode\extensions\vsmobile.vscode-react-native-0.5.4\src\common\remoteExtension.js:6:19)
	at Object.<anonymous> (C:\Users\Jazz\.vscode\extensions\vsmobile.vscode-react-native-0.5.4\src\common\remoteExtension.js:53:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9 command 'reactNative.startPackager' not found
e.doShow @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9
```

This might be related to me using a different project structure again #561. I should also mention that before this `0.5.4` version the error I mentioned at the end of the above issue wasn't fixed, I would still get "Project is not a react native project" but it would still start-up and `F1` -> `React-Native Run-Android` also had the same issue except it just didn't work at all

**Comment by callagga** [comment]
have also been getting:
`
[Error] Error: Error while executing command 'react-native run-ios --simulator --no-packager': spawn react-native ENOENT
`

If I then (in vscode) click on terminal I can run react-native e.g.
```
Gregs-MacBook-Pro:testNavigation Greg$ react-native -v
react-native-cli: 2.0.1
react-native: 0.50.3
Gregs-MacBook-Pro:testNavigation Greg$

```

**Comment by iTOYS** [comment]
Hi @Jarrio 

Could you please try again with 0.5.5 extension

**Comment by callagga** [comment]
just fixed it for me iTOYS!  thanks very much
