### ISSUE TITLE
TypeError: undefined: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by garciawarneckee** [Microsoft/vscode-react-native#615]
## Actual Behavior
1. Run "attach to packager" debug config
2. The title message appear

## Expected Behavior
1. Run the same debug config
2. Start to debug my RN Expo app

## Software versions
- React-Native VS Code extension version: 0.5.7
- VSCode version: 1.19.1
- OS platform and version: macOS High Sierra 10.13.2 
- NodeJS version: v9.3.0
- React Native version: 2.0.1 (react-native-cli), 

## Outputs (Include if relevant)

- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Error] undefined

Stack: TypeError: undefined: Cannot read property 'message' of undefined
	at Function.getWrappedError (/Users/esteban/.vscode/extensions/vsmobile.vscode-react-native-0.5.7/src/common/error/internalError.js:35:16)
	at Function.wrapError (/Users/esteban/.vscode/extensions/vsmobile.vscode-react-native-0.5.7/src/common/error/errorHelper.js:18:44)
	at __dirname.handleErrors.resultOfCode.done.reason (/Users/esteban/.vscode/extensions/vsmobile.vscode-react-native-0.5.7/src/common/entryPointHandler.js:40:72)
	at _rejected (/Users/esteban/.vscode/extensions/vsmobile.vscode-react-native-0.5.7/node_modules/q/q.js:844:24)
	at /Users/esteban/.vscode/extensions/vsmobile.vscode-react-native-0.5.7/node_modules/q/q.js:870:30
	at Promise.when (/Users/esteban/.vscode/extensions/vsmobile.vscode-react-native-0.5.7/node_modules/q/q.js:1122:31)
	at Promise.__dirname.Promise.promise.promiseDispatch (/Users/esteban/.vscode/extensions/vsmobile.vscode-react-native-0.5.7/node_modules/q/q.js:788:41)
	at /Users/esteban/.vscode/extensions/vsmobile.vscode-react-native-0.5.7/node_modules/q/q.js:604:44
	at runSingle (/Users/esteban/.vscode/extensions/vsmobile.vscode-react-native-0.5.7/node_modules/q/q.js:137:13)
	at flush (/Users/esteban/.vscode/extensions/vsmobile.vscode-react-native-0.5.7/node_modules/q/q.js:125:13)```

**Comment by jwargo** [comment]
Are you following the [Debugging Expo applications](https://github.com/Microsoft/vscode-react-native/blob/master/doc/expo.md) instructions? You should, I think, be executing `Debug in Exponent` to debug the app

**Comment by garciawarneckee** [comment]
No matter what I do if I use "Attach to packager" one or "Debug in Exponent" the message is the same.. In both cases the output in the terminal is blank and VS Code spawn an alert "Debug adapter process has terminated unexpectedly".

**Comment by iTOYS** [comment]
Hi @garciawarneckee 
Is it CRAN or `exp init` project?

I've tried [falta-uno-app](https://github.com/garciawarneckee/falta-uno-app) from your Github and it works great for me

**Comment by garciawarneckee** [comment]
CRAN

**Comment by iTOYS** [comment]
Yes, I meant `create-react-native-app`.
Could you please check outputs one more time and paste here if not empty
```
* Output of the Debug Console (View -> Toggle Debug Console)
* Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox)
* Output of the React-Native: Android output channel (View -> Toggle Output -> Select React-Native: Android in ListBox)
* Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab)
```
Also if it possible, could you please create a little project to repro

**Comment by sergey-akhalkov** [comment]
Hi @garciawarneckee, just a friendly ping, please let me know if the issue still has place for you and if you have a chance to take a look at the message above.

**Comment by jpsouzasilva** [comment]
Trying to run on Android gives me the same error message.

Command Pallette -> Run Android on Simulator

```
[Error] Failed to run the application in Android

Stack: TypeError: Failed to run the application in Android: Cannot read property 'message' of undefined
	at Function.getWrappedError (C:\Users\joaopaulo\.vscode\extensions\vsmobile.vscode-react-native-0.5.7\src\common\error\internalError.js:35:16)
	at Function.wrapError (C:\Users\joaopaulo\.vscode\extensions\vsmobile.vscode-react-native-0.5.7\src\common\error\errorHelper.js:18:44)
	at resultOfCode.done.reason (C:\Users\joaopaulo\.vscode\extensions\vsmobile.vscode-react-native-0.5.7\src\common\entryPointHandler.js:40:72)
	at _rejected (C:\Users\joaopaulo\.vscode\extensions\vsmobile.vscode-react-native-0.5.7\node_modules\q\q.js:844:24)
	at C:\Users\joaopaulo\.vscode\extensions\vsmobile.vscode-react-native-0.5.7\node_modules\q\q.js:870:30
	at Promise.when (C:\Users\joaopaulo\.vscode\extensions\vsmobile.vscode-react-native-0.5.7\node_modules\q\q.js:1122:31)
	at Promise.promise.promiseDispatch (C:\Users\joaopaulo\.vscode\extensions\vsmobile.vscode-react-native-0.5.7\node_modules\q\q.js:788:41)
	at C:\Users\joaopaulo\.vscode\extensions\vsmobile.vscode-react-native-0.5.7\node_modules\q\q.js:604:44
	at runSingle (C:\Users\joaopaulo\.vscode\extensions\vsmobile.vscode-react-native-0.5.7\node_modules\q\q.js:137:13)
	at flush (C:\Users\joaopaulo\.vscode\extensions\vsmobile.vscode-react-native-0.5.7\node_modules\q\q.js:125:13)
	at _combinedTickCallback (internal/process/next_tick.js:73:7)
	at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

When trying to Debug -> Debug Android it gives me another error.

I have noticed the `launchReactNative.js` is not being generated when I open the project (CRAN) from the CLI, Open Folder or Open With VSCode from explorer.

package.json

```
{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "jest-expo": "25.0.0",
    "react-native-scripts": "1.11.1",
    "react-test-renderer": "16.2.0"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^6.2.2",
    "expo": "^25.0.0",
    "native-base": "^2.3.7",
    "react": "16.2.0",
    "react-native": "0.52.0"
  }
}
```

If I'm missing some configuration step, let me know :)

**Comment by jpsouzasilva** [comment]
@sergey-akhalkov I could track down what was the problem in my case. I was missing `react-native-cli` from my global modules.

So what I had to do was `npm install -g react-native-cli` and it got the packager to start.

**Comment by sergey-akhalkov** [comment]
@garciawarneckee, I'm closing this for now, please feel free to reopen or create new one if you have any updates.

@jpsouzasilva, sorry for the delayed response, I'm closing this issue, so could you please create new one if the issue still has place for you and share your problem and environment there?

**Comment by kashishgrover** [comment]
even I get the same problem
```

[Error] Failed to start the React Native packager

Stack: TypeError: Failed to start the React Native packager: Cannot read property 'message' of undefined
	at Function.getWrappedError (/Users/kashishgrover/.vscode/extensions/vsmobile.vscode-react-native-0.6.6/src/common/error/internalError.js:35:16)
	at Function.wrapError (/Users/kashishgrover/.vscode/extensions/vsmobile.vscode-react-native-0.6.6/src/common/error/errorHelper.js:18:44)
	at resultOfCode.done.reason (/Users/kashishgrover/.vscode/extensions/vsmobile.vscode-react-native-0.6.6/src/common/entryPointHandler.js:40:72)
	at _rejected (/Users/kashishgrover/.vscode/extensions/vsmobile.vscode-react-native-0.6.6/node_modules/q/q.js:844:24)
	at /Users/kashishgrover/.vscode/extensions/vsmobile.vscode-react-native-0.6.6/node_modules/q/q.js:870:30
	at Promise.when (/Users/kashishgrover/.vscode/extensions/vsmobile.vscode-react-native-0.6.6/node_modules/q/q.js:1122:31)
	at Promise.promise.promiseDispatch (/Users/kashishgrover/.vscode/extensions/vsmobile.vscode-react-native-0.6.6/node_modules/q/q.js:788:41)
	at /Users/kashishgrover/.vscode/extensions/vsmobile.vscode-react-native-0.6.6/node_modules/q/q.js:604:44
	at runSingle (/Users/kashishgrover/.vscode/extensions/vsmobile.vscode-react-native-0.6.6/node_modules/q/q.js:137:13)
	at flush (/Users/kashishgrover/.vscode/extensions/vsmobile.vscode-react-native-0.6.6/node_modules/q/q.js:125:13)
	at _combinedTickCallback (internal/process/next_tick.js:73:7)
	at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by ruslan-bikkinin** [comment]
Hi @kashishgrover please double-check whether you open React Native based project not the directory on the upper/lower level of it.

**Comment by kashishgrover** [comment]
@ruslan-bikkinin oh shit thank you so much. We use a Monorepo structure and I never thought that could be the issue. It works flawlessly now. 😄
