### ISSUE TITLE
Error: EBADF: bad file descriptor, uv_pipe_open

### ISSUE THREAD

**Issue by icahnchen** [Microsoft/vscode-react-native#680]
## Actual Behavior
1. Debug-Debug Android

## Expected Behavior
1.  Can debug program normal

## Software versions
- React-Native VS Code extension version: 0.6.6
- VSCode version: 1.23.0-insider
- OS platform and version: win10 x64
- NodeJS version: 9.10.1
- React Native version: 2.0.1

The exception information as below:
Error: EBADF: bad file descriptor, uv_pipe_open
child_process.js:108
    at Object.exports._forkChild (child_process.js:108:5)
    at Object.setupChannel (internal/process.js:222:30)
    at startup (bootstrap_node.js:63:14)
    at bootstrap_node.js:666:3
```

**Comment by annakocheshkova** [comment]
@icahnchen thank you for your request! I'm not sure how to reproduce it, make sure the issue is reproduced on a stable version of VSCode and if yes, give us some more details, a minimal working version of the project would be great.

**Comment by icahnchen** [comment]
@annakocheshkova Thanks for your reply.  
Here is my detailed procedure...
I  initiated the new project reference React-Native site: [React Native-
      Building Projects with Native Code](https://facebook.github.io/react-native/docs/getting-started.html), and created the launch.json as below:
`{
	"version": "0.2.0",
	"configurations": [
	
		{
			"name": "Debug Android",
			"program": "${workspaceRoot}/.vscode/launchReactNative.js",
			"type": "reactnative",
			"request": "launch",
			"platform": "android",
			"sourceMaps": true,
			"outDir": "${workspaceRoot}/.vscode/.react"
		},
		{
			"name": "Debug iOS",
			"program": "${workspaceRoot}/.vscode/launchReactNative.js",
			"type": "reactnative",
			"request": "launch",
			"platform": "ios",
			"sourceMaps": true,
			"outDir": "${workspaceRoot}/.vscode/.react"
		},
		{
			"name": "Attach to packager",
			"program": "${workspaceRoot}/.vscode/launchReactNative.js",
			"type": "reactnative",
			"request": "attach",
			"sourceMaps": true,
			"outDir": "${workspaceRoot}/.vscode/.react"
		},
		{
			"name": "Debug in Exponent",
			"program": "${workspaceRoot}/.vscode/launchReactNative.js",
			"type": "reactnative",
			"request": "launch",
			"platform": "exponent",
			"sourceMaps": true,
			"outDir": "${workspaceRoot}/.vscode/.react"
		}
	]
}`
and then Debug with 'Debug Android'.

## **React Native:Run android output information**
`[Warning] Target simulator is not supported for Android platform. If you want to use particular device or simulator for launching Android app, please specify  device id (as in 'adb devices' output) instead.

[Info] Starting React Native Packager.

Scanning folders for symlinks in c:\Projects\AwesomeProject\node_modules (77ms)
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee130Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore130Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp3130Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0552Library UP-TO-DATE
:app:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:transformClassesWithDexForDebug UP-TO-DATE
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateSigningDebug
:app:packageDebug UP-TO-DATE
:app:assembleDebug UP-TO-DATE
:app:installDebug
Installing APK 'app-debug.apk' on 'Pixel_XL_API_23(AVD) - 6.0' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 18.988 secs
Running C:\Android\Sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
Starting the app on emulator-5554 (C:\Android\Sdk/platform-tools/adb -s emulator-5554 shell am start -n com.awesomeproject/com.awesomeproject.MainActivity)...
Starting: Intent { cmp=com.awesomeproject/.MainActivity }`

## React Native output Info
`Starting custom debugger by executing: echo A debugger is not needed:  "c:\Projects\AwesomeProject"
Starting custom debugger by executing: echo A debugger is not needed:  "c:\Projects\AwesomeProject"
Starting custom debugger by executing: echo A debugger is not needed:  "c:\Projects\AwesomeProject"
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (481/481), done.`

## LogCat - emulator-5554 output info
`[Info] 04-17 14:24:18.371  5086  5086 D ReactNative: ReactInstanceManager.onReloadWithJSDebugger()

04-17 14:24:18.371  5086  5086 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()

04-17 14:24:18.371  5086  5086 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()



[Info] 04-17 14:24:20.080  5163  5163 D ReactNative: ReactInstanceManager.ctor()



[Info] 04-17 14:24:20.115  5163  5163 D ReactNative: ReactInstanceManager.createReactContextInBackground()



[Info] 04-17 14:24:20.115  5163  5163 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()



[Info] 04-17 14:24:20.169  5163  5163 D ReactNative: ReactInstanceManager.onReloadWithJSDebugger()



[Info] 04-17 14:24:20.170  5163  5163 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()



[Info] 04-17 14:24:20.170  5163  5163 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()



[Info] 04-17 14:24:25.480  5163  5182 D ReactNative: ReactInstanceManager.createReactContext()



[Info] 04-17 14:24:25.724  5163  5182 D ReactNative: Initializing React Xplat Bridge.



[Info] 04-17 14:24:25.813  5163  5182 D ReactNative: Initializing React Xplat Bridge before initializeBridge



[Info] 04-17 14:24:25.826  5163  5182 D ReactNative: Initializing React Xplat Bridge after initializeBridge



[Info] 04-17 14:24:25.826  5163  5182 D ReactNative: CatalystInstanceImpl.runJSBundle()



[Info] 04-17 14:24:25.828  5163  5196 D ReactNative: ReactInstanceManager.setupReactContext()

04-17 14:24:25.828  5163  5196 D ReactNative: CatalystInstanceImpl.initialize()

04-17 14:24:25.829  5163  5196 D ReactNative: ReactInstanceManager.attachRootViewToInstance()`

## Debug Console info
`OS: win32 x64
Adapter node: v8.9.3 x64
vscode-chrome-debug-core: 3.23.0
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Debugger worker loaded runtime on port 22162
Error: EBADF: bad file descriptor, uv_pipe_open
child_process.js:108
    at Object.exports._forkChild (child_process.js:108:5)
    at Object.setupChannel (internal/process.js:222:30)
    at startup (internal/bootstrap/node.js:68:14)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)`

**Comment by icahnchen** [comment]
@annakocheshkova I have installed the stable version of VSCode 1.22.2, the issue also exist...
My operation as below:

1.  install the stable version of VSCode.
2.  install the React-Native tools extension
3.  yarn global add react-native-cli
4.  react-native init awsomeProject
5.  cd the project folder
6.  react-native run-android   -----------this command executed sucessfully
7.  add react-native debug config file as default,
8.  switch to the 'Debug Android', and the debug.
9.  the issue still exist...

## Debug Console output infor
`OS: win32 x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.23.0
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Debugger worker loaded runtime on port 30676
Error: EBADF: bad file descriptor, uv_pipe_open
child_process.js:108
    at Object.exports._forkChild (child_process.js:108:5)
    at Object.setupChannel (internal/process.js:222:30)
    at startup (internal/bootstrap/node.js:68:14)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
`
[awsomeProject.zip](https://github.com/Microsoft/vscode-react-native/files/1926344/awsomeProject.zip)

**Comment by annakocheshkova** [comment]
@icahnchen I just tried the whole workflow you described once again, everything works. 
Still, I can not help but notice that in the project you sent there are no `android` and `ios` folders, which should exist, if you have used `react-native init`, so please verify that.
Also I can suggest you to open an issue [here](https://github.com/nodejs/node/issues), maybe the guys will help you with it, because clearly the issue is on their side.

**Comment by koliapp2019** [comment]
We also have this issue. Any update on how to resolve this?
