### ISSUE TITLE
Debug seems to ignore rn-cli.config.js

### ISSUE THREAD

**Issue by rodrigoelp** [Microsoft/vscode-react-native#743]
## What I am trying to do.
I've been trying to debug this app (https://github.com/pniko/chain-react-2018 - final branch) in a real device and the packager fails to bundle the models present in the assets folder.

## Steps to reproduce in iOS
1. (assuming provisioning profile was correctly configured), add a new configuration to debug on a real device
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug iOS (device)",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "launch",
            "platform": "ios",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/.vscode/.react",
            "runArguments": [
                "--device", "Uber Super Phone"
            ]
        },
    ]
}
```
2. Make sure the application has the rn-cli.config.js as:
```javascript
module.exports = {
    getTransformModulePath() {
      return require.resolve('react-native-typescript-transformer');
    },
    getSourceExts() {
      return ['ts', 'tsx'];
    },
    getAssetExts() {
      return ['pb', 'txt'] // vscode rn packager will ignore this.
    }
  }
```
3. Hit the debug button to get the packager launched and the compilation process to deploy to the device (assuming the device is connected to the mac).
4. Once it has deployed try to open the app

## Actual Behavior
1. The application crashes saying:
```
`/path/chain-react-2018/src/screens/welcomeScreen.tsx`: The module `../../assets/model.pb` could not be found from `/path/welcomeScreen.tsx`. Indeed, none of these files exist:
```
2. The packager reports the same issue.

## Expected Behavior
1. It loads the app?

## Checking a different packager
1. Stops the rntools packager.
2. run `yarn start` from the home of the project
3. kill the iOS app and launch it again. This time it should load the model correctly.

## Software versions
- React-Native VS Code extension version: 0.6.12
- VSCode version: Version 1.25.0-insider (1.25.0-insider) 2018-06-25T09:26:09.607Z
- OS platform and version: MacOS 10.13.5
- NodeJS version: v8.11.2
- React Native version:  react-native-cli: 2.0.1, react-native: 0.54.4
- Expo SDK version (include if relevant): NA

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.17.3
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Disconnected from the Proxy (Packager) to the React Native application. Retrying reconnection soon...
```

- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Info] Starting Packager

Scanning folders for symlinks in /path/chain-react-2018/node_modules (13ms)
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   /path/chain-react-2018
   /path/chain-react-2018/.vscode 


Metro Bundler ready.

Loading dependency graph, done.
[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.bundle?platform=ios

[Info] Building and running application.

error: bundling failed: Error: Unable to resolve module `../../assets/model.pb` from `/path/chain-react-2018/src/screens/welcomeScreen.tsx`: The module `../../assets/model.pb` could not be found from `/path/chain-react-2018/src/screens/welcomeScreen.tsx`. Indeed, none of these files exist:

  * `/path/chain-react-2018/assets/model.pb(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/path/chain-react-2018/assets/model.pb/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/path/chain-react-2018/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:865)
    at ResolutionRequest.resolveDependency (/path/chain-react-2018/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:92:16)
    at DependencyGraph.resolveDependency (/path/chain-react-2018/node_modules/metro/src/node-haste/DependencyGraph.js:271:4465)
    at dependencies.map.relativePath (/path/chain-react-2018/node_modules/metro/src/DeltaBundler/traverseDependencies.js:379:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/path/chain-react-2018/node_modules/metro/src/DeltaBundler/traverseDependencies.js:378:16)
    at /path/chain-react-2018/node_modules/metro/src/DeltaBundler/traverseDependencies.js:203:33
    at Generator.next (<anonymous>)
    at step (/path/chain-react-2018/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:307)
    at /path/chain-react-2018/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:467
 BUNDLE  [ios, dev] ./index.js ▓░░░░░░░░░░░░░░░ 9.5% (61/224), failed.

[Info] Enable JS Debugging

error: bundling failed: Error: Unable to resolve module `../../assets/model.pb` from `/path/chain-react-2018/src/screens/welcomeScreen.tsx`: The module `../../assets/model.pb` could not be found from `/path/chain-react-2018/src/screens/welcomeScreen.tsx`. Indeed, none of these files exist:

  * `/path/chain-react-2018/assets/model.pb(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/path/chain-react-2018/assets/model.pb/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/path/chain-react-2018/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:865)
    at ResolutionRequest.resolveDependency (/path/chain-react-2018/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:92:16)
    at DependencyGraph.resolveDependency (/path/chain-react-2018/node_modules/metro/src/node-haste/DependencyGraph.js:271:4465)
    at dependencies.map.relativePath (/path/chain-react-2018/node_modules/metro/src/DeltaBundler/traverseDependencies.js:379:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/path/chain-react-2018/node_modules/metro/src/DeltaBundler/traverseDependencies.js:378:16)
    at /path/chain-react-2018/node_modules/metro/src/DeltaBundler/traverseDependencies.js:203:33
    at Generator.next (<anonymous>)
    at step (/path/chain-react-2018/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:307)
    at /path/chain-react-2018/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:467
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

Starting custom debugger by executing: echo A debugger is not needed:  "/path/chain-react-2018" "/path/chain-react-2018/.vscode"
error: bundling failed: Error: Unable to resolve module `../../assets/model.pb` from `/path/chain-react-2018/src/screens/welcomeScreen.tsx`: The module `../../assets/model.pb` could not be found from `/path/chain-react-2018/src/screens/welcomeScreen.tsx`. Indeed, none of these files exist:

  * `/path/chain-react-2018/assets/model.pb(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/path/chain-react-2018/assets/model.pb/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/path/chain-react-2018/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:865)
    at ResolutionRequest.resolveDependency (/path/chain-react-2018/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:92:16)
    at DependencyGraph.resolveDependency (/path/chain-react-2018/node_modules/metro/src/node-haste/DependencyGraph.js:271:4465)
    at dependencies.map.relativePath (/path/chain-react-2018/node_modules/metro/src/DeltaBundler/traverseDependencies.js:379:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/path/chain-react-2018/node_modules/metro/src/DeltaBundler/traverseDependencies.js:378:16)
    at /path/chain-react-2018/node_modules/metro/src/DeltaBundler/traverseDependencies.js:203:33
    at Generator.next (<anonymous>)
    at step (/path/chain-react-2018/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:307)
    at /path/chain-react-2018/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:467
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
[Extension Host] 2018-07-11T22:07:49.439Z - debug: [CodeOutline] activeWindowChanged, reparsing (at ConsoleLogTransport.log (/Users/rod/.vscode-insiders/extensions/rbbit.typescript-hero-2.3.2/out/src/utilities/logger.js:45:25))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:271 [Extension Host] 2018-07-11T22:07:51.336Z - debug: [CodeOutline] activeWindowChanged, reparsing (at ConsoleLogTransport.log (/Users/rod/.vscode-insiders/extensions/rbbit.typescript-hero-2.3.2/out/src/utilities/logger.js:45:25))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:271 [Extension Host] 2018-07-11T22:07:51.338Z - debug: [CodeOutline] activeWindowChanged, reparsing (at ConsoleLogTransport.log (/Users/rod/.vscode-insiders/extensions/rbbit.typescript-hero-2.3.2/out/src/utilities/logger.js:45:25))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:271 [Extension Host] 2018-07-11T22:07:54.567Z - debug: [CodeOutline] activeWindowChanged, reparsing (at ConsoleLogTransport.log (/Users/rod/.vscode-insiders/extensions/rbbit.typescript-hero-2.3.2/out/src/utilities/logger.js:45:25))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:271 [Extension Host] 2018-07-11T22:09:03.629Z - debug: [CodeOutline] activeWindowChanged, reparsing (at ConsoleLogTransport.log (/Users/rod/.vscode-insiders/extensions/rbbit.typescript-hero-2.3.2/out/src/utilities/logger.js:45:25))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:271 [Extension Host] 2018-07-11T22:09:07.968Z - debug: [CodeOutline] activeWindowChanged, reparsing (at ConsoleLogTransport.log (/Users/rod/.vscode-insiders/extensions/rbbit.typescript-hero-2.3.2/out/src/utilities/logger.js:45:25))
```

**Comment by iTOYS** [comment]
Hi @rodrigoelp 
Thanks for reporting! Fix will arrive with a new release.
As a workaround you can run packager manually `react-native start` and after that run debugger from VSCode.

Thanks!
