### ISSUE TITLE
Error when stopping packager using "React Native: Stop Packager"

### ISSUE THREAD

**Issue by sregg** [Microsoft/vscode-react-native#752]
## Actual Behavior
1. use command "React Native: Stop Packager"
2. the packager seems stopped but I see this error in the logs:

```[Info] Stopping Packager

[Info] Packager stopped

[Error] Failed to stop the React Native packager

Stack: XDLError: Failed to stop the React Native packager: Not logged in
    at Function.getWrappedError (/Users/simonreggiani/.vscode/extensions/vsmobile.vscode-react-native-0.6.12/src/common/error/internalError.js:35:16)
    at Function.wrapError (/Users/simonreggiani/.vscode/extensions/vsmobile.vscode-react-native-0.6.12/src/common/error/errorHelper.js:18:44)
    at resultOfCode.done.reason (/Users/simonreggiani/.vscode/extensions/vsmobile.vscode-react-native-0.6.12/src/common/entryPointHandler.js:43:72)
    at _rejected (/Users/simonreggiani/.vscode/extensions/vsmobile.vscode-react-native-0.6.12/node_modules/q/q.js:844:24)
    at /Users/simonreggiani/.vscode/extensions/vsmobile.vscode-react-native-0.6.12/node_modules/q/q.js:870:30
    at Promise.when (/Users/simonreggiani/.vscode/extensions/vsmobile.vscode-react-native-0.6.12/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/Users/simonreggiani/.vscode/extensions/vsmobile.vscode-react-native-0.6.12/node_modules/q/q.js:788:41)
    at /Users/simonreggiani/.vscode/extensions/vsmobile.vscode-react-native-0.6.12/node_modules/q/q.js:604:44
    at runSingle (/Users/simonreggiani/.vscode/extensions/vsmobile.vscode-react-native-0.6.12/node_modules/q/q.js:137:13)
    at flush (/Users/simonreggiani/.vscode/extensions/vsmobile.vscode-react-native-0.6.12/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

3. When executing the same command again, I get this log:

```[Warning] Error: Packager is not running```

## Expected Behavior
1. use command "React Native: Stop Packager"
2. the packager is stopped without any error

## Software versions
- React-Native VS Code extension version: 0.6.12
- VSCode version: 1.25.1
- OS platform and version: High Sierra 10.13.6
- NodeJS version: 8.11.3
- React Native version: 0.56

**Comment by 2hyjun** [comment]
Same Error on 
vscode: 0.6.13
vscode-react-native: 1.25.1
OS platform and version: OSX 10.13.3
NodeJS version: 8.10.0
RN version: 0.55.4
