### ISSUE TITLE
Debug  fails to load script in Typescript，  Unable to resolve module `../../fund/containers/index`

### ISSUE THREAD

**Issue by soeasyjx** [Microsoft/vscode-react-native#778]
I have not been able to successfully debug the application in using this extension in VSCode. It should be noted that running from console and using chrome dev tools works fine,

## Actual Behavior
Unable to resolve module `../../fund/containers/index` from `e:\rn_pro\fastman2\src\apps\routes\fund.rule.tsx`: The module `../../fund/containers/index` could not be found from `e:\rn_pro\fastman2\src\apps\routes\fund.rule.tsx`. Indeed, none of these files exist

The App file does exist (though is TSX) and has shown to work just using the commands in terminal.

## Expected Behavior
Able to load ../../fund/containers/index.ts and remotely debug the application in VSCode

## Software versions
- React-Native VS Code extension version: 0.6.14
- VSCode version: 1.26.1
- OS platform and version: 
- NodeJS version: 8.11.1
- React Native version: 0.55.4
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: win32 x64
Adapter node: v8.9.3 x64
vscode-chrome-debug-core: 3.17.3
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Debugger worker loaded runtime on port 11853
Couldn't import script at <http://localhost:8081/index.bundle?platform=android&dev=true&minify=false>. Debugging won't work: Try reloading the JS from inside the app, or Reconnect the VS Code debugger: {"originModulePath":"e:\\rn_pro\\fastman2\\src\\apps\\routes\\fund.rule.tsx","targetModuleName":"../../fund/containers/index","message":"Unable to resolve module `../../fund/containers/index` from `e:\\rn_pro\\fastman2\\src\\apps\\routes\\fund.rule.tsx`: The module `../../fund/containers/index` could not be found from `e:\\rn_pro\\fastman2\\src\\apps\\routes\\fund.rule.tsx`. Indeed, none of these files exist:\n\n  * `e:\\rn_pro\\fastman2\\src\\fund\\containers\\index(.native||.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.js|.native.js|.js|.android.json|.native.json|.json)`\n  * `e:\\rn_pro\\fastman2\\src\\fund\\containers\\index\\index(.native||.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.js|.native.js|.js|.android.json|.native.json|.json)`","errors":[{"description":"Unable to resolve module `../../fund/containers/index` from `e:\\rn_pro\\fastman2\\src\\apps\\routes\\fund.rule.tsx`: The module `../../fund/containers/index` could not be found from `e:\\rn_pro\\fastman2\\src\\apps\\routes\\fund.rule.tsx`. Indeed, none of these files exist:\n\n  * `e:\\rn_pro\\fastman2\\src\\fund\\containers\\index(.native||.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.[...]

```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Info] Starting Packager

Scanning folders for symlinks in e:\rn_pro\fastman2\src\apps\node_modules (158ms)
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   e:\rn_pro\fastman2\src\apps
   E:\rn_pro\fastman2\packages\fastman2-api-stylesheet
   E:\rn_pro\fastman2\packages\fastman2-global
   E:\rn_pro\fastman2\packages\fastman2-helper-logger
   E:\rn_pro\fastman2\src\demo
   E:\rn_pro\fastman2\src\example
   E:\rn_pro\fastman2\src\financing
   E:\rn_pro\fastman2\src\fund
   E:\rn_pro\fastman2\src\images
   E:\rn_pro\fastman2\packages\fastman2-component-animated-modal
   E:\rn_pro\fastman2\packages\fastman2-component-modal
   E:\rn_pro\fastman2\packages\fastman2-component-radio
   E:\rn_pro\fastman2\packages\fastman2-component-swiper
   E:\rn_pro\fastman2\packages\fastman2-helper-sectionlist
   E:\rn_pro\fastman2\packages\fastman2-api-animate 


Metro Bundler ready.

[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.bundle?platform=android

Loading dependency graph, done.
[Info] Building and running application.

error: bundling failed: Error: Unable to resolve module `../../fund/containers/index` from `e:\rn_pro\fastman2\src\apps\routes\fund.rule.tsx`: The module `../../fund/containers/index` could not be found from `e:\rn_pro\fastman2\src\apps\routes\fund.rule.tsx`. Indeed, none of these files exist:

  * `e:\rn_pro\fastman2\src\fund\containers\index(.native||.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `e:\rn_pro\fastman2\src\fund\containers\index\index(.native||.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.js|.native.js|.js|.android.json|.native.json|.json)`
    at ModuleResolver.resolveDependency (e:\rn_pro\fastman2\src\apps\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:161:851)
    at ResolutionRequest.resolveDependency (e:\rn_pro\fastman2\src\apps\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:91:16)
    at DependencyGraph.resolveDependency (e:\rn_pro\fastman2\src\apps\node_modules\metro\src\node-haste\DependencyGraph.js:272:4579)
    at dependencies.map.relativePath (e:\rn_pro\fastman2\src\apps\node_modules\metro\src\DeltaBundler\traverseDependencies.js:376:19)
    at Array.map (<anonymous>)
    at resolveDependencies (e:\rn_pro\fastman2\src\apps\node_modules\metro\src\DeltaBundler\traverseDependencies.js:374:16)
    at e:\rn_pro\fastman2\src\apps\node_modules\metro\src\DeltaBundler\traverseDependencies.js:212:33
    at Generator.next (<anonymous>)
    at step (e:\rn_pro\fastman2\src\apps\node_modules\metro\src\DeltaBundler\traverseDependencies.js:297:313)
    at e:\rn_pro\fastman2\src\apps\node_modules\metro\src\DeltaBundler\traverseDependencies.js:297:473
 BUNDLE  [android, dev] ./index.js ▓▓▓░░░░░░░░░░░░░ 21.2% (381/827), failed.

Starting custom debugger by executing: echo A debugger is not needed:  "e:\rn_pro\fastman2\src\apps" "E:\rn_pro\fastman2\packages\fastman2-api-stylesheet" "E:\rn_pro\fastman2\packages\fastman2-global" "E:\rn_pro\fastman2\packages\fastman2-helper-logger" "E:\rn_pro\fastman2\src\demo" "E:\rn_pro\fastman2\src\example" "E:\rn_pro\fastman2\src\financing" "E:\rn_pro\fastman2\src\fund" "E:\rn_pro\fastman2\src\images" "E:\rn_pro\fastman2\packages\fastman2-component-animated-modal" "E:\rn_pro\fastman2\packages\fastman2-component-modal" "E:\rn_pro\fastman2\packages\fastman2-component-radio" "E:\rn_pro\fastman2\packages\fastman2-component-swiper" "E:\rn_pro\fastman2\packages\fastman2-helper-sectionlist" "E:\rn_pro\fastman2\packages\fastman2-api-animate"
[Info] Enable JS Debugging

Starting custom debugger by executing: echo A debugger is not needed:  "e:\rn_pro\fastman2\src\apps" "E:\rn_pro\fastman2\packages\fastman2-api-stylesheet" "E:\rn_pro\fastman2\packages\fastman2-global" "E:\rn_pro\fastman2\packages\fastman2-helper-logger" "E:\rn_pro\fastman2\src\demo" "E:\rn_pro\fastman2\src\example" "E:\rn_pro\fastman2\src\financing" "E:\rn_pro\fastman2\src\fund" "E:\rn_pro\fastman2\src\images" "E:\rn_pro\fastman2\packages\fastman2-component-animated-modal" "E:\rn_pro\fastman2\packages\fastman2-component-modal" "E:\rn_pro\fastman2\packages\fastman2-component-radio" "E:\rn_pro\fastman2\packages\fastman2-component-swiper" "E:\rn_pro\fastman2\packages\fastman2-helper-sectionlist" "E:\rn_pro\fastman2\packages\fastman2-api-animate"
Starting custom debugger by executing: echo A debugger is not needed:  "e:\rn_pro\fastman2\src\apps" "E:\rn_pro\fastman2\packages\fastman2-api-stylesheet" "E:\rn_pro\fastman2\packages\fastman2-global" "E:\rn_pro\fastman2\packages\fastman2-helper-logger" "E:\rn_pro\fastman2\src\demo" "E:\rn_pro\fastman2\src\example" "E:\rn_pro\fastman2\src\financing" "E:\rn_pro\fastman2\src\fund" "E:\rn_pro\fastman2\src\images" "E:\rn_pro\fastman2\packages\fastman2-component-animated-modal" "E:\rn_pro\fastman2\packages\fastman2-component-modal" "E:\rn_pro\fastman2\packages\fastman2-component-radio" "E:\rn_pro\fastman2\packages\fastman2-component-swiper" "E:\rn_pro\fastman2\packages\fastman2-helper-sectionlist" "E:\rn_pro\fastman2\packages\fastman2-api-animate"
Starting custom debugger by executing: echo A debugger is not needed:  "e:\rn_pro\fastman2\src\apps" "E:\rn_pro\fastman2\packages\fastman2-api-stylesheet" "E:\rn_pro\fastman2\packages\fastman2-global" "E:\rn_pro\fastman2\packages\fastman2-helper-logger" "E:\rn_pro\fastman2\src\demo" "E:\rn_pro\fastman2\src\example" "E:\rn_pro\fastman2\src\financing" "E:\rn_pro\fastman2\src\fund" "E:\rn_pro\fastman2\src\images" "E:\rn_pro\fastman2\packages\fastman2-component-animated-modal" "E:\rn_pro\fastman2\packages\fastman2-component-modal" "E:\rn_pro\fastman2\packages\fastman2-component-radio" "E:\rn_pro\fastman2\packages\fastman2-component-swiper" "E:\rn_pro\fastman2\packages\fastman2-helper-sectionlist" "E:\rn_pro\fastman2\packages\fastman2-api-animate"
error: bundling failed: Error: Unable to resolve module `../../fund/containers/index` from `e:\rn_pro\fastman2\src\apps\routes\fund.rule.tsx`: The module `../../fund/containers/index` could not be found from `e:\rn_pro\fastman2\src\apps\routes\fund.rule.tsx`. Indeed, none of these files exist:

  * `e:\rn_pro\fastman2\src\fund\containers\index(.native||.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `e:\rn_pro\fastman2\src\fund\containers\index\index(.native||.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.js|.native.js|.js|.android.json|.native.json|.json)`
    at ModuleResolver.resolveDependency (e:\rn_pro\fastman2\src\apps\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:161:851)
    at ResolutionRequest.resolveDependency (e:\rn_pro\fastman2\src\apps\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:91:16)
    at DependencyGraph.resolveDependency (e:\rn_pro\fastman2\src\apps\node_modules\metro\src\node-haste\DependencyGraph.js:272:4579)
    at dependencies.map.relativePath (e:\rn_pro\fastman2\src\apps\node_modules\metro\src\DeltaBundler\traverseDependencies.js:376:19)
    at Array.map (<anonymous>)
    at resolveDependencies (e:\rn_pro\fastman2\src\apps\node_modules\metro\src\DeltaBundler\traverseDependencies.js:374:16)
    at e:\rn_pro\fastman2\src\apps\node_modules\metro\src\DeltaBundler\traverseDependencies.js:212:33
    at Generator.next (<anonymous>)
    at step (e:\rn_pro\fastman2\src\apps\node_modules\metro\src\DeltaBundler\traverseDependencies.js:297:313)
    at e:\rn_pro\fastman2\src\apps\node_modules\metro\src\DeltaBundler\traverseDependencies.js:297:473
 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 3.9% (123/621), failed.


```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
 INFO no standard startup: panel is active
workbench.main.js:sourcemap:3225 [fknop.vscode-npm]:  “npm-script.start” repeatly appear in "commands" part
workbench.main.js:sourcemap:3225 [fknop.vscode-npm]:  “npm-script.start” repeatly appear in "commands" part
workbench.main.js:sourcemap:3225 [jundat95.react-native-snippet]: “contributes.react-native-snippet.language”中存在未知的语言。提供的值: jsx
w._logMessageInConsole @ workbench.main.js:sourcemap:3225
workbench.main.js:sourcemap:3225 [santosh.react-native-snippet]: “contributes.react-native-snippet.language”中存在未知的语言。提供的值: jsx
w._logMessageInConsole @ workbench.main.js:sourcemap:3225
workbench.main.js:sourcemap:272 [Extension Host] vscode-icons is active!
workbench.main.js:sourcemap:272 [Extension Host] (node:10088) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ workbench.main.js:sourcemap:272
```
- Output of the React Native:Run android console:
```
[Warning] Target simulator is not supported for Android platform. If you want to use particular device or simulator for launching Android app, please specify  device id (as in 'adb devices' output) instead.

[Info] local.properties file doesn't exist. Using Android SDK location from PATH.

[Info] Starting React Native Packager.

Scanning folders for symlinks in e:\rn_pro\fastman2\src\apps\node_modules (155ms)
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee130Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore130Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp3130Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0554Library UP-TO-DATE
:app:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:transformClassesWithDexForDebug UP-TO-DATE
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateSigningDebug
:app:packageDebug UP-TO-DATE
:app:assembleDebug UP-TO-DATE
:app:installDebug
Installing APK 'app-debug.apk' on 'Custom Phone - 7.0.0 - API 24 - 768x1280 - 7.0' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 13.998 secs
Running D:\android-studio-sdk/platform-tools/adb -s 192.168.11.101:5555 reverse tcp:8081 tcp:8081
Starting the app on 192.168.11.101:5555 (D:\android-studio-sdk/platform-tools/adb -s 192.168.11.101:5555 shell am start -n com.apps/com.apps.MainActivity)...
Starting: Intent { cmp=com.apps/.MainActivity }
```
## Simulator Behavior（Genymotion）
![qq 20180828154550](https://user-images.githubusercontent.com/17918538/44708512-eae06600-aad9-11e8-9468-3ad63583e1c6.png)
## Debug server host & port for device
![qq 20180828155733](https://user-images.githubusercontent.com/17918538/44709009-2b8caf00-aadb-11e8-912b-8be26832f381.png)

## Project structure
![qq 20180828141416](https://user-images.githubusercontent.com/17918538/44704193-05f8a900-aacd-11e8-8924-0056ea99cc43.png)
![qq 20180828141429](https://user-images.githubusercontent.com/17918538/44704232-29bbef00-aacd-11e8-9201-afdf4a1f681a.png)
![qq 20180828141441](https://user-images.githubusercontent.com/17918538/44704383-a0f18300-aacd-11e8-8cf2-ce822c282244.png)
![qq 20180828151425](https://user-images.githubusercontent.com/17918538/44706749-32182800-aad5-11e8-840d-1577cac156b5.png)

## Other configuration
- launch.json
```
{
            "name": "Debug Android",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "launch",
            "platform": "android",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/.vscode/.react"
}
```
- settings.json
```
    "react-native-tools.projectRoot": "./src/apps",
    "react-native.android.runArguments.simulator": ["192.168.11.102:5555"]
```
@ruslan-bikkinin

**Comment by soeasyjx** [comment]
@ruslan-bikkinin

**Comment by ruslan-bikkinin** [comment]
Hi @soeasyjx and sorry for delayed response. Could you please try to replace` "platform": "android"` with `  "platform": "exponent"` in your debug configuration in `launch.json` and let us know if it works.

**Comment by soeasyjx** [comment]
Let me try

**Comment by soeasyjx** [comment]
I just want to debug in the android simulator, not in Expo.

**Comment by ruslan-bikkinin** [comment]
@soeasyjx according to screenshots you posted your project is an Expo one. If you want to debug Expo application on android, you need, at first, install expo app on your android simulator, then start debugging in VS Code using "platform": "exponent". Once the packager starts, the extension will open a separate tab with QR code to scan from the Exponent app. Once you do so, the Exponent app will connect to the packager and begin running your app. Please, follow [this documentation section](https://github.com/Microsoft/vscode-react-native/blob/master/doc/expo.md) for more info. 
Please, try to debug expo app using proper way for such kind of applications by following documentation section above and if it won't help please do the following:
* Prepare demo project so we could reproduce it on our side. We are asking for this, because, seems to be that your project uses different stuff like lerna, typescript, expo and has specific configurations which makes it too difficult for us to recreate the similar one. You can use your current project, but without any important business logic and other personal information. Please, try to keep it as simple as possible. **Please, do not remove your configs and keep directory structure!**

I am looking forward to hearing from you.

**Comment by soeasyjx** [comment]
I will prepare the demonstration project，please wait 。

**Comment by soeasyjx** [comment]
I think it will be caused by the project structure

**Comment by soeasyjx** [comment]
I'll adjust the structure of the project，
Android cannot move project structure。
@ruslan-bikkinin
