### ISSUE TITLE
When debugging via vscode-react-native, the debugger needs to be stopped twice and the packager creates a /.expo/package-info.json file.

### ISSUE THREAD

**Issue by geocachingsyntaxerror** [Microsoft/vscode-react-native#784]
This may be an issue with my development environment and not vscode-react-native, but the symptoms are only present when using vscode-react-native. Any perspective would be appreciated. 

## Actual Behavior
1. Create new react native project via react-native init 
2. cd into project and open VS Code via code .
3. Open debugger tab and add a new set of React Native debug configurations
4. Hit the 'play' button to Debug iOS
5. (Observe the React Native Packager starts as indicated at the bottom of Visual Studio Code, the app starts in the simulator and the debugger attaches.) 
6. Click the stop button on the debugger 
7. (Observe nothing happens)
8. Click the stop button on the debugger again
9. (Observe debugger stops and the packager is still running as indicated by the bottom status bar at the bottom of Visual Studio code)
11. Click the stop button on the React Native Packager at the bottom of Visual Studio Code
10. (Observe the packager stops and the /.expo/packager-info.json file is created in the project. )

## Expected Behavior
1. Debugger stops when clicking stop the first time
2. No /.expo/package-info.json file is created as this is not an expo project.
3. No mention of expo in output

## Software versions
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 18.43 GB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3
        API Levels: 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: darwin x64
Adapter node: v8.9.3 x64
vscode-chrome-debug-core: 3.17.3
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Debugger worker loaded runtime on port 34737
Running application test ({
RCTLog.js:47
    initialProps =     {
    };
    rootTag = 11;
})
Running application "test" with appParams: {"rootTag":11,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
infoLog.js:16
React Native worker process thrown an error. Debugging won't work: Try reloading the JS from inside the app, or Reconnect the VS Code debugger: channel closed
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Info] Starting Packager

[Debug] Executing command: react-native start --port 8081 --root .vscode

Scanning folders for symlinks in /Users/stuart/Documents/projects/test/node_modules (11ms)
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   /Users/stuart/Documents/projects/test
   /Users/stuart/Documents/projects/test/.vscode 


Metro Bundler ready.

Loading dependency graph, done.
[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.bundle?platform=ios

 BUNDLE  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (509/509), done.

[Warning] The Bundle Cache was prewarmed.

[Info] Building and running application.

[Info] Enable JS Debugging

[Info] About to search for plist in base folder: /Users/stuart/Library/Developer/CoreSimulator/Devices/8A70C1DF-41D8-4C32-9290-E9CCD572FDF8/data/Containers/Data/Application pathAfter: Library/Preferences/org.reactjs.native.example.test.plist in each of the apps: 02A256DC-7806-48AC-85A7-ACFB4A4BB827,04C346BD-5AB1-4BA9-8098-5E0A33D8DF85,2C961428-BA9E-4EF4-B124-3891873F08F0,37314A99-876C-40ED-80E0-EF6914B8AEBB,38D527F8-0E61-4706-B186-D489469B39B5,3D7CCA8D-871F-4E7A-B68B-C395217FBDE2,3E4237A1-C137-499A-9C38-06F2A8AD4795,41297BA2-6A4C-4FAD-BA93-1A6041B6D164,4F53F446-6A5E-4AB3-A671-80C0D511D55A,56544C17-1690-4B8A-8E5E-01174238D521,5B7DB68E-BEC7-4EB6-BC19-A4812F1E0E30,63278F24-3ECD-4A12-9A44-43EB4FCD12F3,6951DD5D-908E-43E9-90A9-7F8D29F91A0F,6BE05D44-8DFF-4686-B8A7-5A8D057D1362,6E35A295-33CD-4FA5-9F98-00C7DD77DFEE,6F92D77D-19E7-4712-9155-79DF6F15E41B,7512C443-9415-4536-95FE-E2BAE488C19E,792B5CC4-F561-4FDF-9C06-8A3742315507,7F370A59-AB7D-45E4-BB87-00ADCC73E04D,8D1A0AFA-49BA-41EB-BADA-7F2D74BCCC33,8FEA5708-DC07-4FAE-8248-8DDC1EA8CF23,9900CF0A-3158-421E-8E8E-02B2BB0AAD60,9EC1B7EA-D7BF-40C6-8D60-9F41D5F73C6F,A16FA45A-9B79-49E9-9386-374A81DD86FB,A392760A-953C-4B1B-8CC8-CB07EB5462EE,A58DF794-A284-4154-B909-33AA4680E609,B17DF34D-4D09-4DA5-8BC5-8944B7DB19F1,BB84F38D-FD43-42D5-8707-3EC162389971,C21839D0-68B0-45FA-8E63-9FC4C2B7D076,D888159B-3937-49B4-A259-314B6E11CEF8,D9668168-FF97-48A3-8DF9-ACDC97545976,DA47B6B9-64B0-4B6F-876B-55270D9B8EA1,EAC01470-29E9-494D-8D25-2C6F4AE39388,ECC8BFB8-5F30-4F95-9E8A-D569A00B8AAA,F6D87967-F2A6-4C1D-8102-6C2DAA7E1AF5,FBDE0622-0A7B-4476-AF00-12239B4E9633

 BUNDLE  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

Starting custom debugger by executing: echo A debugger is not needed:  "/Users/stuart/Documents/projects/test" "/Users/stuart/Documents/projects/test/.vscode"
 BUNDLE  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

 BUNDLE  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

 MAP  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

[Info] Stopping Packager

[Info] Packager stopped

[Debug] Stopping Exponent

[Debug] Exponent Stopped
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
 INFO no standard startup: panel is active
TMSyntax.ts:47 Overwriting grammar scope name to file mapping for scope source.swift.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/swift/syntaxes/swift.tmLanguage.json.
New grammar file: file:///Users/stuart/.vscode/extensions/Kasik96.swift-0.0.3/syntaxes/swift.tmLanguage
e.register @ TMSyntax.ts:47
TMSyntax.ts:47 Overwriting grammar scope name to file mapping for scope source.groovy.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/groovy/syntaxes/groovy.tmLanguage.json.
New grammar file: file:///Users/stuart/.vscode/extensions/naco-siren.gradle-language-0.2.3/syntaxes/groovy.tmLanguage.json
e.register @ TMSyntax.ts:47
console.ts:136 [Extension Host] vscode-icons is active!
console.ts:136 [Extension Host] activating extension
console.ts:136 [Extension Host] (node:11360) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```

**Comment by federicot** [comment]
It happens to me too. But I do get an error the first time I click stop.
```
Error processing "terminate": Error: kill ESRCH
    at Object._errnoException (util.js:1024:11)
    at process.kill (internal/process.js:183:18)
    at Object.<anonymous> (/Users/federicot/.vscode/extensions/ms-vscode.node-debug2-1.27.1/out/src/nodeDebugAdapter.js:466:25)
    at Generator.next (<anonymous>)
    at /Users/federicot/.vscode/extensions/ms-vscode.node-debug2-1.27.1/out/src/nodeDebugAdapter.js:10:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/federicot/.vscode/extensions/ms-vscode.node-debug2-1.27.1/out/src/nodeDebugAdapter.js:6:12)
    at Object.terminate (/Users/federicot/.vscode/extensions/ms-vscode.node-debug2-1.27.1/out/src/nodeDebugAdapter.js:461:16)
    at Object.dispatchRequest (/Users/federicot/.vscode/extensions/vsmobile.vscode-react-native-0.6.16/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugSession.js:75:82)
    at Object.dispatchRequest (/Users/federicot/.vscode/extensions/vsmobile.vscode-react-native-0.6.16/src/debugger/nodeDebugWrapper.js:50:26)
```

Visual Studio Code: 1.26.1
React Native Tools: 0.6.16
Node: 8.11.3

**Comment by ruslan-bikkinin** [comment]
Hi @geocachingsyntaxerror and thanks for reporting. I believe, that something has been broken between 1.25 and 1.26 versions of VS Code, because I couldn't reproduce it in 1.25. I will investigate it and let you know about the results.
