### ISSUE TITLE
React-native android app not opening in debug mode (but opens in release mode) after installing vscode react-native-tools debugger.

### ISSUE THREAD

**Issue by msnikhil** [Microsoft/vscode-react-native#787]
## Actual Behavior
1. Install React native tools extension.
2. Update launch.json file to include respective configurations for debug andorid/ios.
3. Select Attach to debugger before building app in debug mode.
4. Build the app.
5. Build fails with error cannot find the adb command (invalid path).
6. Uninstall the extension and try building again.
7. App builds successfully but fails to open.

## Expected Behavior
1. Debug build must open successfully after building.

## Software versions
- React-Native VS Code extension version: 0.6.15 (Not sure but should be the latest version on 29th Aug 2018).
- VSCode version: 1.26.1
- OS platform and version: Windows 10 Pro, OS build 17134.228
- NodeJS version: 6.11.2
- React Native version: 0.55.0
- Expo SDK version (include if relevant): N/A

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
08-30 13:15:42.896 6228-6491/? E/AbstractTracker: Can't create handler inside thread that has not called Looper.prepare()
08-30 13:15:42.957 25112-25112/? E/art: Failed to send JDWP packet APNM to debugger (-1 of 51): Broken pipe
08-30 13:15:42.961 25112-25118/? E/art: Failed sending reply to debugger: Broken pipe
08-30 13:15:43.052 25112-25138/? E/Theme: Different package name.com.<APP_NAME>,com.google.android.gms
08-30 13:15:43.110 25112-25151/? E/AbstractTracker: Can't create handler inside thread that has not called Looper.prepare()
08-30 13:15:43.155 18392-18909/? E/Theme: Different package name.com.facebook.katana,com.google.android.gms
08-30 13:15:43.246 18666-22557/? E/NetworkScheduler: Invalid component specified.
08-30 13:15:43.332 25112-25165/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                Process: com.<APP_NAME>, PID: 25112
                                                java.lang.NoClassDefFoundError: com.facebook.react.modules.fresco.SystraceRequestListener
                                                    at com.facebook.react.modules.fresco.FrescoModule.getDefaultConfigBuilder(FrescoModule.java:149)
                                                    at com.facebook.react.modules.fresco.FrescoModule.getDefaultConfig(FrescoModule.java:138)
                                                    at com.facebook.react.modules.fresco.FrescoModule.initialize(FrescoModule.java:101)
                                                    at com.facebook.react.bridge.ModuleHolder.doInitialize(ModuleHolder.java:198)
                                                    at com.facebook.react.bridge.ModuleHolder.markInitializable(ModuleHolder.java:86)
                                                    at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceInitialized(NativeModuleRegistry.java:123)
                                                    at com.facebook.react.bridge.CatalystInstanceImpl$2.run(CatalystInstanceImpl.java:387)
                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
                                                    at android.os.Looper.loop(Looper.java:152)
                                                    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
                                                    at java.lang.Thread.run(Thread.java:818)
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
N/A
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
N/A
```

**Comment by msnikhil** [comment]
I found that the issue was not from the extension but from one of the packages in was using in the project. Updating the package to the latest version resolved my issue. Thank you for bearing with me :)
