### ISSUE TITLE
Failed to start the React Native packager

### ISSUE THREAD

**Issue by zenz** [Microsoft/vscode-react-native#795]
## Actual Behavior
1. Packager cannot start up
Error msg: error: unknown option `--root'

## Expected Behavior
1. Packager start up successfully

## Software versions
- React-Native VS Code extension version: 
- VSCode version:  1.27.1
- OS platform and version: 
- NodeJS version: 8.12.0
- React Native version: 0.57.0-rc.4

Stack: Error: Failed to start the React Native packager: Could not start the packager.
    at Function.getWrappedError (C:\Users\Simon\.vscode\extensions\vsmobile.vscode-react-native-0.6.16\src\common\error\internalError.js:35:16)
    at Function.wrapError (C:\Users\Simon\.vscode\extensions\vsmobile.vscode-react-native-0.6.16\src\common\error\errorHelper.js:18:44)
    at resultOfCode.done.reason (C:\Users\Simon\.vscode\extensions\vsmobile.vscode-react-native-0.6.16\src\common\entryPointHandler.js:43:72)
    at _rejected (C:\Users\Simon\.vscode\extensions\vsmobile.vscode-react-native-0.6.16\node_modules\q\q.js:844:24)
    at C:\Users\Simon\.vscode\extensions\vsmobile.vscode-react-native-0.6.16\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\Simon\.vscode\extensions\vsmobile.vscode-react-native-0.6.16\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\Simon\.vscode\extensions\vsmobile.vscode-react-native-0.6.16\node_modules\q\q.js:788:41)
    at C:\Users\Simon\.vscode\extensions\vsmobile.vscode-react-native-0.6.16\node_modules\q\q.js:604:44
    at runSingle (C:\Users\Simon\.vscode\extensions\vsmobile.vscode-react-native-0.6.16\node_modules\q\q.js:137:13)
    at flush (C:\Users\Simon\.vscode\extensions\vsmobile.vscode-react-native-0.6.16\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by ruslan-bikkinin** [comment]
Hi @zenz and thanks for reaching us. Looks like we already have similar issue https://github.com/Microsoft/vscode-react-native/issues/790, so I am closing this as duplicate.
