### ISSUE TITLE
React native 0.57.x error

### ISSUE THREAD

**Issue by jas99** [Microsoft/vscode-react-native#811]
Running react init project of 0.57.2 and 0.57.3 produces this error

```
[Info] Starting Packager

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   d:\repo\keybase\skooly\skooly\packages\client\react-native 

[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.bundle?platform=android

Loading dependency graph, done.
[Info] Building and running application.

::ffff:127.0.0.1 - - [13/Oct/2018:16:11:06 +0000] "GET /index.bundle?platform=android HTTP/1.1" 500 - "-" "-"
error: bundling failed: ReferenceError: SHA-1 for file d:\repo\keybase\skooly\skooly\packages\client\react-native\index.js is not computed
    at DependencyGraph.getSha1 (d:\repo\keybase\skooly\skooly\packages\client\react-native\node_modules\metro\src\node-haste\DependencyGraph.js:200:13)
    at d:\repo\keybase\skooly\skooly\packages\client\react-native\node_modules\metro\src\DeltaBundler\Transformer.js:164:26
    at Generator.next (<anonymous>)
    at step (d:\repo\keybase\skooly\skooly\packages\client\react-native\node_modules\metro\src\DeltaBundler\Transformer.js:31:30)
    at d:\repo\keybase\skooly\skooly\packages\client\react-native\node_modules\metro\src\DeltaBundler\Transformer.js:50:14
    at new Promise (<anonymous>)
    at d:\repo\keybase\skooly\skooly\packages\client\react-native\node_modules\metro\src\DeltaBundler\Transformer.js:28:12
    at Transformer.transformFile (d:\repo\keybase\skooly\skooly\packages\client\react-native\node_modules\metro\src\DeltaBundler\Transformer.js:188:7)
    at d:\repo\keybase\skooly\skooly\packages\client\react-native\node_modules\metro\src\Bundler.js:78:34
    at Generator.next (<anonymous>)
[Error] Error: Unknown error: not all success patterns were matched.
It means that "react-native run-android" command failed. Please, check the View -> Toggle Output -> React Native, View -> Toggle Output -> React Native: Run android output windows.
```

## Software versions
- React-Native VS Code extension version: 0.6.18 
- VSCode version: 1.27.2
- OS platform and version: windows 10x64 
- NodeJS version: v10.7.0
- React Native version: 0.57.3

**Comment by SounD120** [comment]
Hi @jas99. Could you please paste an output from React Native: Run android output window? 
![image](https://user-images.githubusercontent.com/32372875/46932064-9d529500-d056-11e8-9a07-052f3fca3013.png)

**Comment by jas99** [comment]
Lemme put out all outputs 
React Native
```
[Info] Stopping Packager

[Info] Packager stopped

[Info] Starting Packager

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   d:\play\rntest1 

[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.bundle?platform=android

Loading dependency graph, done.
[Info] Building and running application.

::ffff:127.0.0.1 - - [15/Oct/2018:10:05:48 +0000] "GET /index.bundle?platform=android HTTP/1.1" 500 - "-" "-"
error: bundling failed: ReferenceError: SHA-1 for file d:\play\rntest1\index.js is not computed
    at DependencyGraph.getSha1 (d:\play\rntest1\node_modules\metro\src\node-haste\DependencyGraph.js:200:13)
    at d:\play\rntest1\node_modules\metro\src\DeltaBundler\Transformer.js:164:26
    at Generator.next (<anonymous>)
    at step (d:\play\rntest1\node_modules\metro\src\DeltaBundler\Transformer.js:31:30)
    at d:\play\rntest1\node_modules\metro\src\DeltaBundler\Transformer.js:50:14
    at new Promise (<anonymous>)
    at d:\play\rntest1\node_modules\metro\src\DeltaBundler\Transformer.js:28:12
    at Transformer.transformFile (d:\play\rntest1\node_modules\metro\src\DeltaBundler\Transformer.js:188:7)
    at d:\play\rntest1\node_modules\metro\src\Bundler.js:78:34
    at Generator.next (<anonymous>)
Starting custom debugger by executing: echo A debugger is not needed:  "d:\play\rntest1"
::ffff:127.0.0.1 - - [15/Oct/2018:10:06:01 +0000] "GET /launch-js-devtools HTTP/1.1" 200 - "-" "okhttp/3.10.0"
[Info] Enable JS Debugging

Starting custom debugger by executing: echo A debugger is not needed:  "d:\play\rntest1"
::ffff:127.0.0.1 - - [15/Oct/2018:10:06:03 +0000] "GET /launch-js-devtools HTTP/1.1" 200 - "-" "okhttp/3.10.0"
Starting custom debugger by executing: echo A debugger is not needed:  "d:\play\rntest1"
::ffff:127.0.0.1 - - [15/Oct/2018:10:06:03 +0000] "GET /launch-js-devtools HTTP/1.1" 200 - "-" "okhttp/3.10.0"
Starting custom debugger by executing: echo A debugger is not needed:  "d:\play\rntest1"
::ffff:127.0.0.1 - - [15/Oct/2018:10:06:06 +0000] "GET /launch-js-devtools HTTP/1.1" 200 - "-" "okhttp/3.10.0"
```
React Native: Run Android
```
[Warning] Target simulator is not supported for Android platform. If you want to use particular device or simulator for launching Android app, please specify  device id (as in 'adb devices' output) instead.

[Info] Using Android SDK location defined in android/local.properties file: C:\Users\jas\AppData\Local\Android\Sdk.

[Info] Starting React Native Packager.

Building and installing the app on the device (cd android && gradlew.bat installDebug)...
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to C:\Users\jas\AppData\Local\Android\Sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:checkDebugManifest UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:prepareLintJar UP-TO-DATE
:app:mainApkListPersistenceDebug UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:createDebugCompatibleScreenManifests UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:splitsDiscoveryTaskDebug UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:javaPreCompileDebug UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk NO-SOURCE
:app:compileDebugSources UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:copyDebugBundledJs SKIPPED
:app:transformClassesWithDexBuilderForDebug UP-TO-DATE
:app:transformDexArchiveWithExternalLibsDexMergerForDebug UP-TO-DATE
:app:transformDexArchiveWithDexMergerForDebug UP-TO-DATE
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
:app:processDebugJavaRes NO-SOURCE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateSigningDebug UP-TO-DATE
:app:packageDebug UP-TO-DATE
:app:assembleDebug UP-TO-DATE
:app:installDebug
Installing APK 'app-debug.apk' on 'Nexus_5X_API_28_x86(AVD) - 9' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL in 3s
27 actionable tasks: 1 executed, 26 up-to-date
Running adb -s emulator-5554 reverse tcp:8081 tcp:8081
Starting the app on emulator-5554 (adb -s emulator-5554 shell am start -n com.rntest1/com.rntest1.MainActivity)...
Starting: Intent { cmp=com.rntest1/.MainActivity }
```
Logcat emulator 554
```
[Info] 10-15 15:35:48.002  8237  8237 D ReactNative: ReactInstanceManager.detachViewFromInstance()


[Info] LogCat monitoring stopped because the process exited.

[Info] 10-15 15:36:04.844  8400  8400 D ReactNative: ReactInstanceManager.ctor()


[Info] 10-15 15:36:05.033  8400  8400 D ReactNative: ReactInstanceManager.createReactContextInBackground()
10-15 15:36:05.033  8400  8400 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()


[Info] 10-15 15:36:05.877  8400  8400 D ReactNative: ReactInstanceManager.onReloadWithJSDebugger()


[Info] 10-15 15:36:05.882  8400  8400 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
10-15 15:36:05.882  8400  8400 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()


[Info] 10-15 15:36:06.132  8400  8432 D ReactNative: ReactInstanceManager.createReactContext()


[Info] 10-15 15:36:06.690  8400  8432 D ReactNative: Initializing React Xplat Bridge.


[Info] 10-15 15:36:06.697  8400  8432 D ReactNative: Initializing React Xplat Bridge before initializeBridge


[Info] 10-15 15:36:06.704  8400  8432 D ReactNative: Initializing React Xplat Bridge after initializeBridge


[Info] 10-15 15:36:06.704  8400  8432 D ReactNative: CatalystInstanceImpl.runJSBundle()


[Info] 10-15 15:36:06.720  8400  8438 D ReactNative: ReactInstanceManager.setupReactContext()
10-15 15:36:06.720  8400  8438 D ReactNative: CatalystInstanceImpl.initialize()
10-15 15:36:06.725  8400  8438 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
```
vscode debug console

```
OS: win32 x64
Adapter node: v8.9.3 x64
vscode-chrome-debug-core: 3.17.3
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Debugger worker loaded runtime on port 9842
******** Unhandled error in debug adapter: SyntaxError: Unexpected token L in JSON at position 0
    at JSON.parse (<anonymous>)
    at Pipe.channel.onread (internal/child_process.js:470:28)
```

Windows work environment was sort of temporary and I will be moving back to linux at some point; will let u know if its realated to my setup.

Is the extensions works for you and whats your env?
PS: lemme know if you need more info.

Thx

**Comment by SounD120** [comment]
@jas99 My test config for this case:
- Windows 10 x64 (android 8.1 emulator)
- Node.js 8.12
- RN 0.57.3
- VSCode v 1.28.1
And it's working without such errors. So could you try to use latest LTS version or latest stable, cause it's looking like node.js issue?

**Comment by jas99** [comment]
Bingo; node lts fixed packager issue; but now debugger won't attach. Let me drill in little bit and will post right back.

Thx

**Comment by SounD120** [comment]
Hi @jas99. Looks like the original issue was solved, so I'm closing this issue for now, but if you have some updates - you can reopen this issue, or create new with all new information you have. Thanks.

**Comment by IceApriler** [comment]
@SounD120 Hi, why can't i debug?

React Native: Run Android
```
[Warning] Target simulator is not supported for Android platform. If you want to use particular device or simulator for launching Android app, please specify  device id (as in 'adb devices' output) instead.

[Info] Using Android SDK location defined in android/local.properties file: /Users/april/Library/Android/sdk.

[Info] Starting React Native Packager.

Building and installing the app on the device (cd android && ./gradlew installDebug)...
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
:app:preBuild UP-TO-DATE
:react-native-picker:preBuild UP-TO-DATE
:react-native-picker:preDebugBuild UP-TO-DATE
:react-native-picker:checkDebugManifest
:react-native-picker:processDebugManifest
:app:preDebugBuild
:react-native-picker:compileDebugAidl
:app:compileDebugAidl
:react-native-picker:packageDebugRenderscript NO-SOURCE
:app:compileDebugRenderscript
:app:checkDebugManifest
:app:generateDebugBuildConfig
:app:prepareLintJar
:app:mainApkListPersistenceDebug
:app:bundleDebugJsAndAssets SKIPPED
:app:generateDebugResValues
:app:generateDebugResources
:react-native-picker:compileDebugRenderscript
:react-native-picker:generateDebugResValues
:react-native-picker:generateDebugResources
:react-native-picker:packageDebugResources
:app:mergeDebugResources
:app:createDebugCompatibleScreenManifests
:app:processDebugManifest
:app:splitsDiscoveryTaskDebug
:react-native-picker:platformAttrExtractor
:react-native-picker:generateDebugBuildConfig
:react-native-picker:prepareLintJar
:react-native-picker:javaPreCompileDebug
:react-native-picker:processDebugJavaRes NO-SOURCE
:app:compileDebugNdk NO-SOURCE
:app:mergeDebugShaders
:app:compileDebugShaders
:app:generateDebugAssets
:react-native-picker:mergeDebugShaders
:react-native-picker:compileDebugShaders
:react-native-picker:generateDebugAssets
:react-native-picker:packageDebugAssets
:app:mergeDebugAssets
:app:copyDebugBundledJs SKIPPED
:app:mergeDebugJniLibFolders
:react-native-picker:compileDebugNdk NO-SOURCE
:react-native-picker:mergeDebugJniLibFolders
:react-native-picker:transformNativeLibsWithMergeJniLibsForDebug
:react-native-picker:generateDebugRFile
:app:processDebugResources
:app:generateDebugSources
:react-native-picker:generateDebugSources
:react-native-picker:compileDebugJavaWithJavac?: /Users/april/myfile/www/gitstore/operator_app/node_modules/react-native-picker/android/src/main/java/com/beefe/picker/PickerViewModule.java?????????? API?
?: ??????, ??? -Xlint:deprecation ?????

:react-native-picker:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
:app:javaPreCompileDebug
:app:compileDebugJavaWithJavac
:app:compileDebugSources
:app:transformClassesWithDexBuilderForDebug
:app:transformDexArchiveWithExternalLibsDexMergerForDebug
:app:transformDexArchiveWithDexMergerForDebug
:react-native-picker:transformNativeLibsWithIntermediateJniLibsForDebug
:app:transformNativeLibsWithMergeJniLibsForDebug
:app:processDebugJavaRes NO-SOURCE
:app:transformResourcesWithMergeJavaResForDebug
:app:validateSigningDebug
:app:packageDebug
:app:assembleDebug
:app:installDebug
Installing APK 'app-debug.apk' on 'Pixel_2_XL_API_28(AVD) - 9' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL in 35s
46 actionable tasks: 46 executed
Running /Users/april/Library/Android/sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
Starting the app on emulator-5554 (/Users/april/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -n cn.funxi.operator/cn.funxi.operator.MainActivity)...
Starting: Intent { cmp=cn.funxi.operator/.MainActivity }

```

**Comment by SounD120** [comment]
Hi, @IceApriler . Did you tried to [enable remote JS debugging](https://github.com/Microsoft/vscode-react-native/tree/improve-docs#debugging-react-native-applications)? If your issue is not connected to this, please create new issue with our [issue template](https://github.com/Microsoft/vscode-react-native/blob/master/.github/ISSUE_TEMPLATE.md).
